
gEvoExAppear_Gfx:: @ 0x0815A8A4
	.incbin "graphics/board_pickups/evo_item_ex.4bpp";

gEvoItem_Pals:: @ 0x0815C4C4
	.incbin "graphics/board_pickups/icon1_xp.gbapal";
	.incbin "graphics/board_pickups/icon2_leaf.gbapal";
	.incbin "graphics/board_pickups/icon3_fire.gbapal";
	.incbin "graphics/board_pickups/icon4_link.gbapal";
	.incbin "graphics/board_pickups/icon5_moon.gbapal";
	.incbin "graphics/board_pickups/icon6_water.gbapal";
	.incbin "graphics/board_pickups/icon7_bolt.gbapal";
	.incbin "graphics/board_pickups/icon8_sun.gbapal";
	.incbin "graphics/board_pickups/icon9_heart.gbapal";
	.incbin "graphics/board_pickups/icon10_pokeblock.gbapal";
	@ Six blank palettes, filling out the block. Solely containing a near-flat grey.
	.incbin "graphics/board_pickups/evo_item_unused.gbapal.bin"

gEvoLeafAppear_Gfx:: @ 0x0815C6C4
	.incbin "graphics/board_pickups/evo_item_leaf.4bpp";

gEvoFireAppear_Gfx:: @ 0x0815E2E4
	.incbin "graphics/board_pickups/evo_item_fire.4bpp";

gEvoHeartAppear_Gfx:: @ 0x0815FF04
	.incbin "graphics/board_pickups/evo_item_heart.4bpp";

gEvoLinkAppear_Gfx:: @ 0x08161B24
	.incbin "graphics/board_pickups/evo_item_link.4bpp";

gEvoMoonAppear_Gfx:: @ 0x08163744
	.incbin "graphics/board_pickups/evo_item_moon.4bpp";

gEvoWaterAppear_Gfx:: @ 0x08165364
	.incbin "graphics/board_pickups/evo_item_water.4bpp";

gEvoBoxAppear_Gfx:: @ 0x08166F84
	.incbin "graphics/board_pickups/evo_item_box.4bpp";

gEvoSunAppear_Gfx:: @ 0x08168BA4
	.incbin "graphics/board_pickups/evo_item_sun.4bpp";

gEvoBoltAppear_Gfx:: @ 0x0816A7C4
	.incbin "graphics/board_pickups/evo_item_bolt.4bpp";
