
gRubyBoardPaletteSet1:: @ 0x081B1584
    .incbin "graphics/stage/ruby/ruby_board_palset_1.gbapal"

gSapphireBoardPaletteSet1:: @ 0x081B1784
    .incbin "graphics/stage/sapphire/sapphire_board_palset_1.gbapal"

gDusclopsBoardPaletteSet1:: @ 0x081B1984
    .incbin "graphics/stage/dusclops/dusclops_board_palset_1.gbapal"

gKecleonBoardPaletteSet1:: @ 0x081B1B84
    .incbin "graphics/stage/kecleon/kecleon_board_palset_1.gbapal"

gKyogreBoardPaletteSet1:: @ 0x081B1D84
    .incbin "graphics/stage/kyogre/kyogre_board_palset_1.gbapal"

gGroudonBoardPaletteSet1:: @ 0x081B1F84
    .incbin "graphics/stage/groudon/groudon_board_palset_1.gbapal"

gRayquazaBoardPaletteSet1:: @ 0x081B2184
    .incbin "graphics/stage/rayquaza/rayquaza_board_palset_1.gbapal"

gSphealBoardPaletteSet1:: @ 0x081B2384
    .incbin "graphics/stage/spheal/spheal_board_palset_1.gbapal"

gRubyBoardPaletteSet2:: @ 0x081B2584
    .incbin "graphics/stage/ruby/ruby_board_palset_2.gbapal"

gSapphireBoardPaletteSet2:: @ 0x081B2784
    .incbin "graphics/stage/sapphire/sapphire_board_palset_2.gbapal"

gDusclopsBoardPaletteSet2:: @ 0x081B2984
    .incbin "graphics/stage/dusclops/dusclops_board_palset_2.gbapal"

gKecleonBoardPaletteSet2:: @ 0x081B2B84
    .incbin "graphics/stage/kecleon/kecleon_board_palset_2.gbapal"

gKyogreBoardPaletteSet2:: @ 0x081B2D84
    .incbin "graphics/stage/kyogre/kyogre_board_palset_2.gbapal"

gGroudonBoardPaletteSet2:: @ 0x081B2F84
    .incbin "graphics/stage/groudon/groudon_board_palset_2.gbapal"

gRayquazaBoardPaletteSet2:: @ 0x081B3184
    .incbin "graphics/stage/rayquaza/rayquaza_board_palset_2.gbapal"

gSphealBoardPaletteSet2:: @ 0x081B3384
    .incbin "graphics/stage/spheal/spheal_board_palset_2.gbapal"

gRubyBoardPaletteSet0:: @ 0x081B3584
    .incbin "graphics/stage/ruby/ruby_board_palset_0.gbapal"

gBonusStageObjPal:: @ 0x081B36A4
	.incbin "graphics/stage/main/bonus_stage_obj.gbapal"

gSapphireBoardPaletteSet0:: @ 0x081B3784
    .incbin "graphics/stage/sapphire/sapphire_board_palset_0.gbapal"

gDusclopsBoardPaletteSet0:: @ 0x081B3984
	.incbin "graphics/stage/dusclops/dusclops_board_palset_0.gbapal"

gKecleonBoardPaletteSet0:: @ 0x081B3B84
    .incbin "graphics/stage/kecleon/kecleon_board_palset_0.gbapal"

gKyogreBoardPaletteSet0:: @ 0x081B3D84
    .incbin "graphics/stage/kyogre/kyogre_board_palset_0.gbapal"

gGroudonBoardPaletteSet0:: @ 0x081B3F84
    .incbin "graphics/stage/groudon/groudon_board_palset_0.gbapal"

gRayquazaBoardPaletteSet0:: @ 0x081B4184
    .incbin "graphics/stage/rayquaza/rayquaza_board_palset_0.gbapal"

gSphealBoardPaletteSet0:: @ 0x081B4384
    .incbin "graphics/stage/spheal/spheal_board_palset_0.gbapal"
