
@ The puff that reveals the catch mon.
gCatchMonAppearFx_Gfx:: @ 0x0839C78C
	.incbin "graphics/stage/main/catch_mon_appear_fx.4bpp"
	.space 0x20

gCatchMonAppearFx_Pal:: @ 0x0839DBAC
	.incbin "graphics/stage/main/catch_mon_appear_fx.gbapal"

gCatchTile_RevealTilesGfx:: @ 0x0839DDAC
	.incbin "graphics/stage/main/catch_tile_reveal.4bpp"
	.space 0xA00

gCatchTile_Reveal_Pal:: @ 0x083A05CC
	.incbin "graphics/stage/main/catch_tile_reveal.gbapal"

@ Lightning strike
gCatchTile_BurstStart_Gfx:: @ 0x083A07CC
	.incbin "graphics/stage/main/catch_tile_burst_start.4bpp"
	.space 0x20

gCatchTile_BurstStart_Pal:: @ 0x083A27EC
	.incbin "graphics/stage/main/catch_tile_burst_start.gbapal"

@ Tile Grid
gCatchTile_BurstStage2_Gfx:: @ 0x083A29EC
	.incbin "graphics/stage/main/catch_tile_burst_stage2.4bpp"
	.space 0x20

gCatchTile_BurstStage2_Pal:: @ 0x083A320C
	.incbin "graphics/stage/main/catch_tile_burst_stage2.gbapal"

gCatchTile_BurstStage3_Gfx:: @ 0x083A340C
	.incbin "graphics/stage/main/catch_tile_burst_stage3.4bpp"
	.space 0x20

gCatchTile_BurstStage3_Pal:: @ 0x083A542C
	.incbin "graphics/stage/main/catch_tile_burst_stage3.gbapal"

gCatchTile_BurstStage4_Gfx:: @ 0x083A562C
	.incbin "graphics/stage/main/catch_tile_burst_stage4.4bpp"
	.space 0x20

gCatchTile_BurstStage4_Pal:: @ 0x083A6E4C
	.incbin "graphics/stage/main/catch_tile_burst_stage4.gbapal"
