gEvoNameDisplay_Pals:: @ 0x081B4584
	.incbin "graphics/stage/main/evo_name_display.gbapal"

gShopNameDisplay_Pals:: @ 0x081B45A4
	.incbin "graphics/stage/main/shop_name_display.gbapal"
	.space 0x1C0

@ Evolution selection background loop
gEvoModeBG0_0_Tilemap:: @ 0x081B4784
	.incbin "graphics/stage/main/evo_mode_bg0_frame0_tilemap.bin"

gEvoModeBG0_1_Tilemap:: @ 0x081B5784
	.incbin "graphics/stage/main/evo_mode_bg0_frame1_tilemap.bin"

gEvoModeBG0_2_Tilemap:: @ 0x081B6784
	.incbin "graphics/stage/main/evo_mode_bg0_frame2_tilemap.bin"

gEvoModeBG0_3_Tilemap:: @ 0x081B7784
	.incbin "graphics/stage/main/evo_mode_bg0_frame3_tilemap.bin"

gShopEvoUI_Pals:: @ 0x081B8784
	.incbin "graphics/stage/main/shop_evo_ui.gbapal"

@ Shop mode background loop
gShopModeBG0_0_Tilemap:: @ 0x081B8984
	.incbin "graphics/stage/main/shop_mode_bg0_frame0_tilemap.bin"

gShopModeBG0_1_Tilemap:: @ 0x081B9984
	.incbin "graphics/stage/main/shop_mode_bg0_frame1_tilemap.bin"

gShopModeBG0_2_Tilemap:: @ 0x081BA984
	.incbin "graphics/stage/main/shop_mode_bg0_frame2_tilemap.bin"

gShopModeBG0_3_Tilemap:: @ 0x081BB984
	.incbin "graphics/stage/main/shop_mode_bg0_frame3_tilemap.bin"

gSapphireShopSign_Pals:: @ 0x081BC984
	.incbin "graphics/stage/sapphire/shop_sign.gbapal"
