gFieldSelectWindow_Gfx:: @ 0x080A2C00
	.incbin "graphics/field_select/window_tiles.4bpp"

gUnknown_080A4000:: @ 0x080A4000
	.incbin "graphics/field_select/unknown_080A4000.bin"

gFieldSelectFrameShadowTilemap:: @ 0x080A4020
	.incbin "graphics/field_select/frame_shadow_tilemap.bin"

gFieldSelectMiniFields_Gfx:: @ 0x080A4820
	.incbin "graphics/field_select/mini_fields.4bpp"

gUnknown_080A8020:: @ 0x080A8020
	.incbin "graphics/field_select/unknown_080A8020.bin"

gFieldSelectWindowTilemap:: @ 0x080A8040
	.incbin "graphics/field_select/window_tilemap.bin"

gFieldSelectBGPals:: @ 0x080A8840
	.incbin "graphics/field_select/bg_pals.gbapal"

gFieldSelectSpritePals:: @ 0x080A8A40
	.incbin "graphics/field_select/sprite_pals.gbapal"

gFieldSelectSpriteGfx:: @ 0x080A8C40
	.incbin "graphics/field_select/sprites.4bpp"
