gMonCatchSprite_Pal:: @ 0x081AEBE4
	.incbin "graphics/mon_catch_sprites/catch_mon_01_treecko.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_02_torchic.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_03_mudkip.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_04_poochyena.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_05_zigzagoon.gbapal"

    .incbin "baserom.gba", 0x1AEC84, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_06_silcoon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_07_cascoon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_08_lombre.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_09_nuzleaf.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_10_tailow.gbapal"

    .incbin "baserom.gba", 0x1AEE84, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_11_wingull.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_12_slakoth.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_13_abra.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_14_nincada.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_15_loudred.gbapal"

    .incbin "baserom.gba", 0x1AF084, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_16_makuhita.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_17_goldeen.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_18_magikarp.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_19_marill.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_20_geodude.gbapal"

    .incbin "baserom.gba", 0x1AF284, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_21_nosepass.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_22_tentacool.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_23_sableye.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_24_mawile.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_25_machop.gbapal"

    .incbin "baserom.gba", 0x1AF484, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_26_meditite.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_27_electrike.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_28_magnemite.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_29_voltorb.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_30_volbeat.gbapal"

    .incbin "baserom.gba", 0x1AF684, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_31_illumise.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_32_doduo.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_33_roselia.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_34_carvanha.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_35_wailmer.gbapal"

    .incbin "baserom.gba", 0x1AF884, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_36_numel.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_37_slugma.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_38_torkoal.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_39_grimer.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_40_koffing.gbapal"

    .incbin "baserom.gba", 0x1AFA84, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_41_skarmory.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_42_vibrava.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_43_cacnea.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_44_swablu.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_45_zangoose.gbapal"

    .incbin "baserom.gba", 0x1AFC84, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_46_seviper.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_47_lunatone.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_48_solrock.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_49_barboach.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_50_corphish.gbapal"

    .incbin "baserom.gba", 0x1AFE84, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_51_baltoy.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_52_lileep.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_53_anorith.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_54_jigglypuff.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_55_febas.gbapal"

    .incbin "baserom.gba", 0x1B0084, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_56_castform.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_57_staryu.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_58_kecleon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_59_duskull.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_60_tropius.gbapal"

    .incbin "baserom.gba", 0x1B0284, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_61_absol.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_62_vulpix.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_63_pikachu.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_64_psyduck.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_65_wobbuffet.gbapal"

    .incbin "baserom.gba", 0x1B0484, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_66_girafarig.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_67_pinsir.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_68_heracross.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_69_rhyhorn.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_70_clamperl.gbapal"

    .incbin "baserom.gba", 0x1B0684, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_71_relicanth.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_72_luvdisc.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_73_shelgon.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_74_beldum.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_75_regirock.gbapal"

    .incbin "baserom.gba", 0x1B0884, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_76_regice.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_77_registeel.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_78_latias.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_79_latios.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_80_jirachi.gbapal"

    .incbin "baserom.gba", 0x1B0A84, 0x160

	.incbin "graphics/mon_catch_sprites/catch_mon_81_chikorita.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_82_cyndaquil.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_83_totodile.gbapal"
	.incbin "graphics/mon_catch_sprites/catch_mon_84_aerodactyl.gbapal"
