gMonHatchSpriteGroup0_Gfx:: @ 0x083C8B6C
	.incbin "graphics/mon_hatch_sprites/wurmple_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/lotad_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/seedot_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/ralts_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/surskit_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/shroomish_hatch.4bpp"

gMonHatchSpriteGroup1_Gfx:: @ 0x083CF0AC
	.incbin "graphics/mon_hatch_sprites/whismur_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/azurill_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/skitty_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/zubat_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/aron_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/plusle_hatch.4bpp"

gMonHatchSpriteGroup2_Gfx:: @ 0x083D55EC
	.incbin "graphics/mon_hatch_sprites/minun_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/oddish_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/gulpin_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/spoink_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/sandshrew_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/spinda_hatch.4bpp"

gMonHatchSpriteGroup3_Gfx:: @ 0x083DBB2C
	.incbin "graphics/mon_hatch_sprites/trapinch_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/igglybuff_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/shuppet_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/chimecho_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/pichu_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/wynaut_hatch.4bpp"

gMonHatchSpriteGroup4_Gfx:: @ 0x083E206C
	.incbin "graphics/mon_hatch_sprites/natu_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/phanpy_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/snorunt_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/spheal_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/corsola_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/chinchou_hatch.4bpp"

gMonHatchSpriteGroup5_Gfx:: @ 0x083E85AC
	.incbin "graphics/mon_hatch_sprites/horsea_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/bagon_hatch.4bpp"
	.incbin "graphics/mon_hatch_sprites/pichu_2_hatch.4bpp"
