gTreeckoPortrait_Pal:: @ 0x39AB8C
	.incbin "graphics/mon_portraits/treecko_portrait.gbapal"

gGrovylePortrait_Pal:: @ 0x39ABAC
	.incbin "graphics/mon_portraits/grovyle_portrait.gbapal"

gSceptilePortrait_Pal:: @ 0x39ABCC
	.incbin "graphics/mon_portraits/sceptile_portrait.gbapal"

gTorchicPortrait_Pal:: @ 0x39ABEC
	.incbin "graphics/mon_portraits/torchic_portrait.gbapal"

gCombuskenPortrait_Pal:: @ 0x39AC0C
	.incbin "graphics/mon_portraits/combusken_portrait.gbapal"

gBlazikenPortrait_Pal:: @ 0x39AC2C
	.incbin "graphics/mon_portraits/blaziken_portrait.gbapal"

gMudkipPortrait_Pal:: @ 0x39AC4C
	.incbin "graphics/mon_portraits/mudkip_portrait.gbapal"

gMarshtompPortrait_Pal:: @ 0x39AC6C
	.incbin "graphics/mon_portraits/marshtomp_portrait.gbapal"

gSwampertPortrait_Pal:: @ 0x39AC8C
	.incbin "graphics/mon_portraits/swampert_portrait.gbapal"

gPoochyenaPortrait_Pal:: @ 0x39ACAC
	.incbin "graphics/mon_portraits/poochyena_portrait.gbapal"

gMightyenaPortrait_Pal:: @ 0x39ACCC
	.incbin "graphics/mon_portraits/mightyena_portrait.gbapal"

gZigzagoonPortrait_Pal:: @ 0x39ACEC
	.incbin "graphics/mon_portraits/zigzagoon_portrait.gbapal"

gLinoonePortrait_Pal:: @ 0x39AD0C
	.incbin "graphics/mon_portraits/linoone_portrait.gbapal"

gWurmplePortrait_Pal:: @ 0x39AD2C
	.incbin "graphics/mon_portraits/wurmple_portrait.gbapal"

gSilcoonPortrait_Pal:: @ 0x39AD4C
	.incbin "graphics/mon_portraits/silcoon_portrait.gbapal"

gSilhouettePortrait_Pal:: @ 0x39AD6C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gBeautiflyPortrait_Pal:: @ 0x39AD8C
	.incbin "graphics/mon_portraits/beautifly_portrait.gbapal"

gCascoonPortrait_Pal:: @ 0x39ADAC
	.incbin "graphics/mon_portraits/cascoon_portrait.gbapal"

gDustoxPortrait_Pal:: @ 0x39ADCC
	.incbin "graphics/mon_portraits/dustox_portrait.gbapal"

gLotadPortrait_Pal:: @ 0x39ADEC
	.incbin "graphics/mon_portraits/lotad_portrait.gbapal"

gLombrePortrait_Pal:: @ 0x39AE0C
	.incbin "graphics/mon_portraits/lombre_portrait.gbapal"

gLudicoloPortrait_Pal:: @ 0x39AE2C
	.incbin "graphics/mon_portraits/ludicolo_portrait.gbapal"

gSeedotPortrait_Pal:: @ 0x39AE4C
	.incbin "graphics/mon_portraits/seedot_portrait.gbapal"

gNuzleafPortrait_Pal:: @ 0x39AE6C
	.incbin "graphics/mon_portraits/nuzleaf_portrait.gbapal"

gShiftryPortrait_Pal:: @ 0x39AE8C
	.incbin "graphics/mon_portraits/shiftry_portrait.gbapal"

gTaillowPortrait_Pal:: @ 0x39AEAC
	.incbin "graphics/mon_portraits/taillow_portrait.gbapal"

gSwellowPortrait_Pal:: @ 0x39AECC
	.incbin "graphics/mon_portraits/swellow_portrait.gbapal"

gWingullPortrait_Pal:: @ 0x39AEEC
	.incbin "graphics/mon_portraits/wingull_portrait.gbapal"

gPelilpperPortrait_Pal:: @ 0x39AF0C
	.incbin "graphics/mon_portraits/pelilpper_portrait.gbapal"

gRaltsPortrait_Pal:: @ 0x39AF2C
	.incbin "graphics/mon_portraits/ralts_portrait.gbapal"

gKirliaPortrait_Pal:: @ 0x39AF4C
	.incbin "graphics/mon_portraits/kirlia_portrait.gbapal"

gSilhouettePortrait_Pal_Copy1:: @ 0x39AF6C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gGardevoirPortrait_Pal:: @ 0x39AF8C
	.incbin "graphics/mon_portraits/gardevoir_portrait.gbapal"

gSurskitPortrait_Pal:: @ 0x39AFAC
	.incbin "graphics/mon_portraits/surskit_portrait.gbapal"

gMasquerainPortrait_Pal:: @ 0x39AFCC
	.incbin "graphics/mon_portraits/masquerain_portrait.gbapal"

gShroomishPortrait_Pal:: @ 0x39AFEC
	.incbin "graphics/mon_portraits/shroomish_portrait.gbapal"

gBreloomPortrait_Pal:: @ 0x39B00C
	.incbin "graphics/mon_portraits/breloom_portrait.gbapal"

gSlakothPortrait_Pal:: @ 0x39B02C
	.incbin "graphics/mon_portraits/slakoth_portrait.gbapal"

gVigorothPortrait_Pal:: @ 0x39B04C
	.incbin "graphics/mon_portraits/vigoroth_portrait.gbapal"

gSlakingPortrait_Pal:: @ 0x39B06C
	.incbin "graphics/mon_portraits/slaking_portrait.gbapal"

gAbraPortrait_Pal:: @ 0x39B08C
	.incbin "graphics/mon_portraits/abra_portrait.gbapal"

gKadabraPortrait_Pal:: @ 0x39B0AC
	.incbin "graphics/mon_portraits/kadabra_portrait.gbapal"

gAlakazamPortrait_Pal:: @ 0x39B0CC
	.incbin "graphics/mon_portraits/alakazam_portrait.gbapal"

gNincadaPortrait_Pal:: @ 0x39B0EC
	.incbin "graphics/mon_portraits/nincada_portrait.gbapal"

gNinjaskPortrait_Pal:: @ 0x39B10C
	.incbin "graphics/mon_portraits/ninjask_portrait.gbapal"

gShedinjaPortrait_Pal:: @ 0x39B12C
	.incbin "graphics/mon_portraits/shedinja_portrait.gbapal"

gWhismurPortrait_Pal:: @ 0x39B14C
	.incbin "graphics/mon_portraits/whismur_portrait.gbapal"

gSilhouettePortrait_Pal_2:: @ 0x39AF6C
	.incbin "graphics/mon_portraits/silhouette_2.gbapal"

gLoudredPortrait_Pal:: @ 0x39B18C
	.incbin "graphics/mon_portraits/loudred_portrait.gbapal"

gExploudPortrait_Pal:: @ 0x39B1AC
	.incbin "graphics/mon_portraits/exploud_portrait.gbapal"

gMakuhitaPortrait_Pal:: @ 0x39B1CC
	.incbin "graphics/mon_portraits/makuhita_portrait.gbapal"

gHariyamaPortrait_Pal:: @ 0x39B1EC
	.incbin "graphics/mon_portraits/hariyama_portrait.gbapal"

gGoldeenPortrait_Pal:: @ 0x39B20C
	.incbin "graphics/mon_portraits/goldeen_portrait.gbapal"

gSeakingPortrait_Pal:: @ 0x39B22C
	.incbin "graphics/mon_portraits/seaking_portrait.gbapal"

gMagikarpPortrait_Pal:: @ 0x39B24C
	.incbin "graphics/mon_portraits/magikarp_portrait.gbapal"

gGyaradosPortrait_Pal:: @ 0x39B26C
	.incbin "graphics/mon_portraits/gyarados_portrait.gbapal"

gAzurillPortrait_Pal:: @ 0x39B28C
	.incbin "graphics/mon_portraits/azurill_portrait.gbapal"

gMarillPortrait_Pal:: @ 0x39B2AC
	.incbin "graphics/mon_portraits/marill_portrait.gbapal"

gAzumarillPortrait_Pal:: @ 0x39B2CC
	.incbin "graphics/mon_portraits/azumarill_portrait.gbapal"

gGeodudePortrait_Pal:: @ 0x39B2EC
	.incbin "graphics/mon_portraits/geodude_portrait.gbapal"

gGravelerPortrait_Pal:: @ 0x39B30C
	.incbin "graphics/mon_portraits/graveler_portrait.gbapal"

gGolemPortrait_Pal:: @ 0x39B32C
	.incbin "graphics/mon_portraits/golem_portrait.gbapal"

gNosepassPortrait_Pal:: @ 0x39B34C
	.incbin "graphics/mon_portraits/nosepass_portrait.gbapal"

gSilhouettePortrait_Pal_Copy2:: @ 0x39B36C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gSkittyPortrait_Pal:: @ 0x39B38C
	.incbin "graphics/mon_portraits/skitty_portrait.gbapal"

gDelcattyPortrait_Pal:: @ 0x39B3AC
	.incbin "graphics/mon_portraits/delcatty_portrait.gbapal"

gZubatPortrait_Pal:: @ 0x39B3CC
	.incbin "graphics/mon_portraits/zubat_portrait.gbapal"

gGolbatPortrait_Pal:: @ 0x39B3EC
	.incbin "graphics/mon_portraits/golbat_portrait.gbapal"

gCrobatPortrait_Pal:: @ 0x39B40C
	.incbin "graphics/mon_portraits/crobat_portrait.gbapal"

gTentacoolPortrait_Pal:: @ 0x39B42C
	.incbin "graphics/mon_portraits/tentacool_portrait.gbapal"

gTentacruelPortrait_Pal:: @ 0x39B44C
	.incbin "graphics/mon_portraits/tentacruel_portrait.gbapal"

gSableyePortrait_Pal:: @ 0x39B46C
	.incbin "graphics/mon_portraits/sableye_portrait.gbapal"

gMawilePortrait_Pal:: @ 0x39B48C
	.incbin "graphics/mon_portraits/mawile_portrait.gbapal"

gAronPortrait_Pal:: @ 0x39B4AC
	.incbin "graphics/mon_portraits/aron_portrait.gbapal"

gLaironPortrait_Pal:: @ 0x39B4CC
	.incbin "graphics/mon_portraits/lairon_portrait.gbapal"

gAggronPortrait_Pal:: @ 0x39B4EC
	.incbin "graphics/mon_portraits/aggron_portrait.gbapal"

gMachopPortrait_Pal:: @ 0x39B50C
	.incbin "graphics/mon_portraits/machop_portrait.gbapal"

gMachokePortrait_Pal:: @ 0x39B52C
	.incbin "graphics/mon_portraits/machoke_portrait.gbapal"

gMachampPortrait_Pal:: @ 0x39B54C
	.incbin "graphics/mon_portraits/machamp_portrait.gbapal"

gSilhouettePortrait_Pal_Copy3:: @ 0x39B56C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gMedititePortrait_Pal:: @ 0x39B58C
	.incbin "graphics/mon_portraits/meditite_portrait.gbapal"

gMedichamPortrait_Pal:: @ 0x39B5AC
	.incbin "graphics/mon_portraits/medicham_portrait.gbapal"

gElectrikePortrait_Pal:: @ 0x39B5CC
	.incbin "graphics/mon_portraits/electrike_portrait.gbapal"

gManectricPortrait_Pal:: @ 0x39B5EC
	.incbin "graphics/mon_portraits/manectric_portrait.gbapal"

gPluslePortrait_Pal:: @ 0x39B60C
	.incbin "graphics/mon_portraits/plusle_portrait.gbapal"

gMinunPortrait_Pal:: @ 0x39B62C
	.incbin "graphics/mon_portraits/minun_portrait.gbapal"

gMagnemitePortrait_Pal:: @ 0x39B64C
	.incbin "graphics/mon_portraits/magnemite_portrait.gbapal"

gMagnetonPortrait_Pal:: @ 0x39B66C
	.incbin "graphics/mon_portraits/magneton_portrait.gbapal"

gVoltorbPortrait_Pal:: @ 0x39B68C
	.incbin "graphics/mon_portraits/voltorb_portrait.gbapal"

gElectrodePortrait_Pal:: @ 0x39B6AC
	.incbin "graphics/mon_portraits/electrode_portrait.gbapal"

gVolbeatPortrait_Pal:: @ 0x39B6CC
	.incbin "graphics/mon_portraits/volbeat_portrait.gbapal"

gIllumisePortrait_Pal:: @ 0x39B6EC
	.incbin "graphics/mon_portraits/illumise_portrait.gbapal"

gOddishPortrait_Pal:: @ 0x39B70C
	.incbin "graphics/mon_portraits/oddish_portrait.gbapal"

gGloomPortrait_Pal:: @ 0x39B72C
	.incbin "graphics/mon_portraits/gloom_portrait.gbapal"

gVileplumePortrait_Pal:: @ 0x39B74C
	.incbin "graphics/mon_portraits/vileplume_portrait.gbapal"

gSilhouettePortrait_Pal_Copy4:: @ 0x39B76C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gBellossomPortrait_Pal:: @ 0x39B78C
	.incbin "graphics/mon_portraits/bellossom_portrait.gbapal"

gDoduoPortrait_Pal:: @ 0x39B7AC
	.incbin "graphics/mon_portraits/doduo_portrait.gbapal"

gDodrioPortrait_Pal:: @ 0x39B7CC
	.incbin "graphics/mon_portraits/dodrio_portrait.gbapal"

gRoseliaPortrait_Pal:: @ 0x39B7EC
	.incbin "graphics/mon_portraits/roselia_portrait.gbapal"

gGulpinPortrait_Pal:: @ 0x39B80C
	.incbin "graphics/mon_portraits/gulpin_portrait.gbapal"

gSwalotPortrait_Pal:: @ 0x39B82C
	.incbin "graphics/mon_portraits/swalot_portrait.gbapal"

gCarvanhaPortrait_Pal:: @ 0x39B84C
	.incbin "graphics/mon_portraits/carvanha_portrait.gbapal"

gSharpedoPortrait_Pal:: @ 0x39B86C
	.incbin "graphics/mon_portraits/sharpedo_portrait.gbapal"

gWailmerPortrait_Pal:: @ 0x39B88C
	.incbin "graphics/mon_portraits/wailmer_portrait.gbapal"

gWailordPortrait_Pal:: @ 0x39B8AC
	.incbin "graphics/mon_portraits/wailord_portrait.gbapal"

gNumelPortrait_Pal:: @ 0x39B8CC
	.incbin "graphics/mon_portraits/numel_portrait.gbapal"

gCameruptPortrait_Pal:: @ 0x39B8EC
	.incbin "graphics/mon_portraits/camerupt_portrait.gbapal"

gSlugmaPortrait_Pal:: @ 0x39B90C
	.incbin "graphics/mon_portraits/slugma_portrait.gbapal"

gMagcargoPortrait_Pal:: @ 0x39B92C
	.incbin "graphics/mon_portraits/magcargo_portrait.gbapal"

gTorkoalPortrait_Pal:: @ 0x39B94C
	.incbin "graphics/mon_portraits/torkoal_portrait.gbapal"

gSilhouettePortrait_Pal_Copy5:: @ 0x39B96C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gGrimerPortrait_Pal:: @ 0x39B98C
	.incbin "graphics/mon_portraits/grimer_portrait.gbapal"

gMukPortrait_Pal:: @ 0x39B9AC
	.incbin "graphics/mon_portraits/muk_portrait.gbapal"

gKoffingPortrait_Pal:: @ 0x39B9CC
	.incbin "graphics/mon_portraits/koffing_portrait.gbapal"

gWeezingPortrait_Pal:: @ 0x39B9EC
	.incbin "graphics/mon_portraits/weezing_portrait.gbapal"

gSpoinkPortrait_Pal:: @ 0x39BA0C
	.incbin "graphics/mon_portraits/spoink_portrait.gbapal"

gGrumpigPortrait_Pal:: @ 0x39BA2C
	.incbin "graphics/mon_portraits/grumpig_portrait.gbapal"

gSandshrewPortrait_Pal:: @ 0x39BA4C
	.incbin "graphics/mon_portraits/sandshrew_portrait.gbapal"

gSandslashPortrait_Pal:: @ 0x39BA6C
	.incbin "graphics/mon_portraits/sandslash_portrait.gbapal"

gSpindaPortrait_Pal:: @ 0x39BA8C
	.incbin "graphics/mon_portraits/spinda_portrait.gbapal"

gSkarmoryPortrait_Pal:: @ 0x39BAAC
	.incbin "graphics/mon_portraits/skarmory_portrait.gbapal"

gTrapinchPortrait_Pal:: @ 0x39BACC
	.incbin "graphics/mon_portraits/trapinch_portrait.gbapal"

gVibravaPortrait_Pal:: @ 0x39BAEC
	.incbin "graphics/mon_portraits/vibrava_portrait.gbapal"

gFlygonPortrait_Pal:: @ 0x39BB0C
	.incbin "graphics/mon_portraits/flygon_portrait.gbapal"

gCacneaPortrait_Pal:: @ 0x39BB2C
	.incbin "graphics/mon_portraits/cacnea_portrait.gbapal"

gCacturnePortrait_Pal:: @ 0x39BB4C
	.incbin "graphics/mon_portraits/cacturne_portrait.gbapal"

gSilhouettePortrait_Pal_Copy6:: @ 0x39BB6C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gSwabluPortrait_Pal:: @ 0x39BB8C
	.incbin "graphics/mon_portraits/swablu_portrait.gbapal"

gAltariaPortrait_Pal:: @ 0x39BBAC
	.incbin "graphics/mon_portraits/altaria_portrait.gbapal"

gZangoosePortrait_Pal:: @ 0x39BBCC
	.incbin "graphics/mon_portraits/zangoose_portrait.gbapal"

gSeviperPortrait_Pal:: @ 0x39BBEC
	.incbin "graphics/mon_portraits/seviper_portrait.gbapal"

gLunatonePortrait_Pal:: @ 0x39BC0C
	.incbin "graphics/mon_portraits/lunatone_portrait.gbapal"

gSolrockPortrait_Pal:: @ 0x39BC2C
	.incbin "graphics/mon_portraits/solrock_portrait.gbapal"

gBarboachPortrait_Pal:: @ 0x39BC4C
	.incbin "graphics/mon_portraits/barboach_portrait.gbapal"

gWhiscashPortrait_Pal:: @ 0x39BC6C
	.incbin "graphics/mon_portraits/whiscash_portrait.gbapal"

gCorphishPortrait_Pal:: @ 0x39BC8C
	.incbin "graphics/mon_portraits/corphish_portrait.gbapal"

gCrawdauntPortrait_Pal:: @ 0x39BCAC
	.incbin "graphics/mon_portraits/crawdaunt_portrait.gbapal"

gBaltoyPortrait_Pal:: @ 0x39BCCC
	.incbin "graphics/mon_portraits/baltoy_portrait.gbapal"

gClaydolPortrait_Pal:: @ 0x39BCEC
	.incbin "graphics/mon_portraits/claydol_portrait.gbapal"

gLileepPortrait_Pal:: @ 0x39BD0C
	.incbin "graphics/mon_portraits/lileep_portrait.gbapal"

gCradilyPortrait_Pal:: @ 0x39BD2C
	.incbin "graphics/mon_portraits/cradily_portrait.gbapal"

gAnorithPortrait_Pal:: @ 0x39BD4C
	.incbin "graphics/mon_portraits/anorith_portrait.gbapal"

gSilhouettePortrait_Pal_Copy7:: @ 0x39BD6C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gArmaldoPortrait_Pal:: @ 0x39BD8C
	.incbin "graphics/mon_portraits/armaldo_portrait.gbapal"

gIgglybuffPortrait_Pal:: @ 0x39BDAC
	.incbin "graphics/mon_portraits/igglybuff_portrait.gbapal"

gJigglypuffPortrait_Pal:: @ 0x39BDCC
	.incbin "graphics/mon_portraits/jigglypuff_portrait.gbapal"

gWigglytuffPortrait_Pal:: @ 0x39BDEC
	.incbin "graphics/mon_portraits/wigglytuff_portrait.gbapal"

gFeebasPortrait_Pal:: @ 0x39BE0C
	.incbin "graphics/mon_portraits/feebas_portrait.gbapal"

gMiloticPortrait_Pal:: @ 0x39BE2C
	.incbin "graphics/mon_portraits/milotic_portrait.gbapal"

gCastformPortrait_Pal:: @ 0x39BE4C
	.incbin "graphics/mon_portraits/castform_portrait.gbapal"

gStaryuPortrait_Pal:: @ 0x39BE6C
	.incbin "graphics/mon_portraits/staryu_portrait.gbapal"

gStarmiePortrait_Pal:: @ 0x39BE8C
	.incbin "graphics/mon_portraits/starmie_portrait.gbapal"

gKecleonPortrait_Pal:: @ 0x39BEAC
	.incbin "graphics/mon_portraits/kecleon_portrait.gbapal"

gShuppetPortrait_Pal:: @ 0x39BECC
	.incbin "graphics/mon_portraits/shuppet_portrait.gbapal"

gBanettePortrait_Pal:: @ 0x39BEEC
	.incbin "graphics/mon_portraits/banette_portrait.gbapal"

gDuskullPortrait_Pal:: @ 0x39BF0C
	.incbin "graphics/mon_portraits/duskull_portrait.gbapal"

gDusclopsPortrait_Pal:: @ 0x39BF2C
	.incbin "graphics/mon_portraits/dusclops_portrait.gbapal"

gTropiusPortrait_Pal:: @ 0x39BF4C
	.incbin "graphics/mon_portraits/tropius_portrait.gbapal"

gSilhouettePortrait_Pal_Copy8:: @ 0x39BF6C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gChimechoPortrait_Pal:: @ 0x39BF8C
	.incbin "graphics/mon_portraits/chimecho_portrait.gbapal"

gAbsolPortrait_Pal:: @ 0x39BFAC
	.incbin "graphics/mon_portraits/absol_portrait.gbapal"

gVulpixPortrait_Pal:: @ 0x39BFCC
	.incbin "graphics/mon_portraits/vulpix_portrait.gbapal"

gNinetalesPortrait_Pal:: @ 0x39BFEC
	.incbin "graphics/mon_portraits/ninetales_portrait.gbapal"

gPichuPortrait_Pal:: @ 0x39C00C
	.incbin "graphics/mon_portraits/pichu_portrait.gbapal"

gPikachuPortrait_Pal:: @ 0x39C02C
	.incbin "graphics/mon_portraits/pikachu_portrait.gbapal"

gRaichuPortrait_Pal:: @ 0x39C04C
	.incbin "graphics/mon_portraits/raichu_portrait.gbapal"

gPsyduckPortrait_Pal:: @ 0x39C06C
	.incbin "graphics/mon_portraits/psyduck_portrait.gbapal"

gGolduckPortrait_Pal:: @ 0x39C08C
	.incbin "graphics/mon_portraits/golduck_portrait.gbapal"

gWynautPortrait_Pal:: @ 0x39C0AC
	.incbin "graphics/mon_portraits/wynaut_portrait.gbapal"

gWobbuffetPortrait_Pal:: @ 0x39C0CC
	.incbin "graphics/mon_portraits/wobbuffet_portrait.gbapal"

gNatuPortrait_Pal:: @ 0x39C0EC
	.incbin "graphics/mon_portraits/natu_portrait.gbapal"

gXatuPortrait_Pal:: @ 0x39C10C
	.incbin "graphics/mon_portraits/xatu_portrait.gbapal"

gGirafarigPortrait_Pal:: @ 0x39C12C
	.incbin "graphics/mon_portraits/girafarig_portrait.gbapal"

gPhanpyPortrait_Pal:: @ 0x39C14C
	.incbin "graphics/mon_portraits/phanpy_portrait.gbapal"

gSilhouettePortrait_Pal_Copy9:: @ 0x39C16C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gDonphanPortrait_Pal:: @ 0x39C18C
	.incbin "graphics/mon_portraits/donphan_portrait.gbapal"

gPinsirPortrait_Pal:: @ 0x39C1AC
	.incbin "graphics/mon_portraits/pinsir_portrait.gbapal"

gHeracrossPortrait_Pal:: @ 0x39C1CC
	.incbin "graphics/mon_portraits/heracross_portrait.gbapal"

gRhyhornPortrait_Pal:: @ 0x39C1EC
	.incbin "graphics/mon_portraits/rhyhorn_portrait.gbapal"

gRhydonPortrait_Pal:: @ 0x39C20C
	.incbin "graphics/mon_portraits/rhydon_portrait.gbapal"

gSnoruntPortrait_Pal:: @ 0x39C22C
	.incbin "graphics/mon_portraits/snorunt_portrait.gbapal"

gGlaliePortrait_Pal:: @ 0x39C24C
	.incbin "graphics/mon_portraits/glalie_portrait.gbapal"

gSphealPortrait_Pal:: @ 0x39C26C
	.incbin "graphics/mon_portraits/spheal_portrait.gbapal"

gSealeoPortrait_Pal:: @ 0x39C28C
	.incbin "graphics/mon_portraits/sealeo_portrait.gbapal"

gWalreinPortrait_Pal:: @ 0x39C2AC
	.incbin "graphics/mon_portraits/walrein_portrait.gbapal"

gClamperlPortrait_Pal:: @ 0x39C2CC
	.incbin "graphics/mon_portraits/clamperl_portrait.gbapal"

gHuntailPortrait_Pal:: @ 0x39C2EC
	.incbin "graphics/mon_portraits/huntail_portrait.gbapal"

gGorebyssPortrait_Pal:: @ 0x39C30C
	.incbin "graphics/mon_portraits/gorebyss_portrait.gbapal"

gRelicanthPortrait_Pal:: @ 0x39C32C
	.incbin "graphics/mon_portraits/relicanth_portrait.gbapal"

gCorsolaPortrait_Pal:: @ 0x39C34C
	.incbin "graphics/mon_portraits/corsola_portrait.gbapal"

gSilhouettePortrait_Pal_Copy10:: @ 0x39C36C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gChinchouPortrait_Pal:: @ 0x39C38C
	.incbin "graphics/mon_portraits/chinchou_portrait.gbapal"

gLanturnPortrait_Pal:: @ 0x39C3AC
	.incbin "graphics/mon_portraits/lanturn_portrait.gbapal"

gLuvdiscPortrait_Pal:: @ 0x39C3CC
	.incbin "graphics/mon_portraits/luvdisc_portrait.gbapal"

gHorseaPortrait_Pal:: @ 0x39C3EC
	.incbin "graphics/mon_portraits/horsea_portrait.gbapal"

gSeadraPortrait_Pal:: @ 0x39C40C
	.incbin "graphics/mon_portraits/seadra_portrait.gbapal"

gKingdraPortrait_Pal:: @ 0x39C42C
	.incbin "graphics/mon_portraits/kingdra_portrait.gbapal"

gBagonPortrait_Pal:: @ 0x39C44C
	.incbin "graphics/mon_portraits/bagon_portrait.gbapal"

gShelgonPortrait_Pal:: @ 0x39C46C
	.incbin "graphics/mon_portraits/shelgon_portrait.gbapal"

gSalamencePortrait_Pal:: @ 0x39C48C
	.incbin "graphics/mon_portraits/salamence_portrait.gbapal"

gBeldumPortrait_Pal:: @ 0x39C4AC
	.incbin "graphics/mon_portraits/beldum_portrait.gbapal"

gMetangPortrait_Pal:: @ 0x39C4CC
	.incbin "graphics/mon_portraits/metang_portrait.gbapal"

gMetagrossPortrait_Pal:: @ 0x39C4EC
	.incbin "graphics/mon_portraits/metagross_portrait.gbapal"

gRegirockPortrait_Pal:: @ 0x39C50C
	.incbin "graphics/mon_portraits/regirock_portrait.gbapal"

gRegicePortrait_Pal:: @ 0x39C52C
	.incbin "graphics/mon_portraits/regice_portrait.gbapal"

gRegisteelPortrait_Pal:: @ 0x39C54C
	.incbin "graphics/mon_portraits/registeel_portrait.gbapal"

gSilhouettePortrait_Pal_Copy11:: @ 0x39C56C
	.incbin "graphics/mon_portraits/silhouette.gbapal"

gLatiasPortrait_Pal:: @ 0x39C58C
	.incbin "graphics/mon_portraits/latias_portrait.gbapal"

gLatiosPortrait_Pal:: @ 0x39C5AC
	.incbin "graphics/mon_portraits/latios_portrait.gbapal"

gKyogrePortrait_Pal:: @ 0x39C5CC
	.incbin "graphics/mon_portraits/kyogre_portrait.gbapal"

gGroudonPortrait_Pal:: @ 0x39C5EC
	.incbin "graphics/mon_portraits/groudon_portrait.gbapal"

gRayquazaPortrait_Pal:: @ 0x39C60C
	.incbin "graphics/mon_portraits/rayquaza_portrait.gbapal"

gJirachiPortrait_Pal:: @ 0x39C62C
	.incbin "graphics/mon_portraits/jirachi_portrait.gbapal"

gChikoritaPortrait_Pal:: @ 0x39C64C
	.incbin "graphics/mon_portraits/chikorita_portrait.gbapal"

gCyndaquilPortrait_Pal:: @ 0x39C66C
	.incbin "graphics/mon_portraits/cyndaquil_portrait.gbapal"

gTotodilePortrait_Pal:: @ 0x39C68C
	.incbin "graphics/mon_portraits/totodile_portrait.gbapal"

gAerodactylPortrait_Pal:: @ 0x39C6AC
	.incbin "graphics/mon_portraits/aerodactyl_portrait.gbapal"

gQuestionMarkPortrait_Pal:: @ 0x39C6CC
	.incbin "graphics/mon_portraits/question_mark_portrait.gbapal"

gPlaceholder207Portrait_Pal:: @ 0x39C6EC
	.incbin "graphics/mon_portraits/207_portrait.gbapal"

gPlaceholder208Portrait_Pal:: @ 0x39C70C
	.incbin "graphics/mon_portraits/208_portrait.gbapal"

gPlaceholder209Portrait_Pal:: @ 0x39C72C
	.incbin "graphics/mon_portraits/209_portrait.gbapal"

gPlaceholder210Portrait_Pal:: @ 0x39C74C
	.incbin "graphics/mon_portraits/210_portrait.gbapal"

gSilhouettePortrait_Pal_Copy12:: @ 0x39C76C
	.incbin "graphics/mon_portraits/silhouette.gbapal"
