gMonHatchSpriteGroup0_Pals:: @ 0x1444F4
	.incbin "graphics/mon_hatch_sprites/wurmple_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/lotad_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/seedot_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/ralts_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/surskit_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/shroomish_hatch.gbapal"

	.incbin "baserom.gba", 0x1445B4, 0x1446F4 - 0x1445B4

gMonHatchSpriteGroup1_Pals:: @ 0x1446F4
	.incbin "graphics/mon_hatch_sprites/whismur_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/azurill_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/skitty_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/zubat_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/aron_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/plusle_hatch.gbapal"

	.incbin "baserom.gba", 0x1447B4, 0x1448F4 - 0x1447B4

gMonHatchSpriteGroup2_Pals:: @ 0x1448F4
	.incbin "graphics/mon_hatch_sprites/minun_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/oddish_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/gulpin_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/spoink_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/sandshrew_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/spinda_hatch.gbapal"

	.incbin "baserom.gba", 0x1449B4, 0x144AF4 - 0x1449B4

gMonHatchSpriteGroup3_Pals:: @ 0x144AF4
	.incbin "graphics/mon_hatch_sprites/trapinch_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/igglybuff_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/shuppet_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/chimecho_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/pichu_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/wynaut_hatch.gbapal"

	.incbin "baserom.gba", 0x144BB4, 0x144CF4 - 0x144BB4

gMonHatchSpriteGroup4_Pals:: @ 0x144CF4
	.incbin "graphics/mon_hatch_sprites/natu_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/phanpy_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/snorunt_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/spheal_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/corsola_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/chinchou_hatch.gbapal"

	.incbin "baserom.gba", 0x144DB4, 0x144EF4 - 0x144DB4

gMonHatchSpriteGroup5_Pals:: @ 0x144EF4
	.incbin "graphics/mon_hatch_sprites/horsea_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/bagon_hatch.gbapal"
	.incbin "graphics/mon_hatch_sprites/pichu_2_hatch.gbapal"

	.incbin "baserom.gba", 0x144F54, 0x1450F4 - 0x144F54
