gTreeckoPortrait_Gfx:: @ 0x084C596C
	.incbin "graphics/mon_portraits/treecko_portrait.4bpp"

gGrovylePortrait_Gfx:: @ 0x084C5C6C
	.incbin "graphics/mon_portraits/grovyle_portrait.4bpp"

gSceptilePortrait_Gfx:: @ 0x084C5F6C
	.incbin "graphics/mon_portraits/sceptile_portrait.4bpp"

gTorchicPortrait_Gfx:: @ 0x084C626C
	.incbin "graphics/mon_portraits/torchic_portrait.4bpp"

gCombuskenPortrait_Gfx:: @ 0x084C656C
	.incbin "graphics/mon_portraits/combusken_portrait.4bpp"

gBlazikenPortrait_Gfx:: @ 0x084C686C
	.incbin "graphics/mon_portraits/blaziken_portrait.4bpp"

gMudkipPortrait_Gfx:: @ 0x084C6B6C
	.incbin "graphics/mon_portraits/mudkip_portrait.4bpp"

gMarshtompPortrait_Gfx:: @ 0x084C6E6C
	.incbin "graphics/mon_portraits/marshtomp_portrait.4bpp"

gSwampertPortrait_Gfx:: @ 0x084C716C
	.incbin "graphics/mon_portraits/swampert_portrait.4bpp"

gPoochyenaPortrait_Gfx:: @ 0x084C746C
	.incbin "graphics/mon_portraits/poochyena_portrait.4bpp"

gMightyenaPortrait_Gfx:: @ 0x084C776C
	.incbin "graphics/mon_portraits/mightyena_portrait.4bpp"

gZigzagoonPortrait_Gfx:: @ 0x084C7A6C
	.incbin "graphics/mon_portraits/zigzagoon_portrait.4bpp"

gLinoonePortrait_Gfx:: @ 0x084C7D6C
	.incbin "graphics/mon_portraits/linoone_portrait.4bpp"

gWurmplePortrait_Gfx:: @ 0x084C806C
	.incbin "graphics/mon_portraits/wurmple_portrait.4bpp"

gSilcoonPortrait_Gfx:: @ 0x084C836C
	.incbin "graphics/mon_portraits/silcoon_portrait.4bpp"

gBeautiflyPortrait_Gfx:: @ 0x084C866C
	.incbin "graphics/mon_portraits/beautifly_portrait.4bpp"

gCascoonPortrait_Gfx:: @ 0x084C896C
	.incbin "graphics/mon_portraits/cascoon_portrait.4bpp"

gDustoxPortrait_Gfx:: @ 0x084C8C6C
	.incbin "graphics/mon_portraits/dustox_portrait.4bpp"

gLotadPortrait_Gfx:: @ 0x084C8F6C
	.incbin "graphics/mon_portraits/lotad_portrait.4bpp"

gLombrePortrait_Gfx:: @ 0x084C926C
	.incbin "graphics/mon_portraits/lombre_portrait.4bpp"

gLudicoloPortrait_Gfx:: @ 0x084C956C
	.incbin "graphics/mon_portraits/ludicolo_portrait.4bpp"

gSeedotPortrait_Gfx:: @ 0x084C986C
	.incbin "graphics/mon_portraits/seedot_portrait.4bpp"

gNuzleafPortrait_Gfx:: @ 0x084C9B6C
	.incbin "graphics/mon_portraits/nuzleaf_portrait.4bpp"

gShiftryPortrait_Gfx:: @ 0x084C9E6C
	.incbin "graphics/mon_portraits/shiftry_portrait.4bpp"

gTaillowPortrait_Gfx:: @ 0x084CA16C
	.incbin "graphics/mon_portraits/taillow_portrait.4bpp"

gSwellowPortrait_Gfx:: @ 0x084CA46C
	.incbin "graphics/mon_portraits/swellow_portrait.4bpp"

gWingullPortrait_Gfx:: @ 0x084CA76C
	.incbin "graphics/mon_portraits/wingull_portrait.4bpp"

gPelilpperPortrait_Gfx:: @ 0x084CAA6C
	.incbin "graphics/mon_portraits/pelilpper_portrait.4bpp"

gRaltsPortrait_Gfx:: @ 0x084CAD6C
	.incbin "graphics/mon_portraits/ralts_portrait.4bpp"

gKirliaPortrait_Gfx:: @ 0x084CB06C
	.incbin "graphics/mon_portraits/kirlia_portrait.4bpp"

gGardevoirPortrait_Gfx:: @ 0x084CB36C
	.incbin "graphics/mon_portraits/gardevoir_portrait.4bpp"

gSurskitPortrait_Gfx:: @ 0x084CB66C
	.incbin "graphics/mon_portraits/surskit_portrait.4bpp"

gMasquerainPortrait_Gfx:: @ 0x084CB96C
	.incbin "graphics/mon_portraits/masquerain_portrait.4bpp"

gShroomishPortrait_Gfx:: @ 0x084CBC6C
	.incbin "graphics/mon_portraits/shroomish_portrait.4bpp"

gBreloomPortrait_Gfx:: @ 0x084CBF6C
	.incbin "graphics/mon_portraits/breloom_portrait.4bpp"

gSlakothPortrait_Gfx:: @ 0x084CC26C
	.incbin "graphics/mon_portraits/slakoth_portrait.4bpp"

gVigorothPortrait_Gfx:: @ 0x084CC56C
	.incbin "graphics/mon_portraits/vigoroth_portrait.4bpp"

gSlakingPortrait_Gfx:: @ 0x084CC86C
	.incbin "graphics/mon_portraits/slaking_portrait.4bpp"

gAbraPortrait_Gfx:: @ 0x084CCB6C
	.incbin "graphics/mon_portraits/abra_portrait.4bpp"

gKadabraPortrait_Gfx:: @ 0x084CCE6C
	.incbin "graphics/mon_portraits/kadabra_portrait.4bpp"

gAlakazamPortrait_Gfx:: @ 0x084CD16C
	.incbin "graphics/mon_portraits/alakazam_portrait.4bpp"

gNincadaPortrait_Gfx:: @ 0x084CD46C
	.incbin "graphics/mon_portraits/nincada_portrait.4bpp"

gNinjaskPortrait_Gfx:: @ 0x084CD76C
	.incbin "graphics/mon_portraits/ninjask_portrait.4bpp"

gShedinjaPortrait_Gfx:: @ 0x084CDA6C
	.incbin "graphics/mon_portraits/shedinja_portrait.4bpp"

gWhismurPortrait_Gfx:: @ 0x084CDD6C
	.incbin "graphics/mon_portraits/whismur_portrait.4bpp"

gLoudredPortrait_Gfx:: @ 0x084CE06C
	.incbin "graphics/mon_portraits/loudred_portrait.4bpp"

gExploudPortrait_Gfx:: @ 0x084CE36C
	.incbin "graphics/mon_portraits/exploud_portrait.4bpp"

gMakuhitaPortrait_Gfx:: @ 0x084CE66C
	.incbin "graphics/mon_portraits/makuhita_portrait.4bpp"

gHariyamaPortrait_Gfx:: @ 0x084CE96C
	.incbin "graphics/mon_portraits/hariyama_portrait.4bpp"

gGoldeenPortrait_Gfx:: @ 0x084CEC6C
	.incbin "graphics/mon_portraits/goldeen_portrait.4bpp"

gSeakingPortrait_Gfx:: @ 0x084CEF6C
	.incbin "graphics/mon_portraits/seaking_portrait.4bpp"

gMagikarpPortrait_Gfx:: @ 0x084CF26C
	.incbin "graphics/mon_portraits/magikarp_portrait.4bpp"

gGyaradosPortrait_Gfx:: @ 0x084CF56C
	.incbin "graphics/mon_portraits/gyarados_portrait.4bpp"

gAzurillPortrait_Gfx:: @ 0x084CF86C
	.incbin "graphics/mon_portraits/azurill_portrait.4bpp"

gMarillPortrait_Gfx:: @ 0x084CFB6C
	.incbin "graphics/mon_portraits/marill_portrait.4bpp"

gAzumarillPortrait_Gfx:: @ 0x084CFE6C
	.incbin "graphics/mon_portraits/azumarill_portrait.4bpp"

gGeodudePortrait_Gfx:: @ 0x084D016C
	.incbin "graphics/mon_portraits/geodude_portrait.4bpp"

gGravelerPortrait_Gfx:: @ 0x084D046C
	.incbin "graphics/mon_portraits/graveler_portrait.4bpp"

gGolemPortrait_Gfx:: @ 0x084D076C
	.incbin "graphics/mon_portraits/golem_portrait.4bpp"

gNosepassPortrait_Gfx:: @ 0x084D0A6C
	.incbin "graphics/mon_portraits/nosepass_portrait.4bpp"

gSkittyPortrait_Gfx:: @ 0x084D0D6C
	.incbin "graphics/mon_portraits/skitty_portrait.4bpp"

gDelcattyPortrait_Gfx:: @ 0x084D106C
	.incbin "graphics/mon_portraits/delcatty_portrait.4bpp"

gZubatPortrait_Gfx:: @ 0x084D136C
	.incbin "graphics/mon_portraits/zubat_portrait.4bpp"

gGolbatPortrait_Gfx:: @ 0x084D166C
	.incbin "graphics/mon_portraits/golbat_portrait.4bpp"

gCrobatPortrait_Gfx:: @ 0x084D196C
	.incbin "graphics/mon_portraits/crobat_portrait.4bpp"

gTentacoolPortrait_Gfx:: @ 0x084D1C6C
	.incbin "graphics/mon_portraits/tentacool_portrait.4bpp"

gTentacruelPortrait_Gfx:: @ 0x084D1F6C
	.incbin "graphics/mon_portraits/tentacruel_portrait.4bpp"

gSableyePortrait_Gfx:: @ 0x084D226C
	.incbin "graphics/mon_portraits/sableye_portrait.4bpp"

gMawilePortrait_Gfx:: @ 0x084D256C
	.incbin "graphics/mon_portraits/mawile_portrait.4bpp"

gAronPortrait_Gfx:: @ 0x084D286C
	.incbin "graphics/mon_portraits/aron_portrait.4bpp"

gLaironPortrait_Gfx:: @ 0x084D2B6C
	.incbin "graphics/mon_portraits/lairon_portrait.4bpp"

gAggronPortrait_Gfx:: @ 0x084D2E6C
	.incbin "graphics/mon_portraits/aggron_portrait.4bpp"

gMachopPortrait_Gfx:: @ 0x084D316C
	.incbin "graphics/mon_portraits/machop_portrait.4bpp"

gMachokePortrait_Gfx:: @ 0x084D346C
	.incbin "graphics/mon_portraits/machoke_portrait.4bpp"

gMachampPortrait_Gfx:: @ 0x084D376C
	.incbin "graphics/mon_portraits/machamp_portrait.4bpp"

gMedititePortrait_Gfx:: @ 0x084D3A6C
	.incbin "graphics/mon_portraits/meditite_portrait.4bpp"

gMedichamPortrait_Gfx:: @ 0x084D3D6C
	.incbin "graphics/mon_portraits/medicham_portrait.4bpp"

gElectrikePortrait_Gfx:: @ 0x084D406C
	.incbin "graphics/mon_portraits/electrike_portrait.4bpp"

gManectricPortrait_Gfx:: @ 0x084D436C
	.incbin "graphics/mon_portraits/manectric_portrait.4bpp"

gPluslePortrait_Gfx:: @ 0x084D466C
	.incbin "graphics/mon_portraits/plusle_portrait.4bpp"

gMinunPortrait_Gfx:: @ 0x084D496C
	.incbin "graphics/mon_portraits/minun_portrait.4bpp"

gMagnemitePortrait_Gfx:: @ 0x084D4C6C
	.incbin "graphics/mon_portraits/magnemite_portrait.4bpp"

gMagnetonPortrait_Gfx:: @ 0x084D4F6C
	.incbin "graphics/mon_portraits/magneton_portrait.4bpp"

gVoltorbPortrait_Gfx:: @ 0x084D526C
	.incbin "graphics/mon_portraits/voltorb_portrait.4bpp"

gElectrodePortrait_Gfx:: @ 0x084D556C
	.incbin "graphics/mon_portraits/electrode_portrait.4bpp"

gVolbeatPortrait_Gfx:: @ 0x084D586C
	.incbin "graphics/mon_portraits/volbeat_portrait.4bpp"

gIllumisePortrait_Gfx:: @ 0x084D5B6C
	.incbin "graphics/mon_portraits/illumise_portrait.4bpp"

gOddishPortrait_Gfx:: @ 0x084D5E6C
	.incbin "graphics/mon_portraits/oddish_portrait.4bpp"

gGloomPortrait_Gfx:: @ 0x084D616C
	.incbin "graphics/mon_portraits/gloom_portrait.4bpp"

gVileplumePortrait_Gfx:: @ 0x084D646C
	.incbin "graphics/mon_portraits/vileplume_portrait.4bpp"

gBellossomPortrait_Gfx:: @ 0x084D676C
	.incbin "graphics/mon_portraits/bellossom_portrait.4bpp"

gDoduoPortrait_Gfx:: @ 0x084D6A6C
	.incbin "graphics/mon_portraits/doduo_portrait.4bpp"

gDodrioPortrait_Gfx:: @ 0x084D6D6C
	.incbin "graphics/mon_portraits/dodrio_portrait.4bpp"

gRoseliaPortrait_Gfx:: @ 0x084D706C
	.incbin "graphics/mon_portraits/roselia_portrait.4bpp"

gGulpinPortrait_Gfx:: @ 0x084D736C
	.incbin "graphics/mon_portraits/gulpin_portrait.4bpp"

gSwalotPortrait_Gfx:: @ 0x084D766C
	.incbin "graphics/mon_portraits/swalot_portrait.4bpp"

gCarvanhaPortrait_Gfx:: @ 0x084D796C
	.incbin "graphics/mon_portraits/carvanha_portrait.4bpp"

gSharpedoPortrait_Gfx:: @ 0x084D7C6C
	.incbin "graphics/mon_portraits/sharpedo_portrait.4bpp"

gWailmerPortrait_Gfx:: @ 0x084D7F6C
	.incbin "graphics/mon_portraits/wailmer_portrait.4bpp"

gWailordPortrait_Gfx:: @ 0x084D826C
	.incbin "graphics/mon_portraits/wailord_portrait.4bpp"

gNumelPortrait_Gfx:: @ 0x084D856C
	.incbin "graphics/mon_portraits/numel_portrait.4bpp"

gCameruptPortrait_Gfx:: @ 0x084D886C
	.incbin "graphics/mon_portraits/camerupt_portrait.4bpp"

gSlugmaPortrait_Gfx:: @ 0x084D8B6C
	.incbin "graphics/mon_portraits/slugma_portrait.4bpp"

gMagcargoPortrait_Gfx:: @ 0x084D8E6C
	.incbin "graphics/mon_portraits/magcargo_portrait.4bpp"

gTorkoalPortrait_Gfx:: @ 0x084D916C
	.incbin "graphics/mon_portraits/torkoal_portrait.4bpp"

gGrimerPortrait_Gfx:: @ 0x084D946C
	.incbin "graphics/mon_portraits/grimer_portrait.4bpp"

gMukPortrait_Gfx:: @ 0x084D976C
	.incbin "graphics/mon_portraits/muk_portrait.4bpp"

gKoffingPortrait_Gfx:: @ 0x084D9A6C
	.incbin "graphics/mon_portraits/koffing_portrait.4bpp"

gWeezingPortrait_Gfx:: @ 0x084D9D6C
	.incbin "graphics/mon_portraits/weezing_portrait.4bpp"

gSpoinkPortrait_Gfx:: @ 0x084DA06C
	.incbin "graphics/mon_portraits/spoink_portrait.4bpp"

gGrumpigPortrait_Gfx:: @ 0x084DA36C
	.incbin "graphics/mon_portraits/grumpig_portrait.4bpp"

gSandshrewPortrait_Gfx:: @ 0x084DA66C
	.incbin "graphics/mon_portraits/sandshrew_portrait.4bpp"

gSandslashPortrait_Gfx:: @ 0x084DA96C
	.incbin "graphics/mon_portraits/sandslash_portrait.4bpp"

gSpindaPortrait_Gfx:: @ 0x084DAC6C
	.incbin "graphics/mon_portraits/spinda_portrait.4bpp"

gSkarmoryPortrait_Gfx:: @ 0x084DAF6C
	.incbin "graphics/mon_portraits/skarmory_portrait.4bpp"

gTrapinchPortrait_Gfx:: @ 0x084DB26C
	.incbin "graphics/mon_portraits/trapinch_portrait.4bpp"

gVibravaPortrait_Gfx:: @ 0x084DB56C
	.incbin "graphics/mon_portraits/vibrava_portrait.4bpp"

gFlygonPortrait_Gfx:: @ 0x084DB86C
	.incbin "graphics/mon_portraits/flygon_portrait.4bpp"

gCacneaPortrait_Gfx:: @ 0x084DBB6C
	.incbin "graphics/mon_portraits/cacnea_portrait.4bpp"

gCacturnePortrait_Gfx:: @ 0x084DBE6C
	.incbin "graphics/mon_portraits/cacturne_portrait.4bpp"

gSwabluPortrait_Gfx:: @ 0x084DC16C
	.incbin "graphics/mon_portraits/swablu_portrait.4bpp"

gAltariaPortrait_Gfx:: @ 0x084DC46C
	.incbin "graphics/mon_portraits/altaria_portrait.4bpp"

gZangoosePortrait_Gfx:: @ 0x084DC76C
	.incbin "graphics/mon_portraits/zangoose_portrait.4bpp"

gSeviperPortrait_Gfx:: @ 0x084DCA6C
	.incbin "graphics/mon_portraits/seviper_portrait.4bpp"

gLunatonePortrait_Gfx:: @ 0x084DCD6C
	.incbin "graphics/mon_portraits/lunatone_portrait.4bpp"

gSolrockPortrait_Gfx:: @ 0x084DD06C
	.incbin "graphics/mon_portraits/solrock_portrait.4bpp"

gBarboachPortrait_Gfx:: @ 0x084DD36C
	.incbin "graphics/mon_portraits/barboach_portrait.4bpp"

gWhiscashPortrait_Gfx:: @ 0x084DD66C
	.incbin "graphics/mon_portraits/whiscash_portrait.4bpp"

gCorphishPortrait_Gfx:: @ 0x084DD96C
	.incbin "graphics/mon_portraits/corphish_portrait.4bpp"

gCrawdauntPortrait_Gfx:: @ 0x084DDC6C
	.incbin "graphics/mon_portraits/crawdaunt_portrait.4bpp"

gBaltoyPortrait_Gfx:: @ 0x084DDF6C
	.incbin "graphics/mon_portraits/baltoy_portrait.4bpp"

gClaydolPortrait_Gfx:: @ 0x084DE26C
	.incbin "graphics/mon_portraits/claydol_portrait.4bpp"

gLileepPortrait_Gfx:: @ 0x084DE56C
	.incbin "graphics/mon_portraits/lileep_portrait.4bpp"

gCradilyPortrait_Gfx:: @ 0x084DE86C
	.incbin "graphics/mon_portraits/cradily_portrait.4bpp"

gAnorithPortrait_Gfx:: @ 0x084DEB6C
	.incbin "graphics/mon_portraits/anorith_portrait.4bpp"

gArmaldoPortrait_Gfx:: @ 0x084DEE6C
	.incbin "graphics/mon_portraits/armaldo_portrait.4bpp"

gIgglybuffPortrait_Gfx:: @ 0x084DF16C
	.incbin "graphics/mon_portraits/igglybuff_portrait.4bpp"

gJigglypuffPortrait_Gfx:: @ 0x084DF46C
	.incbin "graphics/mon_portraits/jigglypuff_portrait.4bpp"

gWigglytuffPortrait_Gfx:: @ 0x084DF76C
	.incbin "graphics/mon_portraits/wigglytuff_portrait.4bpp"

gFeebasPortrait_Gfx:: @ 0x084DFA6C
	.incbin "graphics/mon_portraits/feebas_portrait.4bpp"

gMiloticPortrait_Gfx:: @ 0x084DFD6C
	.incbin "graphics/mon_portraits/milotic_portrait.4bpp"

gCastformPortrait_Gfx:: @ 0x084E006C
	.incbin "graphics/mon_portraits/castform_portrait.4bpp"

gStaryuPortrait_Gfx:: @ 0x084E036C
	.incbin "graphics/mon_portraits/staryu_portrait.4bpp"

gStarmiePortrait_Gfx:: @ 0x084E066C
	.incbin "graphics/mon_portraits/starmie_portrait.4bpp"

gKecleonPortrait_Gfx:: @ 0x084E096C
	.incbin "graphics/mon_portraits/kecleon_portrait.4bpp"

gShuppetPortrait_Gfx:: @ 0x084E0C6C
	.incbin "graphics/mon_portraits/shuppet_portrait.4bpp"

gBanettePortrait_Gfx:: @ 0x084E0F6C
	.incbin "graphics/mon_portraits/banette_portrait.4bpp"

gDuskullPortrait_Gfx:: @ 0x084E126C
	.incbin "graphics/mon_portraits/duskull_portrait.4bpp"

gDusclopsPortrait_Gfx:: @ 0x084E156C
	.incbin "graphics/mon_portraits/dusclops_portrait.4bpp"

gTropiusPortrait_Gfx:: @ 0x084E186C
	.incbin "graphics/mon_portraits/tropius_portrait.4bpp"

gChimechoPortrait_Gfx:: @ 0x084E1B6C
	.incbin "graphics/mon_portraits/chimecho_portrait.4bpp"

gAbsolPortrait_Gfx:: @ 0x084E1E6C
	.incbin "graphics/mon_portraits/absol_portrait.4bpp"

gVulpixPortrait_Gfx:: @ 0x084E216C
	.incbin "graphics/mon_portraits/vulpix_portrait.4bpp"

gNinetalesPortrait_Gfx:: @ 0x084E246C
	.incbin "graphics/mon_portraits/ninetales_portrait.4bpp"

gPichuPortrait_Gfx:: @ 0x084E276C
	.incbin "graphics/mon_portraits/pichu_portrait.4bpp"

gPikachuPortrait_Gfx:: @ 0x084E2A6C
	.incbin "graphics/mon_portraits/pikachu_portrait.4bpp"

gRaichuPortrait_Gfx:: @ 0x084E2D6C
	.incbin "graphics/mon_portraits/raichu_portrait.4bpp"

gPsyduckPortrait_Gfx:: @ 0x084E306C
	.incbin "graphics/mon_portraits/psyduck_portrait.4bpp"

gGolduckPortrait_Gfx:: @ 0x084E336C
	.incbin "graphics/mon_portraits/golduck_portrait.4bpp"

gWynautPortrait_Gfx:: @ 0x084E366C
	.incbin "graphics/mon_portraits/wynaut_portrait.4bpp"

gWobbuffetPortrait_Gfx:: @ 0x084E396C
	.incbin "graphics/mon_portraits/wobbuffet_portrait.4bpp"

gNatuPortrait_Gfx:: @ 0x084E3C6C
	.incbin "graphics/mon_portraits/natu_portrait.4bpp"

gXatuPortrait_Gfx:: @ 0x084E3F6C
	.incbin "graphics/mon_portraits/xatu_portrait.4bpp"

gGirafarigPortrait_Gfx:: @ 0x084E426C
	.incbin "graphics/mon_portraits/girafarig_portrait.4bpp"

gPhanpyPortrait_Gfx:: @ 0x084E456C
	.incbin "graphics/mon_portraits/phanpy_portrait.4bpp"

gDonphanPortrait_Gfx:: @ 0x084E486C
	.incbin "graphics/mon_portraits/donphan_portrait.4bpp"

gPinsirPortrait_Gfx:: @ 0x084E4B6C
	.incbin "graphics/mon_portraits/pinsir_portrait.4bpp"

gHeracrossPortrait_Gfx:: @ 0x084E4E6C
	.incbin "graphics/mon_portraits/heracross_portrait.4bpp"

gRhyhornPortrait_Gfx:: @ 0x084E516C
	.incbin "graphics/mon_portraits/rhyhorn_portrait.4bpp"

gRhydonPortrait_Gfx:: @ 0x084E546C
	.incbin "graphics/mon_portraits/rhydon_portrait.4bpp"

gSnoruntPortrait_Gfx:: @ 0x084E576C
	.incbin "graphics/mon_portraits/snorunt_portrait.4bpp"

gGlaliePortrait_Gfx:: @ 0x084E5A6C
	.incbin "graphics/mon_portraits/glalie_portrait.4bpp"

gSphealPortrait_Gfx:: @ 0x084E5D6C
	.incbin "graphics/mon_portraits/spheal_portrait.4bpp"

gSealeoPortrait_Gfx:: @ 0x084E606C
	.incbin "graphics/mon_portraits/sealeo_portrait.4bpp"

gWalreinPortrait_Gfx:: @ 0x084E636C
	.incbin "graphics/mon_portraits/walrein_portrait.4bpp"

gClamperlPortrait_Gfx:: @ 0x084E666C
	.incbin "graphics/mon_portraits/clamperl_portrait.4bpp"

gHuntailPortrait_Gfx:: @ 0x084E696C
	.incbin "graphics/mon_portraits/huntail_portrait.4bpp"

gGorebyssPortrait_Gfx:: @ 0x084E6C6C
	.incbin "graphics/mon_portraits/gorebyss_portrait.4bpp"

gRelicanthPortrait_Gfx:: @ 0x084E6F6C
	.incbin "graphics/mon_portraits/relicanth_portrait.4bpp"

gCorsolaPortrait_Gfx:: @ 0x084E726C
	.incbin "graphics/mon_portraits/corsola_portrait.4bpp"

gChinchouPortrait_Gfx:: @ 0x084E756C
	.incbin "graphics/mon_portraits/chinchou_portrait.4bpp"

gLanturnPortrait_Gfx:: @ 0x084E786C
	.incbin "graphics/mon_portraits/lanturn_portrait.4bpp"

gLuvdiscPortrait_Gfx:: @ 0x084E7B6C
	.incbin "graphics/mon_portraits/luvdisc_portrait.4bpp"

gHorseaPortrait_Gfx:: @ 0x084E7E6C
	.incbin "graphics/mon_portraits/horsea_portrait.4bpp"

gSeadraPortrait_Gfx:: @ 0x084E816C
	.incbin "graphics/mon_portraits/seadra_portrait.4bpp"

gKingdraPortrait_Gfx:: @ 0x084E846C
	.incbin "graphics/mon_portraits/kingdra_portrait.4bpp"

gBagonPortrait_Gfx:: @ 0x084E876C
	.incbin "graphics/mon_portraits/bagon_portrait.4bpp"

gShelgonPortrait_Gfx:: @ 0x084E8A6C
	.incbin "graphics/mon_portraits/shelgon_portrait.4bpp"

gSalamencePortrait_Gfx:: @ 0x084E8D6C
	.incbin "graphics/mon_portraits/salamence_portrait.4bpp"

gBeldumPortrait_Gfx:: @ 0x084E906C
	.incbin "graphics/mon_portraits/beldum_portrait.4bpp"

gMetangPortrait_Gfx:: @ 0x084E936C
	.incbin "graphics/mon_portraits/metang_portrait.4bpp"

gMetagrossPortrait_Gfx:: @ 0x084E966C
	.incbin "graphics/mon_portraits/metagross_portrait.4bpp"

gRegirockPortrait_Gfx:: @ 0x084E996C
	.incbin "graphics/mon_portraits/regirock_portrait.4bpp"

gRegicePortrait_Gfx:: @ 0x084E9C6C
	.incbin "graphics/mon_portraits/regice_portrait.4bpp"

gRegisteelPortrait_Gfx:: @ 0x084E9F6C
	.incbin "graphics/mon_portraits/registeel_portrait.4bpp"

gLatiasPortrait_Gfx:: @ 0x084EA26C
	.incbin "graphics/mon_portraits/latias_portrait.4bpp"

gLatiosPortrait_Gfx:: @ 0x084EA56C
	.incbin "graphics/mon_portraits/latios_portrait.4bpp"

gKyogrePortrait_Gfx:: @ 0x084EA86C
	.incbin "graphics/mon_portraits/kyogre_portrait.4bpp"

gGroudonPortrait_Gfx:: @ 0x084EAB6C
	.incbin "graphics/mon_portraits/groudon_portrait.4bpp"

gRayquazaPortrait_Gfx:: @ 0x084EAE6C
	.incbin "graphics/mon_portraits/rayquaza_portrait.4bpp"

gJirachiPortrait_Gfx:: @ 0x084EB16C
	.incbin "graphics/mon_portraits/jirachi_portrait.4bpp"

gChikoritaPortrait_Gfx:: @ 0x084EB46C
	.incbin "graphics/mon_portraits/chikorita_portrait.4bpp"

gCyndaquilPortrait_Gfx:: @ 0x084EB76C
	.incbin "graphics/mon_portraits/cyndaquil_portrait.4bpp"

gTotodilePortrait_Gfx:: @ 0x084EBA6C
	.incbin "graphics/mon_portraits/totodile_portrait.4bpp"

gAerodactylPortrait_Gfx:: @ 0x084EBD6C
	.incbin "graphics/mon_portraits/aerodactyl_portrait.4bpp"

gQuestionMarkPortrait_Gfx:: @ 0x084EC06C
	.incbin "graphics/mon_portraits/question_mark_portrait.4bpp"

gPlaceholder207Portrait_Gfx:: @ 0x084EC36C
	.incbin "graphics/mon_portraits/207_portrait.4bpp"

gPlaceholder208Portrait_Gfx:: @ 0x084EC66C
	.incbin "graphics/mon_portraits/208_portrait.4bpp"

gPlaceholder209Portrait_Gfx:: @ 0x084EC96C
	.incbin "graphics/mon_portraits/209_portrait.4bpp"

gPlaceholder210Portrait_Gfx:: @ 0x084ECC6C
	.incbin "graphics/mon_portraits/210_portrait.4bpp"
