gTitlescreenBgTilemap:: @ 0x08120CC0
	.incbin "graphics/titlescreen/titlescreen_bg_tilemap.bin"

gTitlescreenBg_Pals:: @ 0x081214C0
	.incbin "graphics/titlescreen/titlescreen_bg.gbapal"

gTitlescreenBg_Gfx:: @ 0x081216C0
	.incbin "graphics/titlescreen/titlescreen_bg.8bpp"

gTitlescreenSpritesNoSavedGame_Gfx:: @ 0x081296c0
	.incbin "graphics/titlescreen/sprites_no_saved_game.4bpp"

gUnknown_081306C0:: @ 0x08081306C0
	.incbin "graphics/titlescreen/unknown_081306C0.bin"

gTitlescreenSpritesSavedGame_Gfx:: @ 0x081306E0
	.incbin "graphics/titlescreen/sprites_saved_game.4bpp"

gUnknown_081376E0:: @ 0x08081376E0
	.incbin "graphics/titlescreen/unknown_081376E0.bin"

gTitlescreenSprites_Pals:: @ 0x08137700
	.incbin "graphics/titlescreen/sprites.gbapal"
