gRubyTravelPaint_Gfx:: @ 0x081BCAA4
	.incbin "graphics/stage/ruby/travel_paint.4bpp"
	.space 0x120

gRubyPainter_Pals:: @ 0x081BE2C4
	.incbin "graphics/stage/ruby/painter.gbapal"

gSapphireTravelPaint_Gfx:: @ 0x081BE4C4
	.incbin "graphics/stage/sapphire/travel_paint.4bpp"
	.space 0x120

gSapphirePainter_Pals:: @ 0x081BFCE4
	.incbin "graphics/stage/sapphire/painter.gbapal"

gRubyBoard_Pals:: @ 0x081BFEE4
	.incbin "graphics/stage/ruby/ruby_board.gbapal"
