gDusclopsBoardPalette:: @ 0x082EDEE0
	.incbin "graphics/stage/dusclops/dusclops_board.gbapal"

gDusclopsAnimPalettes:: @ 0x082EE0E0
	.incbin "graphics/stage/dusclops/anim_frame_00.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_01.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_02.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_03.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_04.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_05.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_06.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_07.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_08.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_09.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_10.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_11.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_12.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_13.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_14.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_15.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_16.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_17.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_18.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_19.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_20.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_21.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_22.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_23.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_24.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_25.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_26.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_27.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_28.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_29.gbapal"
	.incbin "graphics/stage/dusclops/anim_frame_30.gbapal"

gDusclopsBoardBG0Tilemap:: @ 0x082EE4C0
	.incbin "graphics/stage/dusclops/dusclops_board_bg0_tilemap.bin"

gDusclopsBoardCollisionTileDataAllLayers:: @ 0x082EECC0
	.incbin "data/board_data/collision/dusclops/board_tiledata.bin"

gDusclopsBoardCollisionAngleDataAllLayers:: @ 0x082F0CC0
	.incbin "data/board_data/collision/dusclops/board_angledata.bin"

gDusclopsBoardCollisionTypeDataAllLayers:: @ 0x082FBE40
	.incbin "data/board_data/collision/dusclops/board_typedata.bin"

gDusclopsBoardBG1Tilemap:: @ 0x08301700
	.incbin "graphics/stage/dusclops/dusclops_board_bg1_tilemap.bin"

gDusclopsBoardBG2Tilemap:: @ 0x08301F00
	.incbin "graphics/stage/dusclops/dusclops_board_bg2_tilemap.bin"

gBonusFieldCompressedBaseTiles:: @ 0x08302700
	.incbin "graphics/stage/dusclops/bonus_field_base_tiles.4bpp.lz"

gDusclopsBoardCompressedBGTiles:: @ 0x08303928
	.incbin "graphics/stage/dusclops/dusclops_board_bg_tiles.4bpp.lz"

gDusclopsBodyCollisionMap:: @ 0x083071D4
	.incbin "data/board_data/collision/dusclops/dusclops_entity_collision_96x120.bin"
