gDusclopsBoardPalette:: @ 0x082EDEE0
	.incbin "baserom.gba", 0x2EDEE0, 0x200

gDusclopsAnimPalettes:: @ 0x082EE0E0
	.incbin "baserom.gba", 0x2EE0E0, 0x3E0

gDusclopsBoardBG0Tilemap:: @ 0x082EE4C0
	.incbin "baserom.gba", 0x2EE4C0, 0x800

gDusclopsBoardCollisionTileDataAllLayers:: @ 0x082EECC0
    .incbin "baserom.gba", 0x2EECC0, 0x2000

gDusclopsBoardCollisionAngleDataAllLayers:: @ 0x082F0CC0
    .incbin "baserom.gba", 0x2F0CC0, 0xB180

gDusclopsBoardCollisionTypeDataAllLayers:: @ 0x082FBE40
    .incbin "baserom.gba", 0x2FBE40, 0x58C0

gDusclopsBoardBG1Tilemap:: @ 0x08301700
	.incbin "baserom.gba", 0x301700, 0x800

gDusclopsBoardBG2Tilemap:: @ 0x08301F00
	.incbin "baserom.gba", 0x301F00, 0x800

gBonusFieldCompressedBaseTiles:: @ 0x08302700
	.incbin "baserom.gba", 0x302700, 0x1228

gDusclopsBoardCompressedBGTiles:: @ 0x08303928
	.incbin "baserom.gba", 0x303928, 0x38AC

gDusclopsBodyCollisionMap:: @ 0x083071D4
	.incbin "baserom.gba", 0x3071D4, 0x5A00
