gDusclopsBoardPalette:: @ 0x082EDEE0
	.incbin "graphics/stage/dusclops/dusclops_board.pal"

gDusclopsAnimPalettes:: @ 0x082EE0E0
	.incbin "graphics/stage/dusclops/dusclops_anim.pal"

gDusclopsBoardBG0Tilemap:: @ 0x082EE4C0
	.incbin "graphics/stage/dusclops/dusclops_board_bg0_tilemap.bin"

gDusclopsBoardCollisionTileDataAllLayers:: @ 0x082EECC0
	.incbin "data/board_data/collision/dusclops/board_tiledata.bin"

gDusclopsBoardCollisionAngleDataAllLayers:: @ 0x082F0CC0
	.incbin "data/board_data/collision/dusclops/board_angledata.bin"

gDusclopsBoardCollisionTypeDataAllLayers:: @ 0x082FBE40
	.incbin "data/board_data/collision/dusclops/board_typedata.bin"

gDusclopsBoardBG1Tilemap:: @ 0x08301700
	.incbin "graphics/stage/dusclops/dusclops_board_bg1_tilemap.bin"

gDusclopsBoardBG2Tilemap:: @ 0x08301F00
	.incbin "graphics/stage/dusclops/dusclops_board_bg2_tilemap.bin"

gBonusFieldCompressedBaseTiles:: @ 0x08302700
	.incbin "graphics/stage/dusclops/bonus_field_base_tiles.4bpp.lz"

gDusclopsBoardCompressedBGTiles:: @ 0x08303928
	.incbin "graphics/stage/dusclops/dusclops_board_bg_tiles.4bpp.lz"

gDusclopsBodyCollisionMap:: @ 0x083071D4
	.incbin "data/board_data/collision/dusclops/dusclops_entity_collision_96x120.bin"
