
gRayquazaBoardPalette:: @ 0x08363EC8
	.incbin "graphics/stage/rayquaza/rayquaza_board.gbapal"

gRayquazaBoardBG0Tilemap:: @ 0x083640C8
	.incbin "graphics/stage/rayquaza/rayquaza_board_bg0_tilemap.bin"

gRayquazaBoardCollisionTileDataAllLayers:: @ 0x083650C8
	.incbin "data/board_data/collision/rayquaza/board_tiledata.bin"

gRayquazaBoardCollisionAngleDataAllLayers:: @ 0x083670C8
	.incbin "data/board_data/collision/rayquaza/board_angledata.bin"

gRayquazaBoardCollisionTypeDataAllLayers:: @ 0x0836C048
	.incbin "data/board_data/collision/rayquaza/board_typedata.bin"

gRayquazaBoardBGScrollTilemap:: @ 0x0836E808
	.incbin "graphics/stage/rayquaza/rayquaza_board_scroll_tilemap.bin"

gRayquazaBoardBG1Tilemap:: @ 0x0836F808
	.incbin "graphics/stage/rayquaza/rayquaza_board_bg1_tilemap.bin"

gRayquazaBoardCompressedBGTiles:: @ 0x08370808
	.incbin "graphics/stage/rayquaza/rayquaza_board_bg_tiles.4bpp.lz"

gRayquazaBodyCollisionMap:: @ 0x083722E8
	.incbin "data/board_data/collision/rayquaza/rayquaza_entity_collision_128x128.bin"
