
gSphealBoardPalette:: @ 0x0837A2E8
	.incbin "baserom.gba", 0x37A2E8, 0x200

gSphealWaterBackgroundTilemap:: @ 0x0837A4E8
	.incbin "baserom.gba", 0x37A4E8, 0x800

gSphealBoardCollisionTileDataAllLayers:: @ 0x0837ACE8
    .incbin "baserom.gba", 0x37ACE8, 0x2000

gSphealBoardCollisionAngleDataAllLayers:: @ 0x0837CCE8
    .incbin "baserom.gba", 0x37CCE8, 0xB780

gSphealBoardCollisionTypeDataAllLayers:: @ 0x08388468
    .incbin "baserom.gba", 0x388468, 0x5BC0

gSphealBoardBG1Tilemap:: @ 0x0838E028
	.incbin "baserom.gba", 0x38E028, 0x800

gSphealBoardCompressedBGTiles:: @ 0x0838E828
	.incbin "baserom.gba", 0x38E828, 0x3224

gSphealCrackedIceCollisionMap:: @ 0x08391A4C
	.incbin "baserom.gba", 0x391A4C, 0x2000

gSphealFrozenIceCollisionMap:: @ 0x08393A4C
	.incbin "baserom.gba", 0x393A4C, 0x2000
