#ifndef GUARD_CONSTANTS_BG_MUSIC_H
#define GUARD_CONSTANTS_BG_MUSIC_H

#define MUS_TITLE 1
#define MUS_TABLE_SELECT 3
#define MUS_UNKNOWN_SONG_1 5
#define MUS_UNKNOWN_SONG_5 6
#define MUS_OPENING 8
#define MUS_SHOP 11
#define MUS_END_OF_BALL 13
#define MUS_MOVE_MODE_START 16
#define MUS_EVOLUTION 26
#define MUS_POKEDEX 46

#endif // GUARD_CONSTANTS_BG_MUSIC_H
