#ifndef GUARD_CONSTANTS_COLLISION_H
#define GUARD_CONSTANTS_COLLISION_H

#define ANGLE_UP 0X4000
#define ANGLE_LEFT 0X8000
#define ANGLE_DOWN 0XC000
#define ANGLE_RIGHT 0X0000

#define ANGLE_UP_RANGE_MIN (ANGLE_UP - 0X10)
#define ANGLE_UP_RANGE_MAX (ANGLE_UP + 0X10)

#define ANGLE_UP_RIGHT_BOUNCE (ANGLE_UP - 0X200)
#define ANGLE_UP_LEFT_BOUNCE  (ANGLE_UP + 0X100)
#define ANGLE_UP_RIGHT_SPIN_BOOST 40
#define ANGLE_UP_LEFT_SPIN_BOOST -40

#define SPIN_BOOST_NONE 0

#define COLLISION_ANGLE_MASK 0x0000FFF0
#define COLLISION_TYPE_MASK 0XF

#endif //GUARD_CONSTANTS_COLLISION_H