#ifndef GUARD_CONSTANTS_EREADER_H
#define GUARD_CONSTANTS_EREADER_H


enum eReaderBonuses
{
    EREADER_SPECIAL_GUESTS_CARD = 0, // Card ID: 09-A002
    EREADER_ENCOUNTER_RATE_UP_CARD = 1, // Card ID: 09-A005
    EREADER_DX_MODE_CARD = 2, // Card ID: 09-A004
    // EREADER_DX_MODE_CARD = ???,
    EREADER_BONUS_STAGE_CARD = 4, // Card ID: 09-A001
    NUM_EREADER_CARDS
};

#endif // GUARD_CONSTANTS_EREADER_H
