#ifndef GUARD_CONSTANTS_FIELDS_H
#define GUARD_CONSTANTS_FIELDS_H

#define FIELD_RUBY          0
#define FIELD_SAPPHIRE      1
#define MAIN_FIELD_COUNT    2
#define FIELD_DUSCLOPS      (MAIN_FIELD_COUNT + 0)
#define FIELD_KECLEON       (MAIN_FIELD_COUNT + 1)
#define FIELD_KYOGRE        (MAIN_FIELD_COUNT + 2)
#define FIELD_GROUDON       (MAIN_FIELD_COUNT + 3)
#define FIELD_RAYQUAZA      (MAIN_FIELD_COUNT + 4)
#define FIELD_SPHEAL        (MAIN_FIELD_COUNT + 5)

#endif // GUARD_CONSTANTS_FIELDS_H
