#ifndef GUARD_CONSTANTS_MAIN_BOARD_H
#define GUARD_CONSTANTS_MAIN_BOARD_H

enum MainBoardTrapHoles{
    NOT_TRAPPED = 0,
    TRAP_CATCH_HOLE = 1,
    TRAP_EGG_HOLE = 2,
    TRAP_EVO_SHOP_HOLE = 3,
    TRAP_CENTER_HOLE = 4,
};

#endif // GUARD_CONSTANTS_MAIN_BOARD_H