#ifndef GUARD_CONSTANTS_PINBALL_GAME_H
#define GUARD_CONSTANTS_PINBALL_GAME_H

#define WILD_MON_LOCATION_COUNT     8
#define MAX_EVOLVABLE_PARTY_SIZE    16

#define BALL_POWER_UP_POKE_BALL     0
#define BALL_POWER_UP_GREAT_BALL    1
#define BALL_POWER_UP_ULTRA_BALL    2
#define BALL_POWER_UP_MASTER_BALL   3

#endif // GUARD_CONSTANTS_PINBALL_GAME_H
