#ifndef GUARD_CONSTANTS_PINBALL_INPUTS_H
#define GUARD_CONSTANTS_PINBALL_INPUTS_H

#define PINBALL_INPUT_LEFT_FLIPPER  0
#define PINBALL_INPUT_RIGHT_FLIPPER 1
#define PINBALL_INPUT_TILT_LEFT     2
#define PINBALL_INPUT_TILT_RIGHT    3
#define PINBALL_INPUT_TILT_UP       4
#define NUM_PINBALL_INPUTS          5

#define BUTTON_CONFIG_RESET         (-1)
#define BUTTON_CONFIG_TYPE_A        0
#define BUTTON_CONFIG_TYPE_B        1
#define BUTTON_CONFIG_TYPE_C        2
#define BUTTON_CONFIG_TYPE_D        3
#define BUTTON_CONFIG_TYPE_EDIT     4

#endif // GUARD_CONSTANTS_PINBALL_INPUTS_H
