#ifndef GUARD_CONSTANTS_PINBALL_GAME_H
#define GUARD_CONSTANTS_PINBALL_GAME_H

#define WILD_MON_LOCATION_COUNT     8
#define MAX_EVOLVABLE_PARTY_SIZE    16

#define BALL_UPGRADE_TYPE_POKE_BALL     0
#define BALL_UPGRADE_TYPE_GREAT_BALL    1
#define BALL_UPGRADE_TYPE_ULTRA_BALL    2
#define BALL_UPGRADE_TYPE_MASTER_BALL   3

#endif // GUARD_CONSTANTS_PINBALL_GAME_H
