#ifndef GUARD_CONSTANTS_RUBY_STATES_H
#define GUARD_CONSTANTS_RUBY_STATES_H

enum RubyPondStates{
    RUBY_POND_STATE_CHINCHOU_STAGGERED = 0,
    RUBY_POND_STATE_CHINCHOU_CLOCKWISE = 1,
    RUBY_POND_STATE_CHINCHOU_COUNTERCLOCKWISE = 2,
    RUBY_POND_STATE_CHINCHOU_ROWS = 3,
    RUBY_POND_STATE_LOTAD = 4,
    RUBY_POND_STATE_CHINCHOU_SINGLE_CLOCKWISE = 5,
    RUBY_POND_STATE_WHISCASH = 6
};

enum WhiscashStates{
    WHISCASH_STATE_ARRIVAL = 0,
    WHISCASH_STATE_SITTING = 1,
    WHISCASH_STATE_ABSORB_ZONE_HIT = 2,
    WHISCASH_STATE_ABSORBING = 3,
    WHISCASH_STATE_TO_SPHEAL_BOARD = 4,
    WHISCASH_STATE_INIT_RETURN_FROM_BONUS = 5,
    WHISCASH_STATE_RISE_SPIT_LEAVE = 6,
    WHISCASH_STATE_HIT = 7,
    WHISCASH_STATE_ANGRY = 8,
    WHISCASH_STATE_LEAVING = 9,
    WHISCASH_STATE_CLEANUP = 10,
};

enum WhiscashFramesetIx{
    WHISCASH_FRAME_SUBMERGED = 0,
    WHISCASH_FRAME_SPLASH = 2,
    WHISCASH_FRAME_SITTING = 4,
    WHISCASH_FRAME_ABSORB_BALL_START = 6,
    WHISCASH_FRAME_LEAVING = 9,
    WHISCASH_FRAME_BALL_HELD_SUNK = 12,
    WHISCASH_FRAME_DELIVER_BALL_START = 12,
    WHISCASH_FRAME_EMERGING = 14,
    WHISCASH_FRAME_SPITBALL = 20,
    WHISCASH_FRAME_DELIVER_BALL_END = 30,
    WHISCASH_FRAME_HIT = 31,
    WHISCASH_FRAME_LEAVING_AFTER_HIT = 42,
    WHISCASH_FRAME_GONE_AFTER_HIT = 45,
};

#endif // GUARD_CONSTANTS_RUBY_STATES_H