#ifndef GUARD_SCORE_H
#define GUARD_SCORE_H

#include "constants/numbers.h"

#define SCORE_10 (TEN)
#define SCORE_100 (HUNDRED)
#define SCORE_K (THOUSAND)
#define SCORE_M (THOUSAND * THOUSAND)

#define SCORE_HI_STEP (100 * SCORE_M)
#define SCORE_LO_MAX (SCORE_HI_STEP -1)
#define SCORE_HIGH_MAX (TEN * THOUSAND -1)
#define SCORE_HIGH_MAX_DISPLAY (TEN * MILLION - 1)

#define SCORE_COIN_ARROW_1_LIT (2 * SCORE_K)
#define SCORE_COIN_ARROW_2_LIT (5 * SCORE_K)
#define SCORE_COIN_ARROW_3_LIT (10 * SCORE_K)
#define SCORE_COIN_COLLECTED (SCORE_100)
#define SCORE_SHOP_ENTERED (500 * SCORE_K)

#define SCORE_SLINGSHOT_HIT (5 * SCORE_100)
#define SCORE_TRAVEL_MODE_COMPLETED (500 * SCORE_K)
#define SCORE_HOLE_LIGHT_ACTIVATED (1 * SCORE_K)
#define SCORE_ALL_HOLE_LIGHTS_LIT (4 * SCORE_K)
#define SCORE_CENTER_TRAP_HOLE (10 * SCORE_K)
#define SCORE_PIKA_CHARGE_TICK (SCORE_100)
#define SCORE_PIKA_FULL_CHARGE (3 * SCORE_K)
#define SCORE_PIKA_KICKBACK_FIRED (30 * SCORE_K)

#define SCORE_BALL_UPGRADE_LIGHT_ACTIVATED (1 * SCORE_K)
#define SCORE_BALL_UPGRADE_ALL_LIT (4 * SCORE_K)
#define SCORE_BUMPER_HIT (5 * SCORE_100)
#define SCORE_BUMPER_BONUS_HIT (50 * SCORE_K) // After 100 hits

#define SCORE_GET_ARROW_1_LIT (2 * SCORE_K)
#define SCORE_GET_ARROW_2_LIT (5 * SCORE_K)
#define SCORE_GET_ARROW_3_LIT (10 * SCORE_K)
#define SCORE_CATCH_TILE_BURST (300 * SCORE_K)
#define SCORE_CATCH_HIT (10 * SCORE_K)
#define SCORE_JIRACHI_CATCH_HIT (10 * SCORE_K)
#define SCORE_RARE_CATCH (5 * SCORE_M)
#define SCORE_STEP_RARE_CATCH (80 * SCORE_K)
#define SCORE_LATI_CATCH (10 * SCORE_M)
#define SCORE_STEP_LATI_CATCH (140 * SCORE_K)
#define SCORE_NORMAL_CATCH (1 * SCORE_M)
#define SCORE_RAYQUAZA_CATCH (30 * SCORE_M)
#define SCORE_KYRGRO_CATCH (10 * SCORE_M)
#define SCORE_STEP_LEGENDARY_CATCH (400 * SCORE_K)

#define SCORE_EVO_ARROW_1_LIT (2 * SCORE_K)
#define SCORE_EVO_ARROW_2_LIT (5 * SCORE_K)
#define SCORE_EVO_ARROW_3_LIT (10 * SCORE_K)
#define SCORE_EVO_ITEM_COLLECTED (10 * SCORE_K)
#define SCORE_EVO_COMPLETED (5 * SCORE_M)

#define SCORE_PICHU_HATCH (10 * SCORE_M)
#define SCORE_STEP_PICHU_HATCH (140 * SCORE_K)
#define SCORE_NORMAL_HATCH (3 * SCORE_M)

#define SCORE_CHIKORITA_BUTTON (1 * SCORE_K)
#define SCORE_LINOONE_BUMPER_HIT (3 * SCORE_K)
#define SCORE_MAKUHITA_HIT_BALL (10 * SCORE_K)
#define SCORE_SHARPEDO_BALL_CATCH (50 * SCORE_K)
#define SCORE_CYNDAQUIL_HIT (5 * SCORE_K)
#define SCORE_HATCH_CAVE_CATCH (100 * SCORE_K)
#define SCORE_AERODACTYL_EGG_DELIVERY (100 * SCORE_K)
#define SCORE_TOTODILE_EGG_DELIVERY (2 * SCORE_M)
#define SCORE_RUBY_BONUS_MULTIPLIER_BUTTON (1 * SCORE_K)
#define SCORE_RUBY_POND_CHANGE_BUTTON (2 * SCORE_K)
#define SCORE_WHISCASH_HIT (SCORE_10)
#define SCORE_WHISCASH_ABSORBS_BALL (5 * SCORE_K)
#define SCORE_RUBY_SHOP_DOOR_HIT (50 * SCORE_K)
#define SCORE_NUZLEAF_LOWER_HIT (50 * SCORE_K)
#define SCORE_NUZLEAF_UPPER_HIT (100 * SCORE_K)

#define SCORE_WAILMER_BALL_CATCH (50 * SCORE_K)
#define SCORE_SAPPHIRE_SHOP_GATE_HIT (SCORE_10)
#define SCORE_SAPPHIRE_SHOP_GATE_TRIGGER_ACTIVATED (2 * SCORE_K)
#define SCORE_SAPPHIRE_BONUS_MULTIPLIER_BUTTON (5 * SCORE_K)
#define SCORE_PELLIPER_BALL_GRAB (100 * SCORE_K)
#define SCORE_ZIGZAGOON_READY_BUTTON (3 * SCORE_K)
#define SCORE_ZIGZAGOON_ROULETTE_STOP (5 * SCORE_K)
#define SCORE_SEEDOT_BUTTON (3 * SCORE_K)
#define SCORE_HATCH_MACHINE_STAGE_ADVANCE (20 * SCORE_K)
#define SCORE_HATCH_MACHINE_EGG_HATCH (200 * SCORE_K)

#define SCORE_DUSKULL_HIT (100 * SCORE_K)
#define SCORE_DUSCLOPS_HIT (300 * SCORE_K)
#define SCORE_DUSCLOPS_BONUS_COMPLETE (30 * SCORE_M)
#define SCORE_STEP_DUSCLOPS_BONUS_TALLY (400 * SCORE_K)

#define SCORE_KECLEON_SCOPE_COLLECTED (10 * SCORE_K)
#define SCORE_KECLEON_HIT_WHILE_DOWN (500 * SCORE_K)
#define SCORE_KECLEON_BONUS_COMPLETE (30 * SCORE_M)
#define SCORE_STEP_KECLEON_BONUS_TALLY (400 * SCORE_K)

#define SCORE_KYOGRE_HIT (500 * SCORE_K)
#define SCORE_KYOGRE_BONUS_COMPLETE (50 * SCORE_M)
#define SCORE_STEP_KYOGRE_BONUS_TALLY (400 * SCORE_K)

#define SCORE_GROUDON_HIT (500 * SCORE_K)
#define SCORE_GROUDON_BONUS_COMPLETE (50 * SCORE_M)
#define SCORE_STEP_GROUDON_BONUS_TALLY (400 * SCORE_K)

#define SCORE_RAYQUAZA_HIT (1 * SCORE_M)
#define SCORE_RAYQUAZA_BONUS_COMPLETE  (100 * SCORE_M -1)
#define SCORE_STEP_RAYQUAZA_BONUS_TALLY (400 * SCORE_K)

#define SCORE_SPHEAL_HIT (3 * SCORE_K)
#define SCORE_SEALEO_HIT (5 * SCORE_K)
#define SCORE_PER_BALL_IN_NET (1 * SCORE_M)
#define SCORE_PER_SPHEAL_IN_NET (5 * SCORE_M)
#define SCORE_STEP_SEAL_RESULTS (400 * SCORE_K)

#define SCORE_STEP_DEFAULT (40 * SCORE_K)

#define SCORE_BONUS_PER_CATCH (500 * SCORE_K)
#define SCORE_BONUS_PER_EVO (750 * SCORE_K)
#define SCORE_BONUS_PER_TRAVEL (500 * SCORE_K)
#define SCORE_BONUS_PER_SLOTS_PLAYED (100 * SCORE_K)
#define SCORE_BONUS_PER_PIKA_SAVER (100 * SCORE_K)

#endif // GUARD_SCORE_H