#ifndef GUARD_SCORE_H
#define GUARD_SCORE_H

#define SCORE_10 (TEN)
#define SCORE_100 (HUNDRED)
#define SCORE_K (THOUSAND)
#define SCORE_10K (TEN * THOUSAND)
#define SCORE_100K (HUNDRED * THOUSAND)
#define SCORE_M (THOUSAND * THOUSAND)
#define SCORE_10M (TEN * MILLION)
#define SCORE_100M (HUNDRED * MILLION)

#define SCORE_HI_STEP (SCORE_100M)
#define SCORE_LO_MAX (SCORE_HI_STEP -1)
#define SCORE_HIGH_MAX (TEN * THOUSAND -1)
#define SCORE_HIGH_MAX_DISPLAY (TEN * MILLION - 1)

#endif // GUARD_SCORE_H