#ifndef GUARD_SCORE_H
#define GUARD_SCORE_H

#include "constants/numbers.h"

#define SCORE_10 (TEN)
#define SCORE_100 (HUNDRED)
#define SCORE_K (THOUSAND)
#define SCORE_M (THOUSAND * THOUSAND)

#define SCORE_HI_STEP (100 * SCORE_M)
#define SCORE_LO_MAX (SCORE_HI_STEP -1)
#define SCORE_HIGH_MAX (TEN * THOUSAND -1)
#define SCORE_HIGH_MAX_DISPLAY (TEN * MILLION - 1)


#define SCORE_ALL_HOLE_LIGHTS_LIT (4 * SCORE_K)
#define SCORE_CENTER_TRAP_HOLE (10 * SCORE_K)
#define SCORE_PIKA_CHARGE_TICK (SCORE_100)
#define SCORE_PIKA_FULL_CHARGE (3 * SCORE_K)
#define SCORE_PIKA_KICKBACK_FIRED (30 * SCORE_K)


#define SCORE_CATCH_TILE_BURST (300 * SCORE_K)
#define SCORE_CATCH_HIT (10 * SCORE_K)
#define SCORE_JIRACHI_CATCH_HIT (10 * SCORE_K)
#define SCORE_RARE_CATCH (5 * SCORE_M)
#define SCORE_STEP_RARE_CATCH (80 * SCORE_K)
#define SCORE_LATI_CATCH (10 * SCORE_M)
#define SCORE_STEP_LATI_CATCH (140 * SCORE_K)
#define SCORE_NORMAL_CATCH (1 * SCORE_M)
#define SCORE_RAYQUAZA_CATCH (30 * SCORE_M)
#define SCORE_KYRGRO_CATCH (10 * SCORE_M)
#define SCORE_STEP_LEGENDARY_CATCH (400 * SCORE_K)

#define SCORE_EVO_ITEM_COLLECTED (10 * SCORE_K)
#define SCORE_EVO_COMPLETED (5 * SCORE_M)

#define SCORE_PICHU_HATCH (10 * SCORE_M)
#define SCORE_STEP_PICHU_HATCH (140 * SCORE_K)
#define SCORE_NORMAL_HATCH (3 * SCORE_M)


#define BONUS_DUSKULL_COMPLETE_POINTS (30 * SCORE_M)
#define SCORE_DUSKULL_HIT (100 * SCORE_K)
#define SCORE_DUSCLOPS_HIT (300 * SCORE_K)

#define BONUS_GROUDON_COMPLETE_POINTS (50 * SCORE_M)
#define SCORE_GROUDON_HIT (500 * SCORE_K)

#define BONUS_KECLEON_COMPLETE_POINTS (30 * SCORE_M)
#define SCORE_KECLEON_HIT_WHILE_DOWN (500 * SCORE_K)
#define SCORE_KECLEON_SCOPE_COLLECTED (10 * SCORE_K)

#define SCORE_PER_BALL_IN_NET (1 * SCORE_M)
#define SCORE_PER_SPHEAL_IN_NET (5 * SCORE_M)


#endif // GUARD_SCORE_H