#ifndef GUARD_CONSTANTS_SPECIES_H
#define GUARD_CONSTANTS_SPECIES_H

#define SPECIES_TREECKO         0
#define SPECIES_GROVYLE         1
#define SPECIES_SCEPTILE        2
#define SPECIES_TORCHIC         3
#define SPECIES_COMBUSKEN       4
#define SPECIES_BLAZIKEN        5
#define SPECIES_MUDKIP          6
#define SPECIES_MARSHTOMP       7
#define SPECIES_SWAMPERT        8
#define SPECIES_POOCHYENA       9
#define SPECIES_MIGHTYENA       10
#define SPECIES_ZIGZAGOON       11
#define SPECIES_LINOONE         12
#define SPECIES_WURMPLE         13
#define SPECIES_SILCOON         14
#define SPECIES_BEAUTIFLY       15
#define SPECIES_CASCOON         16
#define SPECIES_DUSTOX          17
#define SPECIES_LOTAD           18
#define SPECIES_LOMBRE          19
#define SPECIES_LUDICOLO        20
#define SPECIES_SEEDOT          21
#define SPECIES_NUZLEAF         22
#define SPECIES_SHIFTRY         23
#define SPECIES_TAILLOW         24
#define SPECIES_SWELLOW         25
#define SPECIES_WINGULL         26
#define SPECIES_PELIPPER        27
#define SPECIES_RALTS           28
#define SPECIES_KIRLIA          29
#define SPECIES_GARDEVOIR       30
#define SPECIES_SURSKIT         31
#define SPECIES_MASQUERAIN      32
#define SPECIES_SHROOMISH       33
#define SPECIES_BRELOOM         34
#define SPECIES_SLAKOTH         35
#define SPECIES_VIGOROTH        36
#define SPECIES_SLAKING         37
#define SPECIES_ABRA            38
#define SPECIES_KADABRA         39
#define SPECIES_ALAKAZAM        40
#define SPECIES_NINCADA         41
#define SPECIES_NINJASK         42
#define SPECIES_SHEDINJA        43
#define SPECIES_WHISMUR         44
#define SPECIES_LOUDRED         45
#define SPECIES_EXPLOUD         46
#define SPECIES_MAKUHITA        47
#define SPECIES_HARIYAMA        48
#define SPECIES_GOLDEEN         49
#define SPECIES_SEAKING         50
#define SPECIES_MAGIKARP        51
#define SPECIES_GYARADOS        52
#define SPECIES_AZURILL         53
#define SPECIES_MARILL          54
#define SPECIES_AZUMARILL       55
#define SPECIES_GEODUDE         56
#define SPECIES_GRAVELER        57
#define SPECIES_GOLEM           58
#define SPECIES_NOSEPASS        59
#define SPECIES_SKITTY          60
#define SPECIES_DELCATTY        61
#define SPECIES_ZUBAT           62
#define SPECIES_GOLBAT          63
#define SPECIES_CROBAT          64
#define SPECIES_TENTACOOL       65
#define SPECIES_TENTACRUEL      66
#define SPECIES_SABLEYE         67
#define SPECIES_MAWILE          68
#define SPECIES_ARON            69
#define SPECIES_LAIRON          70
#define SPECIES_AGGRON          71
#define SPECIES_MACHOP          72
#define SPECIES_MACHOKE         73
#define SPECIES_MACHAMP         74
#define SPECIES_MEDITITE        75
#define SPECIES_MEDICHAM        76
#define SPECIES_ELECTRIKE       77
#define SPECIES_MANECTRIC       78
#define SPECIES_PLUSLE          79
#define SPECIES_MINUN           80
#define SPECIES_MAGNEMITE       81
#define SPECIES_MAGNETON        82
#define SPECIES_VOLTORB         83
#define SPECIES_ELECTRODE       84
#define SPECIES_VOLBEAT         85
#define SPECIES_ILLUMISE        86
#define SPECIES_ODDISH          87
#define SPECIES_GLOOM           88
#define SPECIES_VILEPLUME       89
#define SPECIES_BELLOSSOM       90
#define SPECIES_DODUO           91
#define SPECIES_DODRIO          92
#define SPECIES_ROSELIA         93
#define SPECIES_GULPIN          94
#define SPECIES_SWALOT          95
#define SPECIES_CARVANHA        96
#define SPECIES_SHARPEDO        97
#define SPECIES_WAILMER         98
#define SPECIES_WAILORD         99
#define SPECIES_NUMEL           100
#define SPECIES_CAMERUPT        101
#define SPECIES_SLUGMA          102
#define SPECIES_MAGCARGO        103
#define SPECIES_TORKOAL         104
#define SPECIES_GRIMER          105
#define SPECIES_MUK             106
#define SPECIES_KOFFING         107
#define SPECIES_WEEZING         108
#define SPECIES_SPOINK          109
#define SPECIES_GRUMPIG         110
#define SPECIES_SANDSHREW       111
#define SPECIES_SANDSLASH       112
#define SPECIES_SPINDA          113
#define SPECIES_SKARMORY        114
#define SPECIES_TRAPINCH        115
#define SPECIES_VIBRAVA         116
#define SPECIES_FLYGON          117
#define SPECIES_CACNEA          118
#define SPECIES_CACTURNE        119
#define SPECIES_SWABLU          120
#define SPECIES_ALTARIA         121
#define SPECIES_ZANGOOSE        122
#define SPECIES_SEVIPER         123
#define SPECIES_LUNATONE        124
#define SPECIES_SOLROCK         125
#define SPECIES_BARBOACH        126
#define SPECIES_WHISCASH        127
#define SPECIES_CORPHISH        128
#define SPECIES_CRAWDAUNT       129
#define SPECIES_BALTOY          130
#define SPECIES_CLAYDOL         131
#define SPECIES_LILEEP          132
#define SPECIES_CRADILY         133
#define SPECIES_ANORITH         134
#define SPECIES_ARMALDO         135
#define SPECIES_IGGLYBUFF       136
#define SPECIES_JIGGLYPUFF      137
#define SPECIES_WIGGLYTUFF      138
#define SPECIES_FEEBAS          139
#define SPECIES_MILOTIC         140
#define SPECIES_CASTFORM        141
#define SPECIES_STARYU          142
#define SPECIES_STARMIE         143
#define SPECIES_KECLEON         144
#define SPECIES_SHUPPET         145
#define SPECIES_BANETTE         146
#define SPECIES_DUSKULL         147
#define SPECIES_DUSCLOPS        148
#define SPECIES_TROPIUS         149
#define SPECIES_CHIMECHO        150
#define SPECIES_ABSOL           151
#define SPECIES_VULPIX          152
#define SPECIES_NINETALES       153
#define SPECIES_PICHU           154
#define SPECIES_PIKACHU         155
#define SPECIES_RAICHU          156
#define SPECIES_PSYDUCK         157
#define SPECIES_GOLDUCK         158
#define SPECIES_WYNAUT          159
#define SPECIES_WOBBUFFET       160
#define SPECIES_NATU            161
#define SPECIES_XATU            162
#define SPECIES_GIRAFARIG       163
#define SPECIES_PHANPY          164
#define SPECIES_DONPHAN         165
#define SPECIES_PINSIR          166
#define SPECIES_HERACROSS       167
#define SPECIES_RHYHORN         168
#define SPECIES_RHYDON          169
#define SPECIES_SNORUNT         170
#define SPECIES_GLALIE          171
#define SPECIES_SPHEAL          172
#define SPECIES_SEALEO          173
#define SPECIES_WALREIN         174
#define SPECIES_CLAMPERL        175
#define SPECIES_HUNTAIL         176
#define SPECIES_GOREBYSS        177
#define SPECIES_RELICANTH       178
#define SPECIES_CORSOLA         179
#define SPECIES_CHINCHOU        180
#define SPECIES_LANTURN         181
#define SPECIES_LUVDISC         182
#define SPECIES_HORSEA          183
#define SPECIES_SEADRA          184
#define SPECIES_KINGDRA         185
#define SPECIES_BAGON           186
#define SPECIES_SHELGON         187
#define SPECIES_SALAMENCE       188
#define SPECIES_BELDUM          189
#define SPECIES_METANG          190
#define SPECIES_METAGROSS       191
#define SPECIES_REGIROCK        192
#define SPECIES_REGICE          193
#define SPECIES_REGISTEEL       194
#define SPECIES_LATIAS          195
#define SPECIES_LATIOS          196
#define SPECIES_KYOGRE          197
#define SPECIES_GROUDON         198
#define SPECIES_RAYQUAZA        199
#define SPECIES_JIRACHI         200
#define SPECIES_CHIKORITA       201
#define SPECIES_CYNDAQUIL       202
#define SPECIES_TOTODILE        203
#define SPECIES_AERODACTYL      204
#define SPECIES_NONE            205

#define BONUS_SPECIES_START SPECIES_CHIKORITA
#define NUM_BONUS_SPECIES (SPECIES_NONE - SPECIES_CHIKORITA)
#define NUM_SPECIES SPECIES_NONE

#endif // GUARD_CONSTANTS_SPECIES_H
