gLocation_Pals:: @ 0x081C00E4
	.incbin "graphics/area_portraits/loc00_ruby_forest.gbapal"
	.incbin "graphics/area_portraits/loc01_sapphire_forest.gbapal"
	.incbin "graphics/area_portraits/loc02_ruby_plains.gbapal"
	.incbin "graphics/area_portraits/loc03_sapphire_plains.gbapal"
	.incbin "graphics/area_portraits/loc04_ruby_harbor.gbapal"
	.incbin "graphics/area_portraits/loc05_sapphire_beach.gbapal"
	.incbin "graphics/area_portraits/loc06_ruby_cave.gbapal"
	.incbin "graphics/area_portraits/loc07_sapphire_cave.gbapal"
	.incbin "graphics/area_portraits/loc08_ruby_safari_zone.gbapal"
	.incbin "graphics/area_portraits/loc09_ruby_volcano.gbapal"
	.incbin "graphics/area_portraits/loc10_sapphire_lake.gbapal"
	.incbin "graphics/area_portraits/loc11_sapphire_desert.gbapal"
	.incbin "graphics/area_portraits/loc12_ruins.gbapal"

	@ 3 unused palettes: one with color data, two blank
	.incbin "graphics/area_portraits/loc_unused.gbapal.bin"
