#ifndef GUARD_CONSTANTS_MEM_LAYOUT_DUSCLOPS
#define GUARD_CONSTANTS_MEM_LAYOUT_DUSCLOPS

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_DUSCLOPS_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_DUSCLOPS_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,2,0))
#define BG_VRAM_ADDR_DUSCLOPS_LAYER_1_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,4,0))
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug


// Tiles

// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud

#define OBJ_VRAM_ADDR_DUSKULL_TILES                 OBJ_TILE_ADDR(TILE_INDEX(0, 2, 9))
#define SIZE_OF_VRAM_DUSKULL_TILES                  20 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_DUSCLOPS_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 4, 5))
#define SIZE_OF_VRAM_DUSCLOPS_TILES                 2 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_DUSCLOPS_GRAB_FX_TILES        OBJ_TILE_ADDR(TILE_INDEX(0, 6, 5))
#define SIZE_OF_VRAM_DUSCLOPS_GRAB_FX_TILES         16 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_DUSCLOPS_PHASING_FX_TILES     OBJ_TILE_ADDR(TILE_INDEX(0, 6, 21))
#define SIZE_OF_VRAM_DUSCLOPS_PHASING_FX_TILES      3 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_DUSCLOPS_BANNER_TILES         OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_DUSCLOPS_BANNER_TILES          8 * MEM_SIZE_OF_TILE_ROW

#endif