#ifndef GUARD_CONSTANTS_MEM_LAYOUT_FIELD_SELECT
#define GUARD_CONSTANTS_MEM_LAYOUT_FIELD_SELECT

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_FIELD_SELECT_BG0_TILEMAP       BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_FIELD_SELECT_BG1_TILEMAP       BG_TILE_ADDR(TILE_INDEX(0,2,0))
#define BG_VRAM_ADDR_FIELD_SELECT_BG2_TILEMAP       BG_TILE_ADDR(TILE_INDEX(0,4,0))
#define BG_VRAM_ADDR_FIELD_SELECT_LAYOUT_TILES      BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_FIELD_SELECT_LAYOUT_TILES      5 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_FIELD_SELECT_BOARD_TILES       BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define SIZE_OF_VRAM_FIELD_SELECT_BOARD_TILES       14 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_FIELD_SELECT_SPRITE_TILES     OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_FIELD_SELECT_SPRITE_TILES      16 * MEM_SIZE_OF_TILE_ROW + 1*TILE_SIZE_4BPP




#define BG_VRAM_ADDR_BONUS_FIELD_SELECT_BG0_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_BONUS_FIELD_SELECT_BG1_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,2,0))
#define BG_VRAM_ADDR_BONUS_FIELD_SELECT_BG2_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,4,0))
#define BG_VRAM_ADDR_BONUS_FIELD_SELECT_LAYOUT_TILES    BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_BONUS_FIELD_SELECT_LAYOUT_TILES    16 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_BONUS_FIELD_SELECT_BOARD_TILES     BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define SIZE_OF_VRAM_BONUS_FIELD_SELECT_BOARD_TILES     6 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_BONUS_FIELD_SELECT_SPRITE_TILES   OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_BONUS_FIELD_SELECT_SPRITE_TILES    16 * MEM_SIZE_OF_TILE_ROW + 1*TILE_SIZE_4BPP


#endif