#ifndef GUARD_CONSTANTS_MEM_LAYOUT_GROUDON
#define GUARD_CONSTANTS_MEM_LAYOUT_GROUDON

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_GROUDON_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_GROUDON_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,2,0))
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug


// Tiles

// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud

#define OBJ_VRAM_ADDR_GROUDON_BOULDER_TILES     OBJ_TILE_ADDR(TILE_INDEX(0, 3, 29))
#define SIZE_OF_VRAM_GROUDON_BOULDER_TILES      24 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_GROUDON_ATTACK_FX_TILES   OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_GROUDON_ATTACK_FX_TILES    8 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_GROUDON_BANNER_TILES      OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_GROUDON_BANNER_TILES       8 * MEM_SIZE_OF_TILE_ROW

#endif