#ifndef GUARD_CONSTANTS_MEM_LAYOUT_HIGH_SCORE
#define GUARD_CONSTANTS_MEM_LAYOUT_HIGH_SCORE

#include "constants/mem_layout/shared.h"

#define BG_VRAM_ADDR_HIGH_SCORE_BG2_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_HIGH_SCORE_BG3_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,4,0))
#define BG_VRAM_ADDR_HIGH_SCORE_TEXT_TILES      BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_HIGH_SCORE_TEXT_TILES      18 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_HIGH_SCORE_FRAME_TILES     BG_TILE_ADDR(TILE_INDEX(3,0,0))
#define SIZE_OF_VRAM_HIGH_SCORE_FRAME_TILES     11 * MEM_SIZE_OF_TILE_ROW
#define OBJ_VRAM_ADDR_HIGH_SCORE_SPRITE_TILES   OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_HIGH_SCORE_SPRITE_TILES    17 * MEM_SIZE_OF_TILE_ROW + 1*TILE_SIZE_4BPP

#endif