#ifndef GUARD_CONSTANTS_MEM_LAYOUT_INTRO
#define GUARD_CONSTANTS_MEM_LAYOUT_INTRO

#include "constants/mem_layout/shared.h"

// NOTE: Idle section is inside the area defined for the HUD tilemap space

//Idle board (Demo)
#define BG_VRAM_ADDR_IDLE_PRESS_START_TILEMAP    BG_TILE_ADDR(TILE_INDEX(0, 9, 20))
// Size 2 "tiles"
#define BG_VRAM_ADDR_IDLE_TBD_TILEMAP            BG_TILE_ADDR(TILE_INDEX(0, 9, 18))
// Size 2 "tiles"


#define BG_VRAM_ADDR_COPYRIGHT_TILEMAP      BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_COPYRIGHT_TILEMAP      MEM_SIZE_OF_TILEMAP_256_BY_256

#define BG_VRAM_ADDR_COPYRIGHT_TILES        BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_COPYRIGHT_TILES        2*MEM_SIZE_OF_TILE_ROW


#define BG_VRAM_ADDR_INTRO1_TORCHIC_TEXT_TILES      BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO1_TORCHIC_TEXT_TILES      22 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_INTRO1_TORCHIC_BALL_TILES      26 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_INTRO1_TORCHIC_SMALL_BALL_RECT BG_TILE_ADDR(TILE_INDEX(0, 13, 23))
#define BG_VRAM_ADDR_INTRO1_TORCHIC_BIG_BALL_RECT   BG_TILE_ADDR(TILE_INDEX(0, 12, 22))
#define BG_VRAM_ADDR_INTRO1_TORCHIC_BG0_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,4,0))
#define BG_VRAM_ADDR_INTRO1_TORCHIC_BG1_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,6,0))
#define BG_VRAM_ADDR_INTRO1_TORCHIC_BG2_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,10,0))
#define BG_VRAM_ADDR_INTRO1_TORCHIC_BG3_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,14,0))
#define OBJ_VRAM_ADDR_INTRO1_TORCHIC_SPRITE_TILES   OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO1_TORCHIC_SPRITE_TILES    32 * MEM_SIZE_OF_TILE_ROW


#define BG_VRAM_ADDR_INTRO2_PIKAS_MON_TILES         BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO2_PIKAS_MON_TILES         15 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_INTRO2_PIKAS_BG0_TILEMAP       BG_TILE_ADDR(TILE_INDEX(1,8,0))
#define BG_VRAM_ADDR_INTRO2_PIKAS_BG1_TILEMAP       BG_TILE_ADDR(TILE_INDEX(3,4,0))
#define BG_VRAM_ADDR_INTRO2_PIKAS_BG3_TILEMAP       BG_TILE_ADDR(TILE_INDEX(3,12,0))


#define BG_VRAM_ADDR_INTRO3_TREECKO_BG_TILES        BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO3_TREECKO_BG_TILES        27 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_INTRO3_TREECKO_BG0_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,4,0))
#define BG_VRAM_ADDR_INTRO3_TREECKO_BG1_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,8,0))
#define BG_VRAM_ADDR_INTRO3_TREECKO_BG2_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,10,0))
#define BG_VRAM_ADDR_INTRO3_TREECKO_BG3_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,14,0))
#define OBJ_VRAM_ADDR_INTRO3_TREECKO_SPRITE_TILES   OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO3_TREECKO_SPRITE_TILES    8 * MEM_SIZE_OF_TILE_ROW


#define BG_VRAM_ADDR_INTRO4_PLUSLEMINUN_MON_TILES       BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO4_PLUSLEMINUN_MON_TILES       16 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_INTRO4_PLUSLEMINUN_BG0_TILEMAP     BG_TILE_ADDR(TILE_INDEX(1,8,0))
#define BG_VRAM_ADDR_INTRO4_PLUSLEMINUN_BG1_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,4,0))
#define BG_VRAM_ADDR_INTRO4_PLUSLEMINUN_BG3_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,12,0))


#define BG_VRAM_ADDR_INTRO5_MUDKIP_BG_TILES         BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO5_MUDKIP_BG_TILES         10 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_INTRO5_MUDKIP_BALL_RECT        BG_TILE_ADDR(TILE_INDEX(0, 11, 23))
#define BG_VRAM_ADDR_INTRO5_MUDKIP_BG0_TILEMAP      BG_TILE_ADDR(TILE_INDEX(1,8,0))
#define BG_VRAM_ADDR_INTRO5_MUDKIP_BG1_TILEMAP      BG_TILE_ADDR(TILE_INDEX(1,12,0))
#define BG_VRAM_ADDR_INTRO5_MUDKIP_BG2_TILEMAP      BG_TILE_ADDR(TILE_INDEX(3,8,0))
#define BG_VRAM_ADDR_INTRO5_MUDKIP_BG3_TILEMAP      BG_TILE_ADDR(TILE_INDEX(3,12,0))
#define OBJ_VRAM_ADDR_INTRO5_MUDKIP_SPRITE_TILES    OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO5_MUDKIP_SPRITE_TILES     12 * MEM_SIZE_OF_TILE_ROW


#define BG_VRAM_ADDR_INTRO6_CHINCHOU_BG_TILES        BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO6_CHINCHOU_BG_TILES        25 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_INTRO6_CHINCHOU_BG0_TILEMAP     BG_TILE_ADDR(TILE_INDEX(1,14,0))
#define BG_VRAM_ADDR_INTRO6_CHINCHOU_BG1_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,4,0))
#define BG_VRAM_ADDR_INTRO6_CHINCHOU_BG2_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,12,0))
#define BG_VRAM_ADDR_INTRO6_CHINCHOU_BG3_TILEMAP     BG_TILE_ADDR(TILE_INDEX(3,14,0))
#define OBJ_VRAM_ADDR_INTRO6_CHINCHOU_SPRITE_TILES   OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO6_CHINCHOU_SPRITE_TILES    4 * MEM_SIZE_OF_TILE_ROW


#define BG_VRAM_ADDR_INTRO7_PARADE_BG_TILES         BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO7_PARADE_BG_TILES         20 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_INTRO7_PARADE_BG3_TILEMAP      BG_TILE_ADDR(TILE_INDEX(1,14,0))
#define BG_VRAM_ADDR_INTRO7_PARADE_BG0_TILEMAP      BG_TILE_ADDR(TILE_INDEX(2,8,0))
#define BG_VRAM_ADDR_INTRO7_PARADE_BG1_TILEMAP      BG_TILE_ADDR(TILE_INDEX(3,0,0))
#define BG_VRAM_ADDR_INTRO7_PARADE_BG2_TILEMAP      BG_TILE_ADDR(TILE_INDEX(3,8,0))
#define OBJ_VRAM_ADDR_INTRO7_PARADE_SPRITE_TILES    OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO7_PARADE_SPRITE_TILES     8 * MEM_SIZE_OF_TILE_ROW


#define BG_VRAM_ADDR_INTRO8_WAILMER_BG2_TILEMAP      BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_INTRO8_WAILMER_BG_TILES         BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_INTRO8_WAILMER_BG_TILES         13 * MEM_SIZE_OF_TILE_ROW
#define OBJ_VRAM_ADDR_INTRO8_WAILMER_SPRITE_TILES    OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO8_WAILMER_SPRITE_TILES     11 * MEM_SIZE_OF_TILE_ROW


#define BG_VRAM_ADDR_INTRO9_FLIGHT_BG3_TILEMAP      BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_INTRO9_FLIGHT_BG_TILES         BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_INTRO9_FLIGHT_BG_TILES         9 * MEM_SIZE_OF_TILE_ROW
#define OBJ_VRAM_ADDR_INTRO9_FLIGHT_SPRITE_TILES    OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_INTRO9_FLIGHT_SPRITE_TILES     28 * MEM_SIZE_OF_TILE_ROW

#endif