#ifndef GUARD_CONSTANTS_MEM_LAYOUT_KECLEON
#define GUARD_CONSTANTS_MEM_LAYOUT_KECLEON

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_KECLEON_LAYER_3_TILEMAP         BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_KECLEON_LAYER_2_TILEMAP         BG_TILE_ADDR(TILE_INDEX(0,2,0))
#define BG_VRAM_ADDR_KECLEON_LAYER_1_TILEMAP         BG_TILE_ADDR(TILE_INDEX(0,4,0))
#define BG_VRAM_ADDR_KECLEON_SCOPE_OVERLAY_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,4,0))
#define SIZE_OF_VRAM_KECLEON_SCOPE_OVERLAY_TILEMAP   20*MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW


// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug






// Tiles

// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud

#endif