#ifndef GUARD_CONSTANTS_MEM_LAYOUT_KYOGRE
#define GUARD_CONSTANTS_MEM_LAYOUT_KYOGRE

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_KYOGRE_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_KYOGRE_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,2,0))
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug

// Tiles
// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud

#define OBJ_VRAM_ADDR_KYOGRE_TILES          OBJ_TILE_ADDR(TILE_INDEX(0, 3, 29))
#define SIZE_OF_VRAM_KYOGRE_TOP_TILES       44 * TILE_SIZE_4BPP
#define SIZE_OF_VRAM_KYOGRE_BREACH_TILES    38 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_KYOGRE_WHIRLPOOL      OBJ_TILE_ADDR(TILE_INDEX(0, 5, 9))
#define SIZE_OF_VRAM_KYOGRE_WHIRLPOOL       16 * TILE_SIZE_4BPP


#define OBJ_VRAM_ADDR_KYOGRE_SURFACE_FX_TILES  OBJ_TILE_ADDR(TILE_INDEX(0, 9, 1))
#define SIZE_OF_VRAM_KYOGRE_SURFACE_FX_TILES   6 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_KYOGRE_FREEZE_TILES   OBJ_TILE_ADDR(TILE_INDEX(0, 9, 7))
#define SIZE_OF_VRAM_KYOGRE_FREEZE_TILES    30 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_KYOGRE_BANNER_TILES   OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_KYOGRE_BANNER_TILES    8 * MEM_SIZE_OF_TILE_ROW


#endif