#ifndef GUARD_CONSTANTS_MEM_LAYOUT_OPTIONS
#define GUARD_CONSTANTS_MEM_LAYOUT_OPTIONS

#include "constants/mem_layout/shared.h"

#define BG_VRAM_ADDR_OPTIONS_BG0_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_OPTIONS_BG1_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,2,0))
#define BG_VRAM_ADDR_OPTIONS_TEXT_TILES      BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_OPTIONS_TEXT_TILES      6 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_OPTIONS_FRAME_TILES     BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define SIZE_OF_VRAM_OPTIONS_FRAME_TILES     3 * MEM_SIZE_OF_TILE_ROW
#define OBJ_VRAM_ADDR_OPTIONS_SPRITE_TILES   OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_OPTIONS_SPRITE_TILES    8 * MEM_SIZE_OF_TILE_ROW + 1*TILE_SIZE_4BPP

#endif