#ifndef GUARD_CONSTANTS_MEM_LAYOUT_POKEDEX
#define GUARD_CONSTANTS_MEM_LAYOUT_POKEDEX

#include "constants/mem_layout/shared.h"

#define BG_VRAM_ADDR_POKEDEX_BG1_TILEMAP        BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_POKEDEX_DEX_TEXT_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,20))
#define SIZE_OF_VRAM_POKEDEX_DEX_TEXT_TILEMAP   7 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW
#define SIZE_OF_VRAM_POKEDEX_DEX_TEXT_PLUS_HANDLE_TILEMAP   8 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW
#define BG_VRAM_ADDR_POKEDEX_BG2_TILEMAP        BG_TILE_ADDR(TILE_INDEX(0,2,0))
#define BG_VRAM_ADDR_POKEDEX_BG3_TILEMAP        BG_TILE_ADDR(TILE_INDEX(0,4,0))

//Tile area with full dex text: number bank + species name/category/weight + entry
#define BG_VRAM_ADDR_POKEDEX_TEXT_TILES         BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define SIZE_OF_VRAM_POKEDEX_TEXT_TILES         17 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_POKEDEX_NAME_RECT          BG_TILE_ADDR(TILE_INDEX(1, 3, 0))
#define BG_VRAM_ADDR_POKEDEX_CATEGORY_RECT      BG_TILE_ADDR(TILE_INDEX(1, 3, 8))
//Tile area subset with *just* the dex entry text
#define BG_VRAM_ADDR_POKEDEX_ENTRY_TEXT         BG_TILE_ADDR(TILE_INDEX(1,7,0))
#define SIZE_OF_VRAM_POKEDEX_ENTRY_TEXT         6 * MEM_SIZE_OF_TILE_ROW

#define BG_VRAM_ADDR_POKEDEX_FRAME_TILES        BG_TILE_ADDR(TILE_INDEX(3,0,0))
#define SIZE_OF_VRAM_POKEDEX_FRAME_TILES        5 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_POKEDEX_SPRITE_TILES      OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_POKEDEX_SPRITE_TILES       27 * MEM_SIZE_OF_TILE_ROW + 1*TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_POKEDEX_MON_SPRITE_RECT   OBJ_TILE_ADDR(TILE_INDEX(0, 13, 0))
#define OBJ_VRAM_ADDR_POKEDEX_MON_BOARD_ANIM_RECT   OBJ_TILE_ADDR(TILE_INDEX(0, 14, 0))
#define OBJ_VRAM_ADDR_POKEDEX_MON_HATCH_ANIM_RECT   OBJ_TILE_ADDR(TILE_INDEX(1, 2, 0))

#endif