#ifndef GUARD_CONSTANTS_MEM_LAYOUT_RAYQUAZA
#define GUARD_CONSTANTS_MEM_LAYOUT_RAYQUAZA

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_RAYQUAZA_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_RAYQUAZA_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,4,0))
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug

#define BG_VRAM_ADDR_RAYQUAZA_LAYER_1_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,12,0))


// Tiles

// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud

#define OBJ_VRAM_ADDR_RAYQUAZA_TILES        OBJ_TILE_ADDR(TILE_INDEX(0, 5, 17))
#define SIZE_OF_VRAM_RAYQUAZA_TILES         2 * MEM_SIZE_OF_TILE_ROW + 3 * TILE_SIZE_4BPP
#define SIZE_OF_VRAM_RAYQUAZA_YELL_TILES    2 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_RAYQUAZA_TORNADO_TILES OBJ_TILE_ADDR(TILE_INDEX(0, 7, 21))
#define SIZE_OF_VRAM_RAYQUAZA_TORNADO_TILES  20 * TILE_SIZE_4BPP


#define OBJ_VRAM_ADDR_RAYQUAZA_INTRO_CLOUDS_TILES  OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_RAYQUAZA_INTRO_CLOUDS_TILES   10 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_RAYQUAZA_FLYBY_TILES   OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_RAYQUAZA_FLYBY_TILES    7 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_RAYQUAZA_BANNER_TILES  OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_RAYQUAZA_BANNER_TILES   8 * MEM_SIZE_OF_TILE_ROW

#endif