#ifndef GUARD_CONSTANTS_MEM_LAYOUT_RUBY
#define GUARD_CONSTANTS_MEM_LAYOUT_RUBY

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_RUBY_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_RUBY_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,4,0))
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug

// Shop is shared with sapphire, and inside the HUD tilemap region
#define BG_VRAM_ADDR_MAIN_BOARD_SHOP_BG_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,8,0))
#define SIZE_OF_VRAM_MAIN_BOARD_SHOP_BG_TILEMAP   49 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW

#define BG_VRAM_ADDR_RUBY_LAYER_1_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,12,0))

// Tiles

#define BG_VRAM_ADDR_RUBY_RAMP_TILES               BG_TILE_ADDR(TILE_INDEX(1,0,0))
// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud
#define BG_VRAM_ADDR_MAIN_SCROLL_SEGMENT_TILES          BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define BG_VRAM_ADDR_RUBY_SCROLL_SEGMENT_TILES          BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define SIZE_OF_VRAM_RUBY_INITIAL_BOTTOM_SCROLL_TILES   13 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_RUBY_INITIAL_TOP_SCROLL_TILES      BG_TILE_ADDR(TILE_INDEX(2,13,0))
#define SIZE_OF_VRAM_RUBY_INITIAL_TOP_SCROLL_TILES      9 * MEM_SIZE_OF_TILE_ROW




#define BG_VRAM_ADDR_RUBY_BMULT_SIGN_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 1))
#define BG_VRAM_ADDR_RUBY_BMULT_SIGN_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 2))

#define BG_VRAM_ADDR_RUBY_SHOP_SIGN_ROW0_TILES     BG_TILE_ADDR(TILE_INDEX(3, 6, 3))
#define BG_VRAM_ADDR_RUBY_SHOP_SIGN_ROW1_TILES     BG_TILE_ADDR(TILE_INDEX(3, 6, 9))
#define BG_VRAM_ADDR_RUBY_SHOP_SIGN_ROW2_TILES     BG_TILE_ADDR(TILE_INDEX(3, 6, 15))

#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 16))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 17))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW2_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 19))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW3_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 22))
#define BG_VRAM_ADDR_RUBY_LSLINGSHOT_ROW4_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 25))

#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 27))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 28))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW2_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 30))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW3_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 1))
#define BG_VRAM_ADDR_RUBY_RSLINGSHOT_ROW4_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 4))

// --------------------------------

#define OBJ_VRAM_ADDR_HATCH_CAVE_TILES              OBJ_TILE_ADDR(TILE_INDEX(0, 8, 21))
#define SIZE_OF_VRAM_HATCH_CAVE_TILES               36 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_CHIKORITA_TILES               OBJ_TILE_ADDR(TILE_INDEX(0, 9, 25))
#define SIZE_OF_VRAM_CHIKORITA_TILES                24 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_LINOONE_TILES_FOR_SIDE(sideIx) OBJ_TILE_ADDR(TILE_INDEX(0, 10, 17 + 8 * sideIx))
#define SIZE_OF_VRAM_RUBY_LINOONE_TILES             8 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SHARPEDO_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 11, 1))
#define SIZE_OF_VRAM_SHARPEDO_TILES                 19 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_RUBY_BUMPER(bumperIx)         OBJ_TILE_ADDR(TILE_INDEX(0, 11, 20 + 8 * bumperIx))
#define SIZE_OF_VRAM_RUBY_BUMPER_TILES              8 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_RUBY_MART_DOOR_TILES          OBJ_TILE_ADDR(TILE_INDEX(0, 12, 12))
#define SIZE_OF_VRAM_RUBY_MART_DOOR_TILES           12 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_CYNDAQUIL_TILES               OBJ_TILE_ADDR(TILE_INDEX(0, 12, 24))
#define SIZE_OF_VRAM_CYNDAQUIL_TILES                20 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_MAKUHITA_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 13, 12))
#define SIZE_OF_VRAM_MAKUHITA_TILES                 24 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_GULPIN_1_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 14, 4))
#define OBJ_VRAM_ADDR_GULPIN_2_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 14, 16))
#define OBJ_VRAM_ADDR_GULPIN_3_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 14, 28))
#define SIZE_OF_VRAM_GULPIN_TILES                   12 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_RUBY_MART_SIGN_TILES          OBJ_TILE_ADDR(TILE_INDEX(0, 15, 8))
#define SIZE_OF_VRAM_RUBY_MART_SIGN_TILES           40 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_CHIKORITA_BLADE_TILES         OBJ_TILE_ADDR(TILE_INDEX(1, 0, 16))
#define SIZE_OF_VRAM_CHIKORITA_BLADE_TILES          4 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_CHIKORITA_BLADE_HIT_FX_TILES  OBJ_TILE_ADDR(TILE_INDEX(1, 0, 20))
#define SIZE_OF_VRAM_CHIKORITA_BLADE_HIT_FX_TILES   8 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_NUZLEAF_TILES                 OBJ_TILE_ADDR(TILE_INDEX(1, 0, 28))
#define SIZE_OF_VRAM_NUZLEAF_TILES                  19 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_WHISCASH_TILES                OBJ_TILE_ADDR(TILE_INDEX(1, 1, 20))
#define SIZE_OF_VRAM_WHISCASH_TILES                 35 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_RAMP_PRIZE_TILES              OBJ_TILE_ADDR(TILE_INDEX(1, 2, 24))
#define SIZE_OF_VRAM_RAMP_PRIZE_TILES               4 * TILE_SIZE_4BPP


//FX section; shared space
#define SIZE_OF_VRAM_TOTODILE_EGG_DELIVERY_TILES    3 * MEM_SIZE_OF_TILE_ROW + 5 * TILE_SIZE_4BPP
#define SIZE_OF_VRAM_AERODACTYL_EGG_DELIVERY_TILES  4 * MEM_SIZE_OF_TILE_ROW

// Loaded in after the main ball saver banner
#define OBJ_VRAM_ADDR_LATIOS_BALL_SAVER_TILES       OBJ_TILE_ADDR(TILE_INDEX(1, 10, 0))
#define SIZE_OF_VRAM_LATIOS_BALL_SAVER_TILES        2 * MEM_SIZE_OF_TILE_ROW
#define OBJ_VRAM_ADDR_LATIOS_ARM_TILES              OBJ_TILE_ADDR(TILE_INDEX(1, 12, 0))
#define SIZE_OF_VRAM_LATIOS_ARM_TILES               6 * TILE_SIZE_4BPP


#endif