#ifndef GUARD_CONSTANTS_MEM_LAYOUT_SAPPHIRE
#define GUARD_CONSTANTS_MEM_LAYOUT_SAPPHIRE

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_SAPPHIRE_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_SAPPHIRE_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,4,0))
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug

#define BG_VRAM_ADDR_SAPPHIRE_LAYER_1_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,12,0))

// Tiles

#define BG_VRAM_ADDR_SAPPHIRE_RAMP_TILES                    BG_TILE_ADDR(TILE_INDEX(1,0,0))
// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud
#define BG_VRAM_ADDR_SAPPHIRE_SCROLL_SEGMENT_TILES          BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define SIZE_OF_VRAM_SAPPHIRE_INITIAL_BOTTOM_SCROLL_TILES   10 * MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_SAPPHIRE_INITIAL_TOP_SCROLL_TILES      BG_TILE_ADDR(TILE_INDEX(2,10,0))
#define SIZE_OF_VRAM_SAPPHIRE_INITIAL_TOP_SCROLL_TILES      12 * MEM_SIZE_OF_TILE_ROW

// Hatch machine *segments* go clockwise around it, based on the sparkle sequence
// The tile source is drawing it *mostly* in rows top to bottom.

#define BG_VRAM_ADDR_HATCH_MACHINE_ALL_TILES          BG_TILE_ADDR(TILE_INDEX(3, 6, 8))
#define SIZE_OF_VRAM_HATCH_MACHINE_ALL_TILES          34 * TILE_SIZE_4BPP

#define BG_VRAM_ADDR_HATCH_MACHINE_SEG4_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 8))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG2_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 14))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG4_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 16))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG2_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 6, 22))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG0_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 10))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG0_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 12))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG1_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 14))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG1_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 16))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG3_TILES         BG_TILE_ADDR(TILE_INDEX(3, 7, 18))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG5_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 20))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG5_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 22))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG6_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 24))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG6_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 26))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG7_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 28))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG7_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 7, 30))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG8_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 0))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG8_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 2))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG9_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 4))
#define BG_VRAM_ADDR_HATCH_MACHINE_SEG9_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 6))

#define BG_VRAM_ADDR_SAPPHIRE_LSLINGSHOT_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 8))
#define BG_VRAM_ADDR_SAPPHIRE_LSLINGSHOT_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 9))
#define BG_VRAM_ADDR_SAPPHIRE_LSLINGSHOT_ROW2_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 11))
#define BG_VRAM_ADDR_SAPPHIRE_LSLINGSHOT_ROW3_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 14))
#define BG_VRAM_ADDR_SAPPHIRE_LSLINGSHOT_ROW4_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 17))

#define BG_VRAM_ADDR_SAPPHIRE_RSLINGSHOT_ROW0_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 19))
#define BG_VRAM_ADDR_SAPPHIRE_RSLINGSHOT_ROW1_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 20))
#define BG_VRAM_ADDR_SAPPHIRE_RSLINGSHOT_ROW2_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 22))
#define BG_VRAM_ADDR_SAPPHIRE_RSLINGSHOT_ROW3_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 25))
#define BG_VRAM_ADDR_SAPPHIRE_RSLINGSHOT_ROW4_TILES    BG_TILE_ADDR(TILE_INDEX(3, 8, 28))

// -------------------------------------------

#define OBJ_VRAM_ADDR_PELIPPER_ENTITY_TILES             OBJ_TILE_ADDR(TILE_INDEX(0, 8, 21))
#define SIZE_OF_PELIPPER_ENTTIY_TILES                   36 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_WAILMER_ENTITY_TILES              OBJ_TILE_ADDR(TILE_INDEX(0, 9, 25))
#define SIZE_OF_WAILMER_ENTTIY_TILES                    24 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_ZIGZAGOON_ENTITY_TILES            OBJ_TILE_ADDR(TILE_INDEX(0, 10, 17))
#define SIZE_OF_ZIGZAGOON_ENTTIY_TILES                  28 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_MINUN_ENTITY_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 11, 13))
#define SIZE_OF_MINUN_ENTTIY_TILES                      20 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_PLUSLE_ENTITY_TILES               OBJ_TILE_ADDR(TILE_INDEX(0, 12, 5))
#define SIZE_OF_PLUSLE_ENTTIY_TILES                     20 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SHROOMISH_BUMPER_TILES            OBJ_TILE_ADDR(TILE_INDEX(0, 12, 29))
#define SIZE_OF_SHROOMISH_BUMPER_TILES                  16 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SEEDOT_BASKET_TILES               OBJ_TILE_ADDR(TILE_INDEX(0, 14, 13))
#define SIZE_OF_SEEDOT_BASKET_TILES                     20 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_SEEDOT_ENTITY(seedotIx)           OBJ_TILE_ADDR(TILE_INDEX(0, 15, 1 + 12 * seedotIx))
#define SIZE_OF_SEEDOT_ENTITY_TILES                     11 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_HATCH_MACHINE_SPARKLE_FX_TILES    OBJ_TILE_ADDR(TILE_INDEX(1, 0, 5))
#define SIZE_OF_HATCH_MACHINE_SPARKLE_FX_TILES          8 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SAPPHIRE_MART_ELECTRIC_GATE_TILES OBJ_TILE_ADDR(TILE_INDEX(1, 1, 21))
#define SIZE_OF_SAPPHIRE_MART_ELECTRIC_GATE_TILES       4 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_MINUN_ELECTRICTY_FX_TILES         OBJ_TILE_ADDR(TILE_INDEX(1, 1, 25))
#define SIZE_OF_MINUN_ELECTRICTY_FX_TILES               12 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_PLUSLE_ELECTRICTY_FX_TILES        OBJ_TILE_ADDR(TILE_INDEX(1, 2, 9))
#define SIZE_OF_PLUSLE_ELECTRICTY_FX_TILES              12 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SAPPHIRE_MART_SIGN_TILES          OBJ_TILE_ADDR(TILE_INDEX(1, 2, 25))
#define SIZE_OF_SAPPHIRE_MART_SIGN_TILES                36 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_ZIGZAGOON_SPEECH_BUBBLE_TILES     OBJ_TILE_ADDR(TILE_INDEX(1, 3, 29))
#define SIZE_OF_ZIGZAGOON_SPEECH_BUBBLE_TILES           16 * TILE_SIZE_4BPP

//FX section; shared space
#define SIZE_OF_VRAM_FX_ZIGZAGZOON_ROULETTE_STOP_TILES  3 * MEM_SIZE_OF_TILE_ROW

#endif