#ifndef GUARD_CONSTANTS_MEM_LAYOUT_SHARED
#define GUARD_CONSTANTS_MEM_LAYOUT_SHARED

#include "gba/defines.h"

// 32 OUTPUT tiles (one screen width) are mapped by 0x40 bytes of data
// From a tile index perspective, 2 "tiles" of data = mapping for 1 board row.
#define MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW 0x40

//0x400
#define MEM_SIZE_OF_TILE_ROW                32 * TILE_SIZE_4BPP

// From tile_Index perspective, 2 'rows' of data, mapping a 256*256 output
#define MEM_SIZE_OF_TILEMAP_256_BY_256   MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW * 32
// From tile_Index perspective, 4 'rows' of data, mapping a 256*512 output
#define MEM_SIZE_OF_TILEMAP_256_BY_512   MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW * 64
// From tile_Index perspective, 8 'rows' of data, mapping a 512*512 output
#define MEM_SIZE_OF_TILEMAP_512_BY_512   MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW * 128


#define BG_VRAM_ADDR_CHAR_BLOCK_1_BASE   BG_TILE_ADDR(TILE_INDEX(1,0,0))
#define BG_VRAM_ADDR_CHAR_BLOCK_2_BASE   BG_TILE_ADDR(TILE_INDEX(2,0,0))
#define BG_VRAM_ADDR_CHAR_BLOCK_3_BASE   BG_TILE_ADDR(TILE_INDEX(3,0,0))


#define SIZE_OF_FULL_BLOCK_OF_TILES     16 * MEM_SIZE_OF_TILE_ROW

//Hud: all boards

#define BG_VRAM_ADDR_ALL_BOARDS_LAYER_0_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,8,0))
// Size 4 "rows of tiles" of tilemap data

#define BG_VRAM_ADDR_ALL_BOARDS_DEBUG_TILEMAP     BG_TILE_ADDR(TILE_INDEX(0,8,0))
// Size 2 "rows of tiles" of tilemap data

#define BG_VRAM_ADDR_WAS_CAUGHT_BACKDROP_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,8,0))
#define SIZE_OF_VRAM_WAS_CAUGHT_BACKDROP_TILEMAP   32 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW


#define BG_VRAM_ADDR_TIMER_TILEMAP_DATA   BG_TILE_ADDR(TILE_INDEX(0, 8, 22))
//4 "tiles" of tilemap data
#define SIZE_OF_VRAM_TIMER_TILEMAP_DATA   2 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW

#define BG_VRAM_ADDR_HUD_TILEMAP_DATA     BG_TILE_ADDR(TILE_INDEX(0, 11, 28))
//4 "tiles" of tilemap data
#define SIZE_OF_VRAM_HUD_TILEMAP_DATA     2 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW


// Tiles - Each 0x20 of space is a single 8x8 tile.

#define BG_VRAM_ADDR_HUD_TILES_A         BG_TILE_ADDR(TILE_INDEX(1, 10, 0))
#define SIZE_OF_VRAM_HUD_TILES_A         MEM_SIZE_OF_TILE_ROW
#define BG_VRAM_ADDR_HUD_TILES_B         BG_TILE_ADDR(TILE_INDEX(1, 11, 0))
#define SIZE_OF_VRAM_HUD_TILES_B         2 * MEM_SIZE_OF_TILE_ROW


// ----------------------------------

#define OBJ_VRAM_ADDR_FLIPPER_LEFT_TILES                OBJ_TILE_ADDR(TILE_INDEX(0, 0, 0))
#define SIZE_OF_VRAM_FLIPPER_TILES                      16 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_FLIPPER_RIGHT_TILES               OBJ_TILE_ADDR(TILE_INDEX(0, 0, 16))

#define OBJ_VRAM_ADDR_BALL_TILES                        OBJ_TILE_ADDR(TILE_INDEX(0, 1, 0))
#define SIZE_OF_VRAM_BALL_TILES                         4 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_PAUSE_MENU_BALL_INDICATOR_BONUS_BOARD  OBJ_TILE_ADDR(TILE_INDEX(0, 1, 4))
//Note: 2 sides worth of tiles are used
#define OBJ_VRAM_ADDR_PIKA_MON_AT_LEFT_SIDE_TILES       OBJ_TILE_ADDR(TILE_INDEX(0, 1, 4))
#define SIZE_OF_VRAM_PIKA_MON_TILES                     12 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_PIKA_MON_AT_RIGHT_SIDE_TILES      OBJ_TILE_ADDR(TILE_INDEX(0, 1, 16))

//Bonus Boards Only
#define OBJ_VRAM_ADDR_FX_BALL_SPAWN_TILES_BONUS_BOARD   OBJ_TILE_ADDR(TILE_INDEX(0, 1, 25))
#define SIZE_OF_VRAM_FX_BALL_SPAWN_TILES                16 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_PIKA_CHARGE_SPINNER_TILES         OBJ_TILE_ADDR(TILE_INDEX(0, 1, 28))
#define SIZE_OF_VRAM_PIKA_CHARGE_SPINNER_TILES          9 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_CHARGE_INDICATOR_CIRCLE_TILES     OBJ_TILE_ADDR(TILE_INDEX(0, 2, 23))
#define SIZE_OF_VRAM_CHARGE_INDICATOR_CIRCLE_TILES      4 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_CATCH_MON_ENTITY_TILES            OBJ_TILE_ADDR(TILE_INDEX(0, 3, 5))
#define SIZE_OF_VRAM_CATCH_MON_ENTITY_TILES             36 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_PORTRAIT0_TILES                   OBJ_TILE_ADDR(TILE_INDEX(0, 3, 5))
#define SIZE_OF_VRAM_PORTRAIT_TILES                     24 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_PORTRAIT1_TILES                   OBJ_TILE_ADDR(TILE_INDEX(0, 3, 29))


#define OBJ_VRAM_ADDR_HATCH_MON_ENTITY_TILES            OBJ_TILE_ADDR(TILE_INDEX(0, 4, 21))
#define SIZE_OF_VRAM_HATCH_MON_ENTITY_TILES             9 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_FX_CENTER_HOLE_GRAVITY_TILES      OBJ_TILE_ADDR(TILE_INDEX(0, 4, 30))
#define SIZE_OF_VRAM_FX_CENTER_HOLE_GRAVITY_TILES       24 * TILE_SIZE_4BPP


//Important!: this copy stays when the ball saver scene runs and overwrites the one from the FX section
#define OBJ_VRAM_ADDR_EVO_ITEM_STABLE_TILE              OBJ_TILE_ADDR(TILE_INDEX(0, 5, 22))
#define SIZE_OF_VRAM_EVO_ITEM_STABLE_TILE               16 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_PAUSE_MENU_BALL_INDICATOR_MAIN_BOARD  OBJ_TILE_ADDR(TILE_INDEX(0, 6, 6))
#define SIZE_OF_VRAM_PAUSE_MENU_BALL_INDICATOR              TILE_SIZE_4BPP


#define OBJ_VRAM_ADDR_HATCH_EGG_TILES                   OBJ_TILE_ADDR(TILE_INDEX(0, 7, 7))
#define SIZE_OF_VRAM_HATCH_EGG_TILES                    16 * TILE_SIZE_4BPP

//Main Boards only
#define OBJ_VRAM_ADDR_FX_BALL_UPGRADE_TILES_MAIN_BOARD  OBJ_TILE_ADDR(TILE_INDEX(0, 7, 23))
#define SIZE_OF_VRAM_FX_BALL_UPGRADE_TILES              16 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SPOINK_LAUNCHER_TILES             OBJ_TILE_ADDR(TILE_INDEX(0, 8, 7))
#define SIZE_OF_VRAM_SPOINK_LAUNCHER_TILES              14 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_FX_ONE_UP_TREECKO_DELIVERY_TILES  OBJ_TILE_ADDR(TILE_INDEX(1, 4, 21))
#define SIZE_OF_VRAM_FX_ONE_UP_TREECKO_DELIVERY_TILES   16 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_FX_ONE_UP_LIFE_DIGIT_TILES        OBJ_TILE_ADDR(TILE_INDEX(1, 5, 9))
#define SIZE_OF_VRAM_FX_ONE_UP_LIFE_DITIT_TILES         2 * TILE_SIZE_4BPP


//Used for incidental fx, banners for starting/completing a mode, end of mode bonus screens, etc)
#define OBJ_VRAM_ADDR_FX_BASE                           OBJ_TILE_ADDR(TILE_INDEX(1, 6, 0))

//Note: this includes extra tiles that end up unused, for the clean 9 row copy.
//When a save is loaded during a banner scroll, it loads the larger 'travel' size,
//just in case of it needing the larger travel banner. (doesn't care to preserve later tiles)
#define SIZE_OF_VRAM_MODE_BANNER_LOAD_TILES             9 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_MODE_BANNER_USED_TILES             8 * MEM_SIZE_OF_TILE_ROW + 14 * TILE_SIZE_4BPP
#define SIZE_OF_VRAM_MODE_TRAVEL_BANNER_TILES           9 * MEM_SIZE_OF_TILE_ROW + 15 * TILE_SIZE_4BPP

#define SIZE_OF_VRAM_FX_AREA_ROULETTE_SELECTED_TILES    20 * TILE_SIZE_4BPP
#define SIZE_OF_VRAM_FX_TRAVEL_CUTSCENE                 6 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_FX_TRAVEL_PAINTER                  36 * TILE_SIZE_4BPP //Loads over main cutscene tiles

#define SIZE_OF_VRAM_PIKA_SAVER_KICKBACK_TILES          9 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_BALL_SAVER_BANNER_AND_MON_TILES    9 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_END_OF_BALL_BONUS_WINDOW_TILES     10 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_GAME_OVER_TEXT_TILES               1 * MEM_SIZE_OF_TILE_ROW

#define SIZE_OF_VRAM_EVO_ITEM_SPAWN_TILES               7 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_EVO_CUTSCENE_TILES                 9 * MEM_SIZE_OF_TILE_ROW

#define SIZE_OF_VRAM_FX_CATCH_REAVEAL_SEQUENTIAL_TILES  10 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_FX_CATCH_BURST_LIGHTNING_TILES     8 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_FX_CATCH_BURST_TILE_OUTLINE        2 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_FX_CATCH_BURST_TILE_FLIGHT         8 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_FX_CATCH_BURST_TILE_ELECTRIC       6 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_FX_MON_APPEAR_CLOUD_BURST_TILES    5 * MEM_SIZE_OF_TILE_ROW
#define SIZE_OF_VRAM_FX_MON_CATCH_CUTSCENE_TILES        7 * MEM_SIZE_OF_TILE_ROW


#define SIZE_OF_VRAM_LETTER_TILE                        2 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_MON_NAME_TEXT_CHAR(charIx)        OBJ_TILE_ADDR(TILE_INDEX(1, 6, 0)) + (charIx) * SIZE_OF_VRAM_LETTER_TILE

//Note: this is logically OBJ_TILE_ADDR(TILE_INDEX(1, 6, 20)) + 2 * charIx, but that breaks compilation
#define OBJ_VRAM_ADDR_WAS_CAUGHT_TEXT_CHAR(charIx)      OBJ_TILE_ADDR(TILE_INDEX(1, 6, 0)) + (10 + charIx) * SIZE_OF_VRAM_LETTER_TILE

#define OBJ_VRAM_ADDR_MART_EVO_FOREGROUND_UX_TILES      OBJ_TILE_ADDR(TILE_INDEX(1, 7, 0))
#define SIZE_OF_VRAM_MART_EVO_FOREGROUND_UX_TILES       2 * MEM_SIZE_OF_TILE_ROW + 10 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_MART_PRICE_TENS_DIGIT_TILES       OBJ_TILE_ADDR(TILE_INDEX(1, 7, 13))
#define SIZE_OF_VRAM_MART_PRICE_DIGIT                   2 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_MART_PRICE_ONES_DIGIT_TILES       OBJ_TILE_ADDR(TILE_INDEX(1, 7, 19))

#define OBJ_VRAM_ADDR_MART_EVO_SELECTION_CHANGE_TILES   OBJ_TILE_ADDR(TILE_INDEX(1, 8, 17))
#define SIZE_OF_VRAM_MART_EVO_SELECTION_CHANGE_TILES    24 * TILE_SIZE_4BPP

//Loaded after main MON_CATCH_CUTSCENE_TILES
#define OBJ_VRAM_ADDR_FX_MON_CATCH_OPEN_BALL_TILES1     OBJ_TILE_ADDR(TILE_INDEX(1, 9, 6))
#define SIZE_OF_VRAM_FX_MON_CATCH_OPEN_BALL_TILES1      4 * TILE_SIZE_4BPP
#define OBJ_VRAM_ADDR_FX_MON_CATCH_OPEN_BALL_TILES2     OBJ_TILE_ADDR(TILE_INDEX(1, 9, 27))
#define SIZE_OF_VRAM_FX_MON_CATCH_OPEN_BALL_TILES2      4 * TILE_SIZE_4BPP

//Bonus board completion; 8 chars
#define OBJ_VRAM_ADDR_BONUS_CLEAR_SCORE_TEXT(charIx)    OBJ_TILE_ADDR(TILE_INDEX(1, 12, 12 + 2 * charIx))
#define SIZE_OF_VRAM_SCORE_TEXT_LETTER_TILE             2 * TILE_SIZE_4BPP
//Bonus board; 1 tile
#define OBJ_VRAM_ADDR_BONUS_CLEAR_SCORE_MULT_TEXT       OBJ_TILE_ADDR(TILE_INDEX(1, 12, 28))


//Note: this is logically OBJ_TILE_ADDR(TILE_INDEX(1, 13, 22 * rowIx + charIx)), but that changes compilation
#define OBJ_VRAM_ADDR_END_OF_BALL_BONUS_SUMMARY_TEXT(rowIx,charIx)  OBJ_TILE_ADDR(TILE_INDEX(1, 8, 0)) + (charIx + rowIx * 22 + 160) * TILE_SIZE_4BPP
#define SIZE_OF_VRAM_END_OF_BALL_BONUS_SUMMARY_TEXT_CHAR_TILES      TILE_SIZE_4BPP

#endif