#ifndef GUARD_CONSTANTS_MEM_LAYOUT_SPHEAL
#define GUARD_CONSTANTS_MEM_LAYOUT_SPHEAL

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_SPHEAL_LAYER_3_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_SPHEAL_LAYER_2_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,2,0))

#define BG_VRAM_ADDR_SPHEAL_LAYER_1_TILEMAP   BG_TILE_ADDR(TILE_INDEX(0,4,0))

#define BG_VRAM_ADDR_SPHEAL_TBD_TILEMAP       BG_TILE_ADDR(TILE_INDEX(0,4,10))
#define SIZE_OF_VRAM_SPHEAL_TBD_TILEMAP       10 * MEM_SIZE_OF_TILEMAP_FOR_32_TILE_ROW
// Tile_Index(0,8,0) - Tile(0,11,31) shared, for BG0 hud layer/debug


// Tiles

// BG TILE_INDEX(1, 10, 0) - BG TILE_INDEX(1, 12, 31) shared for hud

#define OBJ_VRAM_ADDR_SPHEAL_NET_TILES      OBJ_TILE_ADDR(TILE_INDEX(0, 2, 9))
#define SIZE_OF_VRAM_SPHEAL_NET_TILES       16 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SPHEAL_NET_FRONT_TILES    OBJ_TILE_ADDR(TILE_INDEX(0, 2, 25))
#define SIZE_OF_VRAM_SPHEAL_NET_FRONT_TILES     12 * TILE_SIZE_4BPP


#define OBJ_VRAM_ADDR_LEFT_SEALEO_TILES     OBJ_TILE_ADDR(TILE_INDEX(0, 3, 5))
#define OBJ_VRAM_ADDR_RIGHT_SEALEO_TILES    OBJ_TILE_ADDR(TILE_INDEX(0, 5, 5))
#define SIZE_OF_VRAM_SEALEO_TILES           48 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SPHEAL_TILES          OBJ_TILE_ADDR(TILE_INDEX(0, 7, 5))
#define SIZE_OF_VRAM_SPHEAL_TILES           9 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SPHEAL_CLIMB_SPLASH_TILES    OBJ_TILE_ADDR(TILE_INDEX(0, 7, 23))
#define SIZE_OF_VRAM_SPHEAL_CLIMB_SPLASH_TILES     9 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SPHEAL_WHISCASH_TILES     OBJ_TILE_ADDR(TILE_INDEX(0, 8, 9))
#define SIZE_OF_VRAM_SPHEAL_WHISCASH_TILES      35 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SPHEAL_PELIPPER_TILES     OBJ_TILE_ADDR(TILE_INDEX(0, 9, 13))
#define SIZE_OF_VRAM_SPHEAL_PELIPPER_TILES      36 * TILE_SIZE_4BPP

#define OBJ_VRAM_ADDR_SPHEAL_SUMMARY_TILES      OBJ_VRAM_ADDR_FX_BASE
#define SIZE_OF_VRAM_SPHEAL_SUMMARY_TILES       2 * MEM_SIZE_OF_TILE_ROW

#endif