#ifndef GUARD_CONSTANTS_MEM_LAYOUT_TITLESCREEN
#define GUARD_CONSTANTS_MEM_LAYOUT_TITLESCREEN

#include "constants/mem_layout/shared.h"


#define BG_VRAM_ADDR_TITLESCREEN_LAYER_1_TILEMAP    BG_TILE_ADDR(TILE_INDEX(0,0,0))
#define BG_VRAM_ADDR_TITLESCREEN_TILES              BG_TILE_ADDR(TILE_INDEX(1,0,0))


#define OBJ_VRAM_ADDR_TITLESCREEN_MENU_TILES        OBJ_TILE_ADDR(TILE_INDEX(0,0,0))
#define SIZE_OF_VRAM_TITLESCREEN_MENU_TILES         28 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_MENU_BUTTON_TEXT_TILE_BASE    OBJ_TILE_ADDR(TILE_INDEX(0, 0, 15))
#define VRAM_MENU_BUTTON_TEXT_TILE_OFFSET           2 * MEM_SIZE_OF_TILE_ROW

#define OBJ_VRAM_ADDR_BLANK_MENU_BUTTON_TILE_BASE   OBJ_TILE_ADDR(TILE_INDEX(1, 8, 15))

// Hand indicator, gba buttons, numbers.
#define OBJ_VRAM_ADDR_TITLESCREEN_EXTRA_TILES       OBJ_TILE_ADDR(TILE_INDEX(1,12,0))
#define SIZE_OF_VRAM_TITLESCREEN_EXTRA_TILES        1 * MEM_SIZE_OF_TILE_ROW


#endif