gIntroScene4PlusleMinun_Pal:: @ 0x080E1540
	.incbin "graphics/intro/scene4plusleminun/scene.gbapal"

gIntroScene4PlusleMinun_BG3Tilemap:: @ 0x080E1740
	.incbin "graphics/intro/scene4plusleminun/bg3_text_tilemap.bin"

gIntroScene4PlusleMinunBgTiles_Gfx:: @ 0x080E1F40
	.incbin "graphics/intro/scene4plusleminun/tiles.4bpp"

gIntroScene4PlusleMinun_BG0Tilemap:: @ 0x080E5F60
	.incbin "graphics/intro/scene4plusleminun/bg0_minun_tilemap.bin"

gIntroScene4PlusleMinun_BG1Tilemap:: @ 0x080E7F60
	.incbin "graphics/intro/scene4plusleminun/bg1_plusle_tilemap.bin"
