gIntroScene8WailmerLaunch_Pal:: @ 0x0810EA20
	.incbin "graphics/intro/scene8wailmerlaunch/scene.gbapal"

gIntroScene8WailmerLaunch_BG2Tilemap:: @ 0x0810EC20
	.incbin "graphics/intro/scene8wailmerlaunch/bg2_explosion_tilemap.bin"

gIntroScene8WailmerLaunchBgTiles_Gfx:: @ 0x0810F420
	.incbin "graphics/intro/scene8wailmerlaunch/explosion_tiles.4bpp"
	.space 0x20

gIntroScene8WailmerLaunch_Gfx:: @ 0x08112840
	.incbin "graphics/intro/scene8wailmerlaunch/sprites.4bpp"
	.space 0x20
