
gIntroScene1TorchicSprites_Pals:: @ 0x080B3AA0
	.incbin "graphics/intro/scene1torchic/sprites.gbapal"

gIntroScene1Torchic_BG3Tilemap:: @ 0x080B3CA0
	.incbin "graphics/intro/scene1torchic/bg3_text_tilemap.bin"

gIntroScene1TorchicText_Gfx:: @ 0x080B44A0
	.incbin "graphics/intro/scene1torchic/tiles.4bpp"
	.space 0x20

gIntroScene1Torchic_BG0Tilemap:: @ 0x080B9CC0
	.incbin "graphics/intro/scene1torchic/bg0_tilemap.bin"

gIntroScene1Torchic_BG2Tilemap:: @ 0x080BB4C0
	.incbin "graphics/intro/scene1torchic/bg2_dividers_tilemap.bin"

gIntroScene1Torchic_BG1Tilemap:: @ 0x080BC4C0
	.incbin "graphics/intro/scene1torchic/bg1_dividers_tilemap.bin"

gIntroScene1TorchicBall_Gfx:: @ 0x080BD4C0
	.incbin "graphics/intro/scene1torchic/ball.4bpp"
	.space 0x20

gIntroScene1TorchicSprites_Gfx:: @ 0x080C3CE0
	.incbin "graphics/intro/scene1torchic/sprites.4bpp"
