gIntroScene9BallFlight_Pal:: @ 0x08115860
	.incbin "graphics/intro/scene9ballflight/scene.gbapal"

gIntroScene9BallFlight_BG3Tilemap:: @ 0x08115A60
	.incbin "graphics/intro/scene9ballflight/bg3_clouds_tilemap.bin"

gIntroScene9BallFlightClouds_Gfx:: @ 0x08116260
	.incbin "graphics/intro/scene9ballflight/cloud_tiles.4bpp"
	.space 0x20

gIntroScene9BallFlightall_Gfx:: @ 0x08118680
	.incbin "graphics/intro/scene9ballflight/ball.4bpp"

	.incbin "graphics/intro/wailmer_swallow.4bpp"

	.incbin "graphics/intro/scene9ballflight/ball_tail.4bpp"
