gIntroScene3Treecko_Pal:: @ 0x080D4700
	.incbin "graphics/intro/scene3treecko/scene.gbapal"

gIntroScene3Treecko_BG2Tilemap:: @ 0x080D4900
	.incbin "graphics/intro/scene3treecko/bg2_tilemap.bin"

gIntroScene3Treecko_BG3Tilemap:: @ 0x080D5900
	.incbin "graphics/intro/scene3treecko/bg3_text_tilemap.bin"

gIntroScene3TreeckoBgTiles_Gfx:: @ 0x080D6100
	@ intro pane with treeko, pinball, flipper
	.incbin "graphics/intro/scene3treecko/tiles.4bpp"
	.space 0x20

gIntroScene3Treecko_BG1Tilemap:: @ 0x080DCD20
	.incbin "graphics/intro/scene3treecko/bg1_ball_tilemap.bin"

gIntroScene3Treecko_BG1TilemapA:: @ 0x080DD520
	.incbin "graphics/intro/scene3treecko/bg1_ballandflipper_tilemap.bin"

gIntroScene3Treecko_BG1TilemapB:: @ 0x080DDD20
	.incbin "graphics/intro/scene3treecko/bg1_ballflipperhit_tilemap.bin"

gIntroScene3Treecko_BG0Tilemap:: @ 0x080DE520
	.incbin "graphics/intro/scene3treecko/bg0_treecko_tilemap.bin"

gIntroScene3TreeckoTreecko_Gfx:: @ 0x080DF520
	.incbin "graphics/intro/scene3treecko/treecko.4bpp"
	.space 0x20
