gIntroScene5Mudkip_Pal:: @ 0x080E9F60
	.incbin "graphics/intro/scene5mudkip/scene.gbapal"

gIntroScene5Mudkip_BG2Tilemap:: @ 0x080EA160
	.incbin "graphics/intro/scene5mudkip/bg2_2sections_tilemap.bin"

gIntroScene5Mudkip_BG1Tilemap:: @ 0x080EB160
	.incbin "graphics/intro/scene5mudkip/bg1_1sections_tilemap.bin"

gIntroScene5Mudkip_BG3Tilemap:: @ 0x080EC160
	.incbin "graphics/intro/scene5mudkip/bg3_text_tilemap.bin"

gIntroScene5MudkipBgTiles_Gfx:: @ 0x080EC960
	.incbin "graphics/intro/scene5mudkip/text_tiles.4bpp"
	.space 0x20

gIntroScene5Mudkip_BG0Tilemap:: @ 0x080F1980
	.incbin "graphics/intro/scene5mudkip/bg0_tilemap.bin"

gIntroScene5MudkipSprites_Gfx:: @ 0x080F2180
	.incbin "graphics/intro/scene5mudkip/sprites.4bpp"
	.space 0x20

	.incbin "graphics/intro/scene5mudkip/unused_bg_tilemap.bin"
