gIntroScene6Chinchou_Pal:: @ 0x080F61A0
	.incbin "graphics/intro/scene6chinchou/scene.gbapal"

gIntroScene6Chinchou_BG3Tilemap:: @ 0x080F63A0
	.incbin "graphics/intro/scene6chinchou/bg3_burst_tilemap.bin"

gIntroScene6ChinchouBgTiles_Gfx:: @ 0x080F6BA0
	.incbin "graphics/intro/scene6chinchou/tiles.4bpp"
	.space 0x20

gIntroScene6Chinchou_BG2Tilemap:: @ 0x080FCFC0
	.incbin "graphics/intro/scene6chinchou/bg2_chinchou_tilemap.bin"

gIntroScene6Chinchou_BG0Tilemap:: @ 0x080FD7C0
	.incbin "graphics/intro/scene6chinchou/bg0_chinchou_tilemap.bin"

gIntroScene6Chinchou_BG1Tilemap:: @ 0x080FDFC0
	.incbin "graphics/intro/scene6chinchou/bg1_ball_tilemap.bin"

gIntroScene6ChinchouStars_Gfx:: @ 0x080FFFC0
	.incbin "graphics/intro/scene6chinchou/stars.4bpp"
	.space 0x20
