gBall_Pals:: @ 0x08137E14
	.incbin "graphics/stage/main/pokeball_regular.gbapal"
	.incbin "graphics/stage/main/pokeball_great.gbapal"
	.incbin "graphics/stage/main/pokeball_ultra.gbapal"
	.incbin "graphics/stage/main/pokeball_master.gbapal"
	.incbin "graphics/stage/main/pokeball_regular_flash.gbapal"
	.incbin "graphics/stage/main/pokeball_great_flash.gbapal"
	.incbin "graphics/stage/main/pokeball_ultra_flash.gbapal"
	.incbin "graphics/stage/main/pokeball_master_flash.gbapal"
	.incbin "graphics/stage/main/ball_full_white.gbapal"
	@ The following are actually unused; apparently, these were considered
	@ for the freeze trap at some point, but were switched to pure white instead.
	.incbin "graphics/stage/main/pokeball_regular_frozen.gbapal"
	.incbin "graphics/stage/main/pokeball_great_frozen.gbapal"
	.incbin "graphics/stage/main/pokeball_ultra_frozen.gbapal"
	.incbin "graphics/stage/main/pokeball_master_frozen.gbapal"
