gBonusFieldSelectBackgroundDimSpriteSet:: @ 0x086A699E
.2byte 4
    packed_sprite_oaml x=0x0, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x49, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_16x32, tileNum=0x4d, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x20, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x8, tileNum=0xc9, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x20, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_16x8, tileNum=0xcd, paletteNum=PAL_IX_0

gBonusFieldSelectDusclopsNameSpriteSet:: @ 0x086A69C0
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x180, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x184, paletteNum=PAL_IX_0

gBonusFieldSelectKecleonNameSpriteSet:: @ 0x086A69D2
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x188, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x18c, paletteNum=PAL_IX_0

gBonusFieldSelectSphealNameSpriteSet:: @ 0x086A69E4
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x190, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x194, paletteNum=PAL_IX_0

gBonusFieldSelectGroudonNameSpriteSet:: @ 0x086A69F6
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x198, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x19c, paletteNum=PAL_IX_0

gBonusFieldSelectKyogreNameSpriteSet:: @ 0x086A6A08
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x1c0, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x1c4, paletteNum=PAL_IX_0

gBonusFieldSelectRayquazaNameSpriteSet:: @ 0x086A6A1A
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x1c8, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x1cc, paletteNum=PAL_IX_0
