gFieldSelectFullHighlightSpriteSet:: @ 0x086A6830
.2byte 1
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x9, paletteNum=PAL_IX_0

gFieldSelectFullShadowSpriteSet:: @ 0x086A683A
.2byte 9
    packed_sprite_oaml x=0x0, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x0, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_64x64, tileNum=0x48, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x16, tileNum=0x8, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x30, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x48, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x48, paletteNum=PAL_IX_0

gFieldSelectDim3SpriteSet:: @ 0x086A6884
.2byte 13
    packed_sprite_oaml x=0x0, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x0, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x16, tileNum=0x8, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x30, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x48, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x48, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x10, y=0x30, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x9c, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x30, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_16x32, tileNum=0xce, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x30, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_16x32, tileNum=0x4e, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x48, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x32, tileNum=0x48, paletteNum=PAL_IX_0

gFieldSelectDim2SpriteSet:: @ 0x086A68EE
.2byte 11
    packed_sprite_oaml x=0x0, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x0, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x16, tileNum=0x8, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x30, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x4f, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x20, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_64x64, tileNum=0x40, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x48, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4c, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x60, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x48, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x60, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4c, paletteNum=PAL_IX_0

gFieldSelectDim1SpriteSet:: @ 0x086A6948
.2byte 6
    packed_sprite_oaml x=0x40, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x16, tileNum=0x8, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x0, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_64x32, tileNum=0x94, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_64x32, tileNum=0x14, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x10, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x1c, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x40, y=0x50, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_8x32, tileNum=0x1d, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x0, y=0x20, objMode=ST_OAM_OBJ_BLEND, spriteSize=SPRITE_SIZE_16x16, tileNum=0x114, paletteNum=PAL_IX_0

gFieldSelectRubyBoardNameHighlightSpriteSet:: @ 0x086A697A
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x140, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x144, paletteNum=PAL_IX_0

gFieldSelectSapphireBoardNameHighlightSpriteSet:: @ 0x086A698C
.2byte 2
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x148, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x14c, paletteNum=PAL_IX_0
