gFieldSelectBallSpeedNormal0SpriteSet:: @ 0x086A6A2C
.2byte 5
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x150, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x154, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_32x16, tileNum=0x158, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x8, y=0x10, spriteSize=SPRITE_SIZE_8x16, tileNum=0x11f, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x30, y=0x10, spriteSize=SPRITE_SIZE_8x16, hFlip=0x1,  tileNum=0x11f, paletteNum=PAL_IX_1

gFieldSelectBallSpeedNormal1SpriteSet:: @ 0x086A6A56
.2byte 5
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x150, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x154, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_32x16, tileNum=0x158, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x7, y=0x10, spriteSize=SPRITE_SIZE_8x16, tileNum=0x11f, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x31, y=0x10, spriteSize=SPRITE_SIZE_8x16, hFlip=0x1,  tileNum=0x11f, paletteNum=PAL_IX_1

gFieldSelectBallSpeedSlow0SpriteSet:: @ 0x086A6A80
.2byte 5
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x150, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x154, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x8, y=0x10, spriteSize=SPRITE_SIZE_8x16, tileNum=0x11f, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x30, y=0x10, spriteSize=SPRITE_SIZE_8x16, hFlip=0x1,  tileNum=0x11f, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_32x16, tileNum=0x15c, paletteNum=PAL_IX_1

gFieldSelectBallSpeedSlow1SpriteSet:: @ 0x086A6AAA
.2byte 5
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x150, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x154, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x7, y=0x10, spriteSize=SPRITE_SIZE_8x16, tileNum=0x11f, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x31, y=0x10, spriteSize=SPRITE_SIZE_8x16, hFlip=0x1,  tileNum=0x11f, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_32x16, tileNum=0x15c, paletteNum=PAL_IX_1
