gPokedexCursorHandSpriteSet:: @ 0x086A553C
.2byte 1
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x0, paletteNum=PAL_IX_0

.2byte 1
    packed_sprite_oaml x=0x1, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x0, paletteNum=PAL_IX_0


gPokedexPressSelectText0SpriteSet:: @ 0x086A5550
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0xC, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText1SpriteSet:: @ 0x086A556A
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x12, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0xC, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText2SpriteSet:: @ 0x086A5584
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x1A, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0xC, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText3SpriteSet:: @ 0x086A559E
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x22, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0xC, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText4SpriteSet:: @ 0x086A55B8
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x2A, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0xC, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText5SpriteSet:: @ 0x086A55D2
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x32, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0xC, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText6SpriteSet:: @ 0x086A55EC
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x3A, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0xC, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText7SpriteSet:: @ 0x086A5606
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x42, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x4A, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText8SpriteSet:: @ 0x086A5620
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x4E, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0

gPokedexPressSelectText9SpriteSet:: @ 0x086A563A
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x52, paletteNum=PAL_IX_0

gPokedexPressSelectText10SpriteSet:: @ 0x086A5654
.2byte 3
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x16, tileNum=0x4, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x30, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x10, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x56, paletteNum=PAL_IX_0

gPokedexMonPortraitSpriteSet:: @ 0x086A566E
.2byte 6
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x1A0, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x1A4, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x1A8, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x16, tileNum=0x1AC, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_16x16, tileNum=0x1B0, paletteNum=PAL_IX_1
    packed_sprite_oaml x=0x20, y=0x10, spriteSize=SPRITE_SIZE_16x16, tileNum=0x1B4, paletteNum=PAL_IX_1

gPokedexCatchSpriteSpriteSet:: @ 0x086A56A0
.2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x32, tileNum=0x1C0, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x32, tileNum=0x1D0, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x0, y=0x20, spriteSize=SPRITE_SIZE_32x16, tileNum=0x1D8, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x20, y=0x20, spriteSize=SPRITE_SIZE_16x16, tileNum=0x1E0, paletteNum=PAL_IX_2

.2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x32, tileNum=0x1E4, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x32, tileNum=0x1F4, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x0, y=0x20, spriteSize=SPRITE_SIZE_32x16, tileNum=0x1FC, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x20, y=0x20, spriteSize=SPRITE_SIZE_16x16, tileNum=0x204, paletteNum=PAL_IX_2

.2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_32x32, tileNum=0x208, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x20, y=0x0, spriteSize=SPRITE_SIZE_16x32, tileNum=0x218, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x0, y=0x20, spriteSize=SPRITE_SIZE_32x16, tileNum=0x220, paletteNum=PAL_IX_2
    packed_sprite_oaml x=0x20, y=0x20, spriteSize=SPRITE_SIZE_16x16, tileNum=0x228, paletteNum=PAL_IX_2

gPokedexScrollIndicatorSpriteSet:: @ 0x086A5706
.2byte 1
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_8x8, tileNum=0x238, paletteNum=PAL_IX_0

gPokedexStartTransmissionPopupSpriteSet:: @ 0x086A5710
.2byte 5
    packed_sprite_oaml x=-0x34, y=-0x1E, spriteSize=SPRITE_SIZE_64x32, tileNum=0x60, paletteNum=PAL_IX_0
    packed_sprite_oaml x=-0x34, y=0x2, spriteSize=SPRITE_SIZE_64x32, tileNum=0x80, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0xC, y=-0x1E, spriteSize=SPRITE_SIZE_32x64, tileNum=0xa0, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x2C, y=-0x1E, spriteSize=SPRITE_SIZE_8x32, tileNum=0xc0, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x2C, y=0x2, spriteSize=SPRITE_SIZE_8x32, tileNum=0xc4, paletteNum=PAL_IX_0

gPokedexTransmittingPopupSpriteSet:: @ 0x086A573A
.2byte 2
    packed_sprite_oaml x=-0x28, y=-0xB, spriteSize=SPRITE_SIZE_64x32, tileNum=0xc8, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x18, y=-0xB, spriteSize=SPRITE_SIZE_16x32, tileNum=0xe8, paletteNum=PAL_IX_0

gPokedexTransmissionErrorPopupSpriteSet:: @ 0x086A574C
.2byte 2
    packed_sprite_oaml x=-0x30, y=-0xB, spriteSize=SPRITE_SIZE_64x32, tileNum=0xf0, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x10, y=-0xB, spriteSize=SPRITE_SIZE_32x32, tileNum=0x110, paletteNum=PAL_IX_0

gPokedexTransferCompletePopupSpriteSet:: @ 0x086A575E
.2byte 3
    packed_sprite_oaml x=-0x38, y=-0xB, spriteSize=SPRITE_SIZE_64x32, tileNum=0x120, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x8, y=-0xB, spriteSize=SPRITE_SIZE_32x32, tileNum=0x140, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x28, y=-0xB, spriteSize=SPRITE_SIZE_16x32, tileNum=0x150, paletteNum=PAL_IX_0

gPokedexDeleteConfirmationPopupSpriteSet:: @ 0x086A5778
.2byte 2
    packed_sprite_oaml x=-0x2C, y=-0x10, spriteSize=SPRITE_SIZE_64x32, tileNum=0x158, paletteNum=PAL_IX_0
    packed_sprite_oaml x=0x14, y=-0x10, spriteSize=SPRITE_SIZE_32x32, tileNum=0x178, paletteNum=PAL_IX_0

gPokedexHatchSpriteSpriteSet:: @ 0x086A578A
.2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x240, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x244, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x246, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x248, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x249, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x24D, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x24F, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x251, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x252, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x256, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x258, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x25A, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x25B, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x25F, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x261, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x263, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x264, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x268, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x26A, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x26C, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x26D, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x271, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x273, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x275, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x276, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x27A, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x27C, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x27E, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x27F, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x283, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x285, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x287, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x288, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x28C, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x28E, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x290, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x291, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x295, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x297, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x299, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x29A, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x29E, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x2A0, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x2A2, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x2A3, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x2A7, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x2A9, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x2AB, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x2AC, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x2B0, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x2B2, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x2B4, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x2B5, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x2B9, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x2BB, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x2BD, paletteNum=PAL_IX_3

    .2byte 4
    packed_sprite_oaml x=0x0, y=0x0, spriteSize=SPRITE_SIZE_16x16, tileNum=0x2BE, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x0, spriteSize=SPRITE_SIZE_8x16, tileNum=0x2C2, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x0, y=0x10, spriteSize=SPRITE_SIZE_16x8, tileNum=0x2C4, paletteNum=PAL_IX_3
    packed_sprite_oaml x=0x10, y=0x10, spriteSize=SPRITE_SIZE_8x8, tileNum=0x2C6, paletteNum=PAL_IX_3
