#ifndef GUARD_CONSTANTS_DUSCLOPS_STATES_H
#define GUARD_CONSTANTS_DUSCLOPS_STATES_H
#include "bonus_board.h"

enum DusclopsBoardStates{
    DUSCLOPS_BOARD_STATE_0_INTRO = 0,
    DUSCLOPS_BOARD_STATE_1_DUSKULL_PHASE = 1,
    DUSCLOPS_BOARD_STATE_2_INIT_DUSCLOPS_PHASE = 2,
    DUSCLOPS_BOARD_STATE_3_DUSCLOPS_PHASE = 3,
    DUSCLOPS_BOARD_STATE_4_INIT_SCORE_PHASE = 4,
    DUSCLOPS_BOARD_STATE_SCORE_PHASE = 5,
    DUSCLOPS_BOARD_STATE_SCORE_COUNTING_FINISHED = 6
};

enum DusclopsEntityColisionMode{
    DUSCLOPS_ENTITY_COLLISION_MODE_NONE = 0,
    DUSCLOPS_ENTITY_COLLISION_MODE_DUSKULL = 1,
    DUSCLOPS_ENTITY_COLLISION_MODE_DUSCLOPS = 2
};

enum DuskullEntityState{
    DUSKULL_ENTITY_STATE_SPAWN = 0,
    DUSKULL_ENTITY_STATE_APPEARS = 1,
    DUSKULL_ENTITY_STATE_MOVE_LEFT = 2,
    DUSKULL_ENTITY_STATE_MOVE_RIGHT = 3,
    DUSKULL_ENTITY_STATE_HIT = 4,
    DUSKULL_ENTITY_STATE_DYING = 5,
    DUSKULL_ENTITY_STATE_ESCAPE_WHILE_WALKING_LEFT = 6,
    DUSKULL_ENTITY_STATE_ESCAPE_WHILE_WALKING_RIGHT = 7,
    DUSKULL_ENTITY_STATE_ESCAPE = 8,
    DUSKULL_ENTITY_STATE_CLEANUP = 9
};

enum DuskullFramesetIx{
    DUSKULL_FRAME_MOVE_LEFT_START = 0,
    DUSKULL_FRAME_MOVE_LEFT_END = 3,
    DUSKULL_FRAME_NEUTRAL_FACING = 6,
    DUSKULL_FRAME_MOVE_RIGHT_START = 7,
    DUSKULL_FRAME_MOVE_RIGHT_END = 10,
    DUSKULL_FRAME_TURN_TO_FACE_LEFT_END = 13,
    DUSKULL_FRAME_HIT = 14,
    DUSKULL_FRAME_DYING = 15,
    DUSKULL_FRAME_ESCAPE_PREP = 18,
    DUSKULL_FRAME_ESCAPE = 25
};

enum DuskullTileOffset{
    DUSKULL_TILE_OFFSET_QUARTER_FACING = 3,
    DUSKULL_TILE_OFFSET_FACE_FORWARD = 4
};

enum DusclopsEntityState{
    DUSCLOPS_ENTITY_STATE_INIT = 0,
    DUSCLOPS_ENTITY_STATE_INTRO_APPEARANCE = 1,
    DUSCLOPS_ENTITY_STATE_GUARD_READY = 2,
    DUSCLOPS_ENTITY_STATE_WALKING = 3,
    DUSCLOPS_ENTITY_STATE_HIT = 4,
    DUSCLOPS_ENTITY_STATE_HIT_STUN = 5,
    DUSCLOPS_ENTITY_STATE_HIT_ABSORB_ZONE = 6,
    DUSCLOPS_ENTITY_STATE_ABSORBED_BALL = 7,
    DUSCLOPS_ENTITY_STATE_VANISH = 8
};

enum DusclopsFramesetIx{
    DUSCLOPS_FRAME_WALK_NEUTRAL = 0,
    DUSCLOPS_FRAME_LEFT_FOOT_LANDS = 2,
    DUSCLOPS_FRAME_WALK_NEUTRAL_RIGHT_FOOT_FORWARD = 4,
    DUSCLOPS_FRAME_RIGHT_FOOT_LANDS = 6,
    DUSCLOPS_FRAME_RIGHT_FOOT_FORWARD = 7,
    DUSCLOPS_FRAME_ABSORB_START = 9,
    DUSCLOPS_FRAME_ABSORB_VORTEX_START = 10,
    DUSCLOPS_FRAME_ABSORB_VORTEX_END = 12,
    DUSCLOPS_FRAME_ABSORB_LAUNCH_PREP = 15,
    DUSCLOPS_FRAME_ABSOLB_LAUNCH = 16,
    DUSCLOPS_FRAME_INTRO_START = 21,
    DUSCLOPS_FRAME_INTRO_FOOTSTEP_LEFT = 23,
    DUSCLOPS_FRAME_INTRO_FOOTSTEP_RIGHT = 27,
    DUSCLOPS_FRAME_INTRO_END = 28,
};

enum DusclopsTileOffset{
    DUSCLOPS_TILE_OFFSET_HIT = 7,
    DUSCLOPS_TILE_OFFSET_ABSORB_START = 8,
    DUSCLOPS_TILE_OFFSET_VANQUISHED = 15
};

#endif // GUARD_CONSTANTS_DUSCLOPS_STATES_H