#ifndef GUARD_CONSTANTS_GROUDON_STATES_H
#define GUARD_CONSTANTS_GROUDON_STATES_H
#include "bonus_board.h"

enum GroudonEntityState{
    GROUDON_ENTITY_STATE_SPAWN = 0,
    GROUDON_ENTITY_STATE_ENTRY = 1,
    GROUDON_ENTITY_STATE_IDLE = 2,
    GROUDON_ENTITY_STATE_FIREBALL = 3,
    GROUDON_ENTITY_STATE_SHOCKWAVE = 4,
    GROUDON_ENTITY_STATE_JUMP = 5,
    GROUDON_ENTITY_STATE_SUFFICIENT_HITS = 6,
    GROUDON_ENTITY_STATE_PREPARE_LEAVING = 7,
    GROUDON_ENTITY_STATE_LEAVES = 8,
    GROUDON_ENTITY_STATE_CAPTURE = 9,
    GROUDON_ENTITY_STATE_FINISHED = 10,
};

enum GroudonBoulderState{
    GROUDON_BOULDER_STATE_SPAWN = 0,
    GROUDON_BOULDER_STATE_DROP = 1,
    GROUDON_BOULDER_STATE_UNHIT = 2,
    GROUDON_BOULDER_STATE_HIT_ONCE = 3,
    GROUDON_BOULDER_STATE_HIT_TWICE = 4,
    GROUDON_BOULDER_STATE_CLEANUP = 5,
};

enum GroudonFirePillarState{
    GROUDON_FIRE_PILLAR_STATE_SPAWN = 0,
    GROUDON_FIRE_PILLAR_STATE_FULL_SIZE_SETUP = 1,
    GROUDON_FIRE_PILLAR_STATE_FULL_SIZE_VULNERABLE = 2,
    GROUDON_FIRE_PILLAR_STATE_TALL_SETUP = 3,
    GROUDON_FIRE_PILLAR_STATE_TALL_VULNERABLE = 4,
    GROUDON_FIRE_PILLAR_STATE_MEDIUM_SETUP = 5,
    GROUDON_FIRE_PILLAR_STATE_MEDIUM_VULNERABLE = 6,
    GROUDON_FIRE_PILLAR_STATE_SHORT_SETUP = 7,
    GROUDON_FIRE_PILLAR_STATE_SHORT_VULNERABLE = 8,
    GROUDON_FIRE_PILLAR_STATE_DESTROYED = 9,
    GROUDON_FIRE_PILLAR_STATE_CLEANUP = 10,
};

enum GroudonCollisionMode{
    GROUDON_COLLISION_MODE_NONE = 0,
    GROUDON_COLLISION_MODE_ACTIVE = 1
};

#endif // GUARD_CONSTANTS_GROUDON_STATES_H
