#ifndef GUARD_CONSTANTS_KECLEON_STATES_H
#define GUARD_CONSTANTS_KECLEON_STATES_H
#include "bonus_board.h"

enum KecleonBoardState{
    KECLEON_BOARD_STATE_INTRO = 0,
    KECLEON_BOARD_STATE_BATTLE_PHASE = 1,
    KECLEON_BOARD_STATE_ENDING_BANNER = 2,
    KECLEON_BOARD_STATE_SCORING = 3,
    KECLEON_BOARD_STATE_SCORE_COUNTING_FINISHED = 4,
};

enum KecleonEntityState{
    KECLEON_ENTITY_STATE_SPAWN = 0,
    KECLEON_ENTITY_STATE_WALK_TO_CENTER = 1,
    KECLEON_ENTITY_STATE_VANISH = 2,
    KECLEON_ENTITY_STATE_CHOOSE_WALK_LOCATION = 3,
    KECLEON_ENTITY_STATE_WALK_TO_TARGET = 4,
    KECLEON_ENTITY_STATE_CHOOSE_RUN_LOCATION = 5,
    KECLEON_ENTITY_STATE_RUN_TO_TARGET = 6,
    KECLEON_ENTITY_STATE_RESTING = 7,
    KECLEON_ENTITY_STATE_OBSERVING = 8,
    KECLEON_ENTITY_STATE_HIT_WHILE_STANDING = 9,
    KECLEON_ENTITY_STATE_KNOCKED_OVER = 10,
    KECLEON_ENTITY_STATE_HIT_WHILE_DOWN = 11,
    KECLEON_ENTITY_STATE_RESPOND_TO_HIT = 12,
    KECLEON_ENTITY_STATE_RISE_FROM_DOWN = 13,
    KECLEON_ENTITY_STATE_SURRENDERS = 14,
    KECLEON_ENTITY_STATE_ENDING = 15,
};

enum KecleonCollisionMode{
    KECLEON_COLLISION_MODE_NONE = 0,
    KECLEON_COLLISION_MODE_STANDING = 1,
    KECLEON_COLLISION_MODE_KNOCKED_OVER = 2,
};

enum KecleonCollisionTrigger{
    KECLEON_TRIGGER_FLOWERS = 8,
    KECLEON_TRIGGER_BUSH_GROUP_0 = 9,
    KECLEON_TRIGGER_WATER = 10,
    KECLEON_TRIGGER_BUSH_GROUP_1 = 11,
    KECLEON_TRIGGER_BUSH_GROUP_2 = 12,
};

#endif //GUARD_CONSTANTS_KECLEON_STATES_H