#ifndef GUARD_CONSTANTS_KYOGRE_STATES_H
#define GUARD_CONSTANTS_KYOGRE_STATES_H
#include "bonus_board.h"

enum KyogreEntityState{
    KYOGRE_ENTITY_STATE_INIT = 0,
    KYOGRE_ENTITY_STATE_ENTRY = 1,
    KYOGRE_ENTITY_STATE_RETURN_TO_TOP = 2,
    KYOGRE_ENTITY_STATE_DIVE = 3,
    KYOGRE_ENTITY_STATE_IDLE = 4,
    KYOGRE_ENTITY_STATE_SPAWN_WHIRLPOOLS = 5,
    KYOGRE_ENTITY_STATE_SHOCKWAVE = 6,
    KYOGRE_ENTITY_STATE_SUFFICIENT_HITS = 7,
    KYOGRE_ENTITY_STATE_PRESUMED_UNREACHABLE = 8,
    KYOGRE_ENTITY_STATE_PREPARE_LEAVING = 9,
    KYOGRE_ENTITY_STATE_CAPTURE = 10,
    KYOGRE_ENTITY_STATE_UNDERWATER = 11,
    KYOGRE_ENTITY_STATE_LEAP = 12,
    KYOGRE_ENTITY_STATE_FINISHED = 13,
};

enum KyogreCollisionMode{
    KYOGRE_COLLISION_MODE_NONE = 0,
    KYOGRE_COLLISION_MODE_TOP_POSITION = 1,
    KYOGRE_COLLISION_MODE_EMERGING_FROM_WATER = 2,
    KYOGRE_COLLISION_MODE_JUMPING = 3,
};

enum KyogreFreezePhase{
    KYOGRE_FREEZE_PHASE_ENCLOSE_BALL = 0,
    KYOGRE_FREEZE_PHASE_CRACKING_HIT_SETUP = 1,
    KYOGRE_FREEZE_PHASE_CRACKED_VULNERABLE = 2,
    KYOGRE_FREEZE_PHASE_SPLITTING_HIT_SETUP = 3,
    KYOGRE_FREEZE_PHASE_SPLIT_VULNERABLE = 4,
    KYOGRE_FREEZE_PHASE_BREAKING_HIT_SETUP = 5,
    KYOGRE_FREEZE_PHASE_LAST_HIT_VULNERABLE = 6,
    KYOGRE_FREEZE_PHASE_DESPAWN = 7,
};

enum KyogreWhirlpoolPhase{
    KYOGRE_WHIRLPOOL_PHASE_INIT = 0,
    KYOGRE_WHIRLPOOL_PHASE_SPAWN = 1,
    KYOGRE_WHIRLPOOL_PHASE_FULL = 2,
    KYOGRE_WHIRLPOOL_PHASE_FULL_CAUGHT_BALL = 3,
    KYOGRE_WHIRLPOOL_PHASE_SHRINKING_CAUGHT_BALL = 4,
    KYOGRE_WHIRLPOOL_PHASE_SHRUNK = 5,
};

#endif //GUARD_CONSTANTS_KYOGRE_STATES_H