#ifndef GUARD_CONSTANTS_RAYQUAZA_STATES_H
#define GUARD_CONSTANTS_RAYQUAZA_STATES_H
#include "bonus_board.h"

enum RayquazaEntityState{
    RAYQUAZA_ENTITY_STATE_SPAWN = 0,
    RAYQUAZA_ENTITY_STATE_ENTRY = 1,
    RAYQUAZA_ENTITY_STATE_BOUNCE_IN_PLACE = 2,
    RAYQUAZA_ENTITY_STATE_LANDS = 3,
    RAYQUAZA_ENTITY_STATE_FLIES_UP = 4,
    RAYQUAZA_ENTITY_STATE_BOUNCES_SIDEWAYS = 5,
    RAYQUAZA_ENTITY_STATE_LIGHTNING_ATTACK = 6,
    RAYQUAZA_ENTITY_STATE_WAIT_FOR_FLYBY = 7,
    RAYQUAZA_ENTITY_STATE_FLYBY = 8,
    RAYQUAZA_ENTITY_STATE_SUFFICIENT_HITS = 9,
    RAYQUAZA_ENTITY_STATE_YELLS = 10,
    RAYQUAZA_ENTITY_STATE_DEPARTS = 11,
    RAYQUAZA_ENTITY_STATE_BOARD_CLEANUP = 12,
    RAYQUAZA_ENTITY_STATE_FLYDOWN = 13,
    RAYQUAZA_ENTITY_STATE_CAPTURE = 14,
    RAYQUAZA_ENTITY_STATE_FINISHED = 15,
};

enum RayquazaWhirlwindState{
    RAYQUAZA_WHIRLWIND_STATE_INIT = 0,
    RAYQUAZA_WHIRLWIND_STATE_SPAWN = 1,
    RAYQUAZA_WHIRLWIND_STATE_FULL = 2,
    RAYQUAZA_WHIRLWIND_STATE_FULL_CAUGHT_BALL = 3,
    RAYQUAZA_WHIRLWIND_STATE_SHRINKING_CAUGHT_BALL = 4,
    RAYQUAZA_WHIRLWIND_STATE_SHRUNK = 5,
};

enum RayquazaLightningState{
    RAYQUAZA_LIGHTNING_STATE_INACTIVE = 0,
    RAYQUAZA_LIGHTNING_STATE_CHARGING = 1,
    RAYQUAZA_LIGHTNING_STATE_TARGET_BALL = 2,
    RAYQUAZA_LIGHTNING_STATE_STRIKING = 3,
    RAYQUAZA_LIGHTNING_STATE_4 = 4,
};

#endif //GUARD_CONSTANTS_RAYQUAZA_STATES_H