#ifndef GUARD_CONSTANTS_SAPPHIRE_STATES_H
#define GUARD_CONSTANTS_SAPPHIRE_STATES_H
#include "main_board.h"

enum SapphireCollisionTrigger{
    SAPPHIRE_TRIGGER_MODE_START_BALL_LOCK = 1,
    SAPPHIRE_TRIGGER_2 = 2,
    SAPPHIRE_TRIGGER_3 = 3,
    SAPPHIRE_TRIGGER_4 = 4,
    SAPPHIRE_TRIGGER_5 = 5,
    SAPPHIRE_TRIGGER_6 = 6,
    SAPPHIRE_TRIGGER_7 = 7,
    SAPPHIRE_TRIGGER_8 = 8,
    SAPPHIRE_TRIGGER_9 = 9,
    SAPPHIRE_TRIGGER_10 = 10,
    SAPPHIRE_TRIGGER_11 = 11,
    SAPPHIRE_TRIGGER_12 = 12,
    SAPPHIRE_TRIGGER_13 = 13,
    SAPPHIRE_TRIGGER_14 = 14,
    SAPPHIRE_TRIGGER_15 = 15,
};

/*
enum RubyCollisionZone{
    RUBY_ZONE_LAUNCH_CHUTE = 0,
    RUBY_ZONE_COIN_LANE_TOP = 1,
    RUBY_ZONE_EVO_LANE_TOP = 2,
    RUBY_ZONE_LEFT_BALL_UPGRADE_LANE = 3,
    RUBY_ZONE_CENTER_BALL_UPGRADE_LANE = 4,
    RUBY_ZONE_RIGHT_BALL_UPGRADE_LANE = 5,
    RUBY_ZONE_GET_LANE_TOP = 6,
    RUBY_ZONE_COIN_LANE_BOTTOM = 7,
    RUBY_ZONE_EVO_LANE_BOTTOM = 8,
    RUBY_ZONE_GET_LANE_BOTTOM = 9,
    RUBY_ZONE_H_OUTLANE = 10,
    RUBY_ZONE_O_INLANE = 11,
    RUBY_ZONE_L_INLANE = 12,
    RUBY_ZONE_E_OUTLANE = 13,
    RUBY_ZONE_NUZLEAF_RAMP = 14,
};
*/

#endif //GUARD_CONSTANTS_SAPPHIRE_STATES_H