#ifndef GUARD_CONSTANTS_SPHEAL_STATES_H
#define GUARD_CONSTANTS_SPHEAL_STATES_H
#include "bonus_board.h"

enum SphealBoardState{
    SPHEAL_BOARD_STATE_INTRO = 0,
    SPHEAL_BOARD_STATE_ACTIVE_PHASE = 1,
    SPHEAL_BOARD_STATE_ENDING = 2,
    SPHEAL_BOARD_STATE_SCORE_DISPLAY = 3,
    SPHEAL_BOARD_STATE_SCORE_DISPLAY_CLEANUP = 4,
    SPHEAL_BOARD_STATE_PREPARE_RETURN = 5,
};

//NOTE: Hit stun tracked with a timer, rather than a state
enum SealeoEntityState{
    SEALEO_ENTITY_STATE_INIT = 0,
    SEALEO_ENTITY_STATE_READY = 1,
    SEALEO_ENTITY_STATE_ANTICIPATE_BOUNCE = 2,
    SEALEO_ENTITY_STATE_DONE_BOUNCING = 3,
};

//Applies to the ball and spheal in ramp/bouncing
enum KnockdownPhase{
    SPHEAL_KNOCKDOWN_PHASE_WAITING = 0,
    SPHEAL_KNOCKDOWN_PHASE_BALL_PROXIMITY_CROSSED = 1,
    SPHEAL_KNOCKDOWN_PHASE_PREPARE_BOUNCE = 2,
    SPHEAL_KNOCKDOWN_PHASE_VERTICAL_BOUNCE = 3,
    SPHEAL_KNOCKDOWN_PHASE_BOUNCE_TO_HOOP = 4,
    SPHEAL_KNOCKDOWN_PHASE_DROPPED = 5,
};

enum SphealEntityState{
    SPHEAL_ENTITY_STATE_INIT = 0,
    SPHEAL_ENTITY_STATE_CHOOSE_SPAWN = 1,
    SPHEAL_ENTITY_STATE_SURFACE_IN_WATER = 2,
    SPHEAL_ENTITY_STATE_SWIMMING = 3,
    SPHEAL_ENTITY_STATE_HIT = 4,
    SPHEAL_ENTITY_STATE_HIT_WHILE_SWIMMING = 5,
    SPHEAL_ENTITY_STATE_DIVING = 6,
    SPHEAL_ENTITY_STATE_SURFACE_AT_RAMP = 7,
    SPHEAL_ENTITY_STATE_CLIMBING_RAMP = 8,
    SPHEAL_ENTITY_STATE_SLIDE_PLUNGE = 9,
    SPHEAL_ENTITY_STATE_HIT_UP_RAMP = 10,
    SPHEAL_ENTITY_STATE_FOLLOW_RAMP = 11,
    SPHEAL_ENTITY_STATE_AWAIT_BOUNCE = 12,
    SPHEAL_ENTITY_STATE_BOUNCING = 13,
    SPHEAL_ENTITY_STATE_LAND_AND_WALK_TO_WATER = 14,
};

enum TargetSealeoPosition{
    TARGET_SEALEO_LEFT = 0,
    TARGET_SEALEO_RIGHT = 1,
};

enum SphealMovementDirection{
    SPHEAL_MOVING_LEFT = 0,
    SPHEAL_MOVING_RIGHT = 1,
};

enum SphealSpawnPositionVariant{
    SPHEAL_SPAWN_UNDEFINED_POSITION = -1,
    SPHEAL_SPAWN_AT_LEFT_RAMP = 0,
    SPHEAL_SPAWN_AT_RIGHT_RAMP = 1,
    SPHEAL_SPAWN_AT_TOP_ROW = 2,
    SPHEAL_SPAWN_AT_CENTER_HIGH_ROW = 3,
    SPHEAL_SPAWN_AT_CENTER_LOW_ROW = 4,
    SPHEAL_SPAWN_AT_LOWEST_ROW = 5,
};

enum SphealCollisionType{
    SPHEAL_COLLISION_TYPE_INACTIVE = 0,
    SPHEAL_COLLISION_TYPE_SWIMMING = 1,
    SPHEAL_COLLISION_TYPE_ON_RAMP = 2,
    SPHEAL_COLLISION_TYPE_WALK_DOWN = 3,
};

#endif //GUARD_CONSTANTS_SPHEAL_STATES_H